### ISSUE TITLE
feat：支持回调被封禁通知

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10018]
当回调被封禁时，支持企业微信通知。

通知内容：你注册的回调 [xxx]因[xxx]被封禁。若需继续使用，请联系管理员恢复。

**Comment by mingshewhe** [comment]
目前通知是已有通知功能，但是通知是给回调创建人，如果是第三方平台回调地址，关注人并不是回调创建人，而是第三方平台，希望能够通知给第三方平台。

实现方案：
1. 修改熔断机制，由原来是请求30次，100%失败，改成100%失败的持续时间达到12小时，则熔断，持续时间可以通过配置callback.failureDisableTimePeriod修改
2. 增加回调请求OkHttpMetricsEventListener度量，在监控平台(如grafana)配置状态非200的请求数，然后告警通知
![image](https://github.com/TencentBlueKing/bk-ci/assets/22971705/221dbc65-43dd-4f73-84b1-885d85ca17a7)
