### ISSUE TITLE
支持批量安装 Agent

### ISSUE THREAD

**Issue by irwinsun** [TencentBlueKing/bk-ci#10024]
### 需求背景：
当用户有大批新机需要安装时，希望能简化安装流程，自动化去添加构建机 
比如支持通过接口导入或批量导入

### 目前已有的batch_install.bat 方案
- 下载好某个项目下的的agent.zip（未安装过）
- 到目标机器解压后执行 batch_install.bat (linux 也可照提供一个类似的 shell 脚本)
  - batch_install.bat 会拉起 installer进程
  - installer 进程向后台请求batch_zip接口，分配得到新 agent信息用于安装

### 请根据上述需求描述和已有方案综合考虑细化改进。

**Comment by irwinsun** [comment]
需要增加：
1、防止被爆破，构建机导入数量上限限制，可用ImportServerNodeUtils
2、批量下线、删除接口

**Comment by tangruotian** [comment]
方案：用户点开安装第三方构建机选择好系统和区域后，点击批量安装时会生成一个带有有时间限制的token的安装命令，用户在有效期内可以使用该命令随意安装agent，每次安装的都是新的agent。有效期超过则无法安装，需要重新点击安装第三方构建机按钮生成。

**Comment by fayewong-v5** [comment]
统一生成带token的安装命令，不区分是否为批量安装
