### ISSUE TITLE
feat：支持通过接口自定义项目级别用户组

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10025]
包括如下几个功能点：
1、新增用户组
2、修改用户组
3、给用户组增加权限策略
4、修改用户组权限策略
5、从用户组删除权限策略
6、添加用户/组织到用户组
7、从用户组删除用户/组织
8、删除用户组 --- 注意不能删除管理员组

接口设计待补充

**Comment by irwinsun** [comment]
因为创建权限用户组的参数非常复杂，讨论可事先封装好几个预置好的用户组模板，  比如预置用户组模板【CI 管理员】。由调用方传参调用 。
