### ISSUE TITLE
私有构建机支持项目内复用互斥

### ISSUE THREAD

**Issue by hummerstudio** [TencentBlueKing/bk-ci#10082]
**What would you like to be added**: 增加流水线级别的互斥排队，在一条流水线跑完后才能执行另一条流水线。

**Why is this needed**: 目前的互斥组功能为Job级别。在以下场景下会存在问题：
1. 流水线A有多个Job，均在同一构建机上运行
2. 流水线B有多个Job，也均在同一构建机上运行
3. 在流水线A和B的Job上设置互斥组。
4. 假设流水线A在执行时，流水线B也被触发，此时流水线B的Job会互斥排队
5. 流水线A的Job1执行完成后，预期是执行Job2，但实际是会去执行流水线B的Job，由此导致环境混乱或流水线A、B互相抢占构建资源，导致构建时间加长

**Comment by irwinsun** [comment]
如果所有 Job 都是用了同一台构建机，可以尝试用 流水线的并发设置 搭配流水线启动时的参数，可以做到流水线级别的互斥组
<img width="756" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/16686129/ed222197-7141-46a6-8172-d677fb24fa6b">

<img width="575" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/16686129/5e00df2e-f2f3-4078-a3f9-57e5d02d078a">

**Comment by hummerstudio** [comment]
@irwinsun 感谢提供解决思路。不过我这边使用场景实际上是一个流水线会有多个构建机的，并行打包Android、iOS、PC等。也会有多个Job在同一个构建机上，所以上面说的并发设置功能无法满足需要。

**Comment by irwinsun** [comment]
示例流水线：
-----------------------

```TXT
Stage-2                   Stage-3                 Stage-4                                  Stage-5				
   |- Job2-1(构建机A)        |- Job3-1 (公共机)	   |- Job4-1 (复用Job2-1)	     |- Job5-1 (公共机)
   |- Job2-2(构建机A)                               |- MatrixJob4-2(裂变Job全部复用Job2-1）

```
构建# 1、# 2 开始并发或顺序构建场景：

- 1、  假设 # 1 的 Job2-1 优先获得 构建机A，开始锁定构建机A， # 2的Job2-1进入等待

- 2、 # 1 的 Job2-2 也是用到构建机 A， 此时只要构建机A 的并发数设置>= 2, 则可立即满足分配运行。 # 2的Job2-1 继续等待。 
 **注意：这和现有的 Job 级互斥组同时只能有一个在执行有着本质的区别。**

- 3、 当 # 1 Job2-1 Job2-2执行完毕， 流程进入Job3-1，虽然用的不是构建机A， 但构建机A仍然是锁定状态。 # 2的Job2-1 继续等待。

- 4、 Job3-1 执行完毕， 流程进入Job4-1， 直接获得构建机A锁定，开始执行， # 2的Job2-1 继续等待

- 5、Job4-2是 Matrix Job，根据裂变情况分裂出多个 Job，每个 Job 都选中构建机 A，与第 2 步类似，只要此时构建机 A 的并发数没达到并发的上限，就可立即满足分配运行。

- 6、 Job4-1执行完毕， 后续Job5-1已与构建机A无关，可立即释放锁定， 接着# 2的Job2-1 立即获得构建机A进入执行

- 7、 # 1 Job5-1 执行完毕， # 1全部流程执行结束。

**Comment by irwinsun** [comment]
@hummerstudio 不知你是否是腾讯同事，如是为加快交流可以直接联系我，或者直接邮件交流。 github 上会不定时回复。
另外可见上述设计方案是否满足，以上方案结合腾讯游戏业务是可以达到目的

**Comment by irwinsun** [comment]
类似需求 #1122

**Comment by tangruotian** [comment]
> 此方案设计如下：
> 
> ## 示例流水线：
> ```
> Stage-2               Stage-3             Stage-4                              Stage-5				
>    |- Job2-1(构建机A)   |- Job3-1 (公共机)   |- Job4-1 (复用Job2-1)	        |- Job5-1 (公共机)
>    |- Job2-2(构建机A)                       |- MatrixJob4-2(裂变Job全部复用Job2-1）
> ```
> 
> 构建# 1、# 2 开始并发构建：
> 
> * 1、  假设 # 1 的 Job2-1 优先获得 构建机A，开始锁定构建机A， # 2的Job2-1进入等待
> * 2、 # 1 的 Job2-2 也是用到构建机 A， 此时只要构建机A 的并发数设置>= 2, 则可立即满足分配运行。 # 2的Job2-1 继续等待。 **注意：这和现有的 Job 级互斥组同时只能有一个在执行有着本质的区别。**
> * 3、 当 # 1 Job2-1 Job2-2执行完毕， 流程进入Job3-1，虽然用的不是构建机A， 但构建机A仍然是锁定状态。 # 2的Job2-1 继续等待。
> * 4、 Job3-1 执行完毕， 流程进入Job4-1， 直接获得构建机A锁定，开始执行， # 2的Job2-1 继续等待
> * 5、Job4-2是 Matrix Job，根据裂变情况分裂出多个 Job，每个 Job 都选中构建机 A，与第 2 步类似，只要此时构建机 A 的并发数没达到并发的上限，就可立即满足分配运行。
> * 6、 Job4-1执行完毕， 后续Job5-1已与构建机A无关，可立即释放锁定， 接着# 2的Job2-1 立即获得构建机A进入执行
> * 7、 # 1 Job5-1 执行完毕， # 1全部流程执行结束。
> * 8、当有取消，失败等在中途导致流程提前结束的行为，也会释放该锁定，防止锁定被长期持有
> 
> ### 映射到产品的操作入口大概是这样：
> <img alt="企业微信截图_a416350f-c88c-47b1-8441-9b0ed296db6a" width="603" src="https://private-user-images.githubusercontent.com/16686129/316759216-8824bdd9-3ff6-477c-a52d-814eaf4e38db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTU2NTUsIm5iZiI6MTcxMTU5NTM1NSwicGF0aCI6Ii8xNjY4NjEyOS8zMTY3NTkyMTYtODgyNGJkZDktM2ZmNi00NzdjLWE1MmQtODE0ZWFmNGUzOGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAzMDkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhODZjNDM2NzVjMzYzYzAxNzcxNDc0YTdmOWNjMWRlMWEwZWYyYzdlZTkwYzk0ZTRjYWI2MWVhOGFmZjM5NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X5-JoE6_1oZ2oVI464wwki_G1CTg6ZCHFFKm7EOZ6mE">



> 本方案设计如下：
> 
> ## 示例：
> ```
> Stage-2               Stage-3             Stage-4                              Stage-5				
>    |- Job2-1(构建机A)   |- Job3-1 (公共机)   |- Job4-1 (复用Job2-1)	        |- Job5-1 (公共机)
>    |- Job2-2(构建机A)                       |- MatrixJob4-2(裂变Job全部复用Job2-1）
> ```
> 
> 构建#1、#2 开始持续构建：
> 
> * 1、假设#1的Job2-1优先获得构建机A，开始锁定构建机A，#2的Job2-1进入等待
> * 2、 # 1 的 Job2-2 也占用构建机 A，此时只需构建机 A 的负载数设置>= 2，则可立即满足分配运行。 # 2 的 Job2-1 继续等待。注意：**这和现有的工作级别互斥组同时只有一个在执行本质上的区别。**
> * 3、 当#1 Job2-1 Job2-2执行完毕，流程进入Job3-1，虽然不是构建机A，但构建机A仍然是锁定状态。#2的Job2-1继续等待。
> * 4、 Job3-1 执行完毕，流程进入Job4-1，直接获得等待构建机A锁定，开始执行， # 2的Job2-1继续等待
> * 5、Job4-2是Matrix Job，根据裂变情况分割出多个Job，每个Job都勾选了构建机A，与第2步类似，只要此时构建机A的并发数没有达到并发的上限，就可立即满足运动分配。
> * 6、 Job4-1执行完毕，后续Job5-1已与构建机A无关，可立即释放锁定，随后#2的Job2-1立即获得构建机A进入执行
> * 7、 # 1 Job5-1执行完毕， # 1全部流程执行结束。
> * 8、当有取消，失败等在中途导致流程提前结束的行为时，染色体释放应锁定，防止被锁定长期持有
> 
> ### 映射到产品的操作入口大概是这样的：
> <img alt="企业微信截图_a416350f-c88c-47b1-8441-9b0ed296db6a" width="603" src="https://private-user-images.githubusercontent.com/16686129/316759216-8824bdd9-3ff6-477c-a52d-814eaf4e38db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTU2NTUsIm5iZiI6MTcxMTU5NTM1NSwicGF0aCI6Ii8xNjY4NjEyOS8zMTY3NTkyMTYtODgyNGJkZDktM2ZmNi00NzdjLWE1MmQtODE0ZWFmNGUzOGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAzMDkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhODZjNDM2NzVjMzYzYzAxNzcxNDc0YTdmOWNjMWRlMWEwZWYyYzdlZTkwYzk0ZTRjYWI2MWVhOGFmZjM5NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X5-JoE6_1oZ2oVI464wwki_G1CTg6ZCHFFKm7EOZ6mE">

被复用的Job需要再复用他的Job之前的Stage或者同一个Stage，如果是同一个stage，在可以确认agent的前提下进行并发执行

**Comment by hummerstudio** [comment]
@irwinsun 这个是需要手动指定才能流水线级别互斥吗，是否有可能不添加配置由平台自行判断？ 先执行的构建先获取节点是更符合直觉/预期的（虽然技术上来说，先排队的应该先获取节点）

**Comment by irwinsun** [comment]
> @irwinsun 这个是需要手动指定才能流水线级别互斥吗，是否有可能不添加配置由平台自行判断？ 先执行的构建先获取节点是更符合直觉/预期的（虽然技术上来说，先排队的应该先获取节点）

@hummerstudio   
【先执行的构建先获取节点】

**这句话是对的，而且平台也是一直是这种策略的。**

【这个是需要手动指定才能流水线级别互斥吗，是否有可能不添加配置由平台自行判断？ 】
通常情况下，构建机是允许并发的，如果要引入这个特性，那必然是要用户自主开启，而且设计上已经做了大量精减，只需要在想复用的 Job 里选择上，那么平台会根据用户选择哪些 job 要被复用，或者准确的说叫【锁定】来决定开启这个功能，

比如以下选项：
<img width="679" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/16686129/efef3b20-f8c2-4b8e-b4fd-2ca35e561c58">

**Comment by hummerstudio** [comment]
@irwinsun 那这里的配置，是单选，就是设置当前job要复用**前面**哪个job的构建机（颗粒度到IP）对吧？如果前面的job使用的资源是变量，动态指定的，也能兼容吧？
