### ISSUE TITLE
bug：流水线设置依赖的job会卡主

### ISSUE THREAD

**Issue by caomiao0116** [TencentBlueKing/bk-ci#10104]
![image](https://github.com/TencentBlueKing/bk-ci/assets/148753087/4e050c8c-74ad-489c-8c24-25471ae80864)
根据跟踪代码发现，这里是判断流水线状态为 readToRun的，而readToRun是以下的类型
![image](https://github.com/TencentBlueKing/bk-ci/assets/148753087/0e92b013-8182-48d0-992e-d36a4952a7e7)
但实际上流水线是running状态的，导致这里会一直卡主

**Comment by caomiao0116** [comment]
同一个stage中其中一个job依赖上一个job时，上一个job取消构建时，依赖的那个job不会执行

**Comment by irwinsun** [comment]
hello， 这个是产品feature，不是bug。

我说个场景哈： 比如 job_Deploy(部署） 依赖 job_Build(构建出包)， 那么当job_Build(构建出包）被取消时，你希望job_Deploy 要被执行吗？  显然是否定的， 因为此时要部署的包资源都未准备好，进入 job_Deploy(部署）能做什么？ 


> 同一个stage中其中一个job依赖上一个job时，上一个job取消构建时，依赖的那个job不会执行

**Comment by Grapefruit-Shu** [comment]
@irwinsun 那那个卡主的问题是bug吗？
