### ISSUE TITLE
运行锁定支持同一时间最多运行n个构建任务

### ISSUE THREAD

**Issue by eternalsea** [TencentBlueKing/bk-ci#1018]
### 作为
DevOps 的使用者

### 我希望
基于某些资源是有限的，希望 流水线的并发构建 支持设置最大并发数，超过最大并发数。
![image](https://user-images.githubusercontent.com/14304956/78105190-37f98c00-7423-11ea-9fe9-72286196eaaf.png)

**Comment by zanyzhao** [comment]
我们把现在的运行锁定方式改为：

同一时间最多运行`X`个构建任务，超过限制时允许排队，最大排队数量`Y`，最长排队时长`Z`

**Comment by kaholai** [comment]
关注，希望支持。

**Comment by kingzjw** [comment]
强力建议支持 对单条流水线设置 统一时间最多运行n个的构建任务。 应用场景： 多条构建机本身处理多条流水线，然后针对一条流水线的多次触发，希望用私有集群的来并发解决。比如说：我现在有两个构建机，一条流水线，触发三次。此时：第一次用A构建机，第二次用B构建机，这些是OK的。但是第三次触发，就会再使用A构建机，但是A构建机的工作目录已经被第一次触发所使用，会直接失败，然后就导致出现问题了。理论上应该保证第三次处于等待状态

**Comment by zanyzhao** [comment]
> 强力建议支持 对单条流水线设置 统一时间最多运行n个的构建任务。 应用场景： 多条构建机本身处理多条流水线，然后针对一条流水线的多次触发，希望用私有集群的来并发解决。比如说：我现在有两个构建机，一条流水线，触发三次。此时：第一次用A构建机，第二次用B构建机，这些是OK的。但是第三次触发，就会再使用A构建机，但是A构建机的工作目录已经被第一次触发所使用，会直接失败，然后就导致出现问题了。理论上应该保证第三次处于等待状态

可以这样解题：
1. 将多个构建机的最大并发任务设置为1，方法[在此](https://bk.tencent.com/docs/document/6.0/129/7521)
2. 将这几个构建机组成一个构建环境
3. 在流水线的Job里选择“私有构建环境”
4. 等 #3575 上线后，在Job里设置一个合理的超时时间

**Comment by dennisleung** [comment]
构建详情页是怎么进去的？现在节点别名那里是灰的

**Comment by irwinsun** [comment]
通过定义流水线变量，在不同的启动构建赋予不同的值，可以达到不同分组并行，实现并行n个构建任务

<img width="810" alt="image" src="https://user-images.githubusercontent.com/16686129/231627765-28d8f221-5c19-4462-b43e-eaedf1e77c13.png">
