### ISSUE TITLE
bug: Git事件触发变更文件列表为空也应该触发

### ISSUE THREAD

**Issue by mingshewhe** [TencentBlueKing/bk-ci#10229]
创建分支，工蜂的变更文件列表为空，如果"TGIT事件触发"插件配置排除路径不为空，监听路径为空，那么流水线不会触发，希望流水线能够触发
![image](https://github.com/TencentBlueKing/bk-ci/assets/22971705/dafdb1da-0c5f-4550-8fdd-7ea4d31a0e4c)

**Comment by hejieehe** [comment]
#10288
