### ISSUE TITLE
feat：构建环境中的节点，支持停用/启用

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10258]
背景：
当某个节点环境有问题或出现异常时，希望先将此节点暂时停用，待问题解决后再启用。不希望直接停用节点，因为修复问题过程中，需要进行测试验证问题。

需求：
1、停用/启用入口加在下图所示位置：
<img width="800" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/136c38fc-ee75-48c8-a5a0-a4cf07b5e9ab">
- 当停用后，对应的行灰掉
- 停用的节点排在前边
- 仅构建环境下的节点支持停用/启用
- 环境管理员可以进行此操作（需要增加权限action）

2、停用后，使用此环境的流水线 Job 任务不会被分配到此节点上

**Comment by fabio-he** [comment]
环境的节点停用后,使用该环境执行JOB一直循环"agent等待释放"
![image](https://github.com/TencentBlueKing/bk-ci/assets/56472792/a0234e32-8fbc-42e1-be81-019ab68044d1)

**Comment by fabio-he** [comment]
环境使用者 也能进行停用启用操作, 不符合预期
