### ISSUE TITLE
feat：拉取构件支持流水线调试模式

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10291]
<img width="400" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/64461d0b-f1a3-4d6c-9dc0-1945eb937d6a">

比如如图所示的配置：
- 当流水线处于调试模式时，运行时应该拉取调试运行记录中最新的构建归档的制品
- 当流水线处于正常运行模式时，运行时应该拉取正式运行记录中最新的构建归档的制品

不仅仅是此插件，使用相同的 sdk 方法时，也遵循同样的原则，即调试模式和正式运行模式分开

**Comment by yaoxuwan** [comment]
/process/api/build/builds/${projectId}/${pipelineId}/${buildNum}/history
当流水线存在历史构建时，buildNum为调试的构建号会获取到正式的流水线历史
