### ISSUE TITLE
【蓝盾】感觉蓝盾要是和蓝鲸Job，运维等集成起来，就真的成神了

### ISSUE THREAD

**Issue by pengkang1991** [TencentBlueKing/bk-ci#10343]
现在用蓝盾还是有些不方便，比如没法直接用作业平台实现远程执行命令，远程发包，也没法调标准运维的各种流程。请问一下，标准运维有插件可以用吗。

**Comment by irwinsun** [comment]
https://github.com/orgs/TencentBlueKing/repositories?type=public&q=ci-
ci-开头的都是蓝盾的流水线插件，你希望的作业平台（脚本执行、作业执行、文件分发都有）

**Comment by pengkang1991** [comment]
我希望能直接调标准运维里面配置好的流程步骤




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TencentBlueKing/bk-ci"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月21日(星期二) 中午11:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TencentBlueKing/bk-ci] 【蓝盾】感觉蓝盾要是和蓝鲸Job，运维等集成起来，就真的成神了 (Issue #10343)





 
https://github.com/orgs/TencentBlueKing/repositories?type=public&amp;q=ci-
 ci-开头的都是蓝盾的流水线插件，你希望的作业平台（脚本执行、作业执行、文件分发都有）

**Comment by irwinsun** [comment]
标准运维也有相应的流水线插件，在腾讯内部由标准运维平台提供，但目前应该他们没有开源出来，
可以移步标准运维开源库提需求 https://github.com/TencentBlueKing/bk-sops
