### ISSUE TITLE
feat：通过命令字 ::set-variable  设置常量和运行时只读的变量时，应该报错

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10413]
目前步骤没有失败，且输出了参数，会让人误解为设置成功了:
<img width="250" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/ceae2ead-758e-40f4-9602-302d2a7320a5">

需求：
当通过::set-variable 设置常量和运行时只读的变量时，应该报错，对应的设置步骤结果为失败

Variable xxx is read-only and cannot be modified.
Constant xxx cannot be modified.

**Comment by yongyiduan** [comment]
已完成
