### ISSUE TITLE
feat：流水线变量支持手动拖拽调整顺序

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10458]
<img width="800" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/e7a7a659-c788-426e-a9c6-ad140883afb0">

1. 流水线变量支持手动拖拽调整顺序
2. 可以一键“移到最前”
3. 删除变量增加二次确认，避免误触

**Comment by fabio-he** [comment]
查看页不应该支持拖拽
![image](https://github.com/TencentBlueKing/bk-ci/assets/56472792/7b2d0d79-3610-41f0-b598-aeac98c2a104)

**Comment by fabio-he** [comment]
查看页不应该支持拖拽
![image](https://github.com/TencentBlueKing/bk-ci/assets/56472792/60e6b5b0-d889-4de7-adbf-83c625d4b225)
