### ISSUE TITLE
feat: 插件管理菜单对应插件列表增加默认公共插件显示

### ISSUE THREAD

**Issue by carlyin0801** [TencentBlueKing/bk-ci#10472]
**问题：**  用户需要知道项目下哪些插件被哪些流水线用到了以便修改，但目前只会显示已安装的普通插件。
![企业微信截图_17174705345077](https://github.com/TencentBlueKing/bk-ci/assets/5268164/57726df3-d3e5-436b-b5d8-6b2ba55eadee)

**措施：**  插件管理菜单对应插件列表增加默认公共插件显示。

**Comment by fayewong-v5** [comment]
注意默认的公共插件，不能卸载
