### ISSUE TITLE
feature：添加批量删除流水线功能

### ISSUE THREAD

**Issue by iccengan** [TencentBlueKing/bk-ci#1054]
需求背景：目前缺少管理流水线的功能，当需要批量删除流水线时，需要一个个流水线操作。

解决方案：添加批量删除流水线功能

**Comment by woc2006** [comment]
非常需要这个功能

**Comment by iccengan** [comment]
> 非常需要这个功能

@woc2006 能具体描述下是什么场景下会批量删除多条流水线吗

**Comment by woc2006** [comment]
@iccengan 项目组里人多，每个需求都创建流水线，时间长了过期流水线很多，导致找有用流水线效率低，有些流水线有定时触发特定，也导致计算资源浪费。
现在没有批量删除，人工删效率极低。

**Comment by buendia27** [comment]
流水线提供自动生成功能，有些长期不使用的git因为某些工具自动修改，导致生成了很多无用流水线，而且这些流水线中有很多是定时触发的，造成了很多无用告警；

本身一个网站，批量删除也应该作为一个基本功能，这个使用非常不友好

**Comment by Abbyyan** [comment]
需求+1。应该是一个网站的基本功能，而不是只有对应的接口。

**Comment by iccengan** [comment]
设计图待补充，挪至v1.8

**Comment by irwinsun** [comment]
已实现
