### ISSUE TITLE
feat：流水线变量语法支持两种风格

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10576]
【背景】
蓝盾早期的变量使用比较自由，但在一些场景下业务希望有严格的检查控制。
考虑到存量流水线太多，开启严格检查需要修改的内容太多，一刀切不适合，增加配置由业务选择。

【需求】
1. 支持项目级别的“语法风格”配置，可选值有 宽松/制约
    - 蓝盾和stream存量项目默认都为 “宽松”
    - 新建项目时，新建页面默认选中“传统”，业务可根据需要切换
    - 编辑项目时，支持修改此项配置，修改时提示影响范围，以便用户修改流水线满足新风格后再切换
        <img width="400" alt="image" src="https://github.com/user-attachments/assets/b916e082-5d31-4175-bef3-d64501ead392">
        <img width="300" alt="image" src="https://github.com/user-attachments/assets/51fea9b3-0a34-48ec-937f-4143657c3635">

2. 支持流水线级别的 “语法风格”配置，默认继承项目配置，可修改为和项目配置不同的方式，修改后在当前流水线生效
    - 新增流水线时，提供入口让用户配置
        <img width="150" alt="image" src="https://github.com/user-attachments/assets/b203d818-eebd-488e-9664-2955762eeb06">
        - 默认勾选“继承项目设置”，并展示出项目配置供用户参考
        - 用户可以去掉勾选，设置为当前流水线指定的风格
    - 编辑流水线时，可以修改配置
        <img width="200" alt="image" src="https://github.com/user-attachments/assets/732df832-15ee-4257-9bcb-3e0393ffa096">
   
        
3. 两种风格的区别:
    - 制约模式仅支持通过双花括号引用流水线过程变量，避免出现 bash 脚本变量在执行前被系统赋值的问题
    - 表达式函数 如contains、join、fromJSON等，传统模式仅支持在流程控制选项 自定义表达式满足时运行 设置中可以使用；制约模式流程控制选项、插件入参、Job设置等流水线配置中均可使用函数
    - 制约模式下，流水线变量值超长时，将报错，运行失败（传统风格仅警告，未报错）
    - 制约模式下，流水线变量 ID 规范化，不支持中文 ID，减少不同构建环境下的兼容问题
   
<img width="500" alt="image" src="https://github.com/user-attachments/assets/615f5cc5-bf4f-44ad-bd3d-69b9ec964f96">

4. code 模式下关键字配置为：
    ```
    syntax-dialect: CONSTRAINT/CLASSIC/INHERIT
    ```
- CONSTRAINT： 制约模式
- CLASSIC：宽松模式
- INHERIT：继承项目配置

**Comment by fayewong-v5** [comment]
https://github.com/TencentBlueKing/bk-ci/issues/10665 其中第三点，在制约模式下报错

**Comment by mingshewhe** [comment]
在实现过程中，发现以下问题导致有些功能无法实现
1. 表达式格式
    - 原有设计，是不管传统模式还是制约模式，都可以使用表达式，先执行表达式替换，如果支持${}替换，再执行替换逻辑。但是在实现的时候发现，表达式如果变量不存在，表达式会直接输出空字符串，而不是原有的值，这样子导致，原来bash脚本会直接报错的，现在输出空字符串不会报错了，导致可能产生不可预知的错误
2. 环境变量：插件输出不导入到环境变量中
    - 有些插件没有通过入参传入参数，而是插件内部直接读取环境变量，如果去掉后，插件就无法使用了
3. 引用方式: 只能通过上下文的方式引用变量
     - 如果环境变量没有去除，用户还是可以通过${}方式引用变量，会产生歧义
4. 重置内置只读变量: 只读变量不能修改
     - 目前只读变量都无法修改，不需要通过开关控制
5. 变量值超长
6. 变量不存在
    - 只有表达式才能判断变量是否存在，变量替换无法判断，因为${}无法判断是变量还是引用环境变量
7. 变量ID不规范
