### ISSUE TITLE
feat：依赖的服务未部署时的交互优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10612]
1. 流水线如果需要支持 GitHub 代码库，需在部署时，注册好 GitHub APP 并添加相应的配置，否则功能不正常。
此时，希望代码库服务下关联 GitHub 代码库入口虽然展示出来，但处于禁用态。点击弹框提示。
提示文案：GitHub 连接服务尚未部署完成
                  如需使用此功能，请联系平台管理员注册 GitHub APP，并更新配置文件 bkenv.properties。
指引链接：待补充

2. 编译加速服务，需要部署好后台服务才能使用，否则有前端saas页面注册方案ID也没什么用。
此时，希望服务列表里，有编译加速服务（让更多用户知道我们有这个能力），但禁用不可选。点击打开页面：
提示文案：编译加速服务尚未部署完成
                  Turbo 编译加速服务基于分布式编译、缓存、容器技术，旨在为业务提供高效、稳定、便捷的加速服务，提升研发效率。
                 如需使用此功能，需要部署加速服务。
指引链接：待补充

前端组件：https://bkui-vue.woa.com/bk/functional-deps

**Comment by irwinsun** [comment]
- [ ]  提供代码库列表接口，返回目前支持的代码库类型列表，前端根据此数据来渲染下拉菜单以及根据启动状态来决定弹相应的操作框
- [ ]  前端根据服务列表接口返回的服务status字段来决定展示， status=developing时，前端展示出来，并支持点击展示提示信息。
