### ISSUE TITLE
丰富流水线-stage准入的审核功能，支持配置角色或用户组作为审核人

### ISSUE THREAD

**Issue by Ruinano** [TencentBlueKing/bk-ci#10689]
【背景】
stage 准入只能配置具体人员进行准入审核，如出现用户注销等情况后，管理配置成本比较高。

【需求】
丰富流水线-stage准入的审核功能，支持配置角色或用户组作为审核人，且支持审核结果的变量输出。

**Comment by fayewong-v5** [comment]
1. 审核人配置，支持关联项目级用户组
2. 增加上下文输出 stage 审核信息：
    -  stages.<stage_id>.check-in.flow1.operator
    - stages.<stage_id>.check-in.flow1.result

**Comment by yongyiduan** [comment]
stages.<stage_id>.check-in.flow<idx>.operator 是输出输出用户原始填写内容，还是变量替换后/用户组替换后的内容。

**Comment by fayewong-v5** [comment]
> stages.<stage_id>.check-in.flow.operator 是输出用户原始填写内容，还是变量替换后/用户组替换后的内容。 以及什么时机写入该上下文，我会默认为该flow触发执行时写入上下文。

真正操作的人，谁点了审核通过/拒绝，就是谁
