### ISSUE TITLE
feat：Git分支/Tag和Svn分支/Tag类型的变量优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10774]
1. 支持在执行和模版实例化时，可以修改代码库，根据代码库联动出分支供用户选择
2. 在执行时，对于这些类型的变量，支持两个上下文，便于用户在流水线配置中引用：
    - variables.<变量名>.repo-name：取值规则和关联代码库到蓝盾时的别名默认值一致
    - variables.<变量名>.branch

UI 交互如下：
1. 新增/编辑变量界面：
<img width="300" alt="image" src="https://github.com/user-attachments/assets/30df3cb1-31e4-4b5f-ab99-a4973ace20df">

2. 查看和复制变量：
<img width="300" alt="image" src="https://github.com/user-attachments/assets/613777f9-8246-41c3-ba5a-d900a8107635">

3. 执行预览和模版实例化
<img width="600" alt="image" src="https://github.com/user-attachments/assets/a80d0232-5cec-4905-bcdc-72c9e3a05da0">

**Comment by mingshewhe** [comment]
## 设计思路
为了方便后续能够扩展成用户自定义级联，前后端交互格式需要灵活。级联的变量，通过json传递参数， 如代码库分支，那么值应该是
```
{"repo-name": "TencentBlueKing/bk-ci", "branch":"master"}
```
不过因为代码库分支是定制化变量，所以还是增加REPO_REF的类型，但是格式用级联的格式

### 保存时
保存时，前端传入的值
```
{"id":"aaa", "type":"REPO_REF", "defaultValue": {"repo-name": "TencentBlueKing/bk-ci", "branch":"master"}}
```
### 预览时
预览接口: process/api/user/builds/{projectId}/{pipelineId}/manualStartupInfo
后端返回前端：
```
{
    "id": "aaa",
    "type": "REPO_REF",
    "defaultValue": {
        "repo-name": "TencentBlueKing/bk-ci",
        "branch": "master"
    },
    "cascaderOptions": [
        {
            "id": "repo-name",
            "value": "TencentBlueKing/bk-ci",
            "searchUrl": "process/api/user/buildParam/repository/mht/aliasName?aliasName={word}&permission=LIST&repositoryType=CODE_GIT,GITHUB,CODE_SVN,CODE_TGIT,CODE_GITLAB",
            "replaceKey": "{word}",
            "children": [
                {
                    "id": "branch",
                    "value": "master",
                    "searchUrl": "process/api/user/buildParam/{projectId}/repository/refs?search={word}&repositoryType=NAME&repositoryId={parentId}",
                    "replaceKey": "{word}"
                }
            ]
        }
    ]
}
```
当用户点击时，前端根据searchUrl进行搜索，点击第二级时，需要将searchUrl中的{parentId}替换成上一级的值

### 运行时
运行时，前端给后端传入
```
"aaa":"{\"repo-name\":\"TencentBlueKing/bk-ci\",\"branch\":\"master\"}"
```
后端在com.tencent.devops.process.engine.compatibility.v2.V2BuildParametersCompatibilityTransformer#parseTriggerParam 判断变量类型是否是REPO_REF，如果是，则增加variabls.aaa.repo-name, variables.aaa.branch变量
