### ISSUE TITLE
feat：stream stage 审核的通知方式支持企业微信群

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10796]
<img width="800" alt="image" src="https://github.com/user-attachments/assets/87023850-9ea4-4705-b426-5366d57b28f2">

1. 支持发通知到群
2. 群里支持 @审核人

**Comment by yongyiduan** [comment]
发现@审核人是属于富文本支持的范围，会和以Markdown格式发送互斥
