### ISSUE TITLE
增加构建详情的查看配置项，在构建详情界面点击插件时，默认进入的是 日志 or 配置 Tab页面。

### ISSUE THREAD

**Issue by irwinsun** [TencentBlueKing/bk-ci#10808]
对于金融Ops场景, 插件作为审批流的入口，经常点击插件是希望直接展示表单页面，进行表单内容输入或点击等交互操作，因此对日志并不关注，可在Model中增加一个配置项，**通过api创建流水线时传入，不在页面增加额外的选项入口**
前端根据这个配置项来决定要展示日志，还是表单。

**Comment by fayewong-v5** [comment]
1. 支持项目级别的配置项，不细化到流水线
2. 配置项：
    - 名称为 “日志/制品/配置显示顺序”
    - 默认值为“LOG,ARTIFACT,CONFIG”，可以修改为 “CONFIG,LOG,ARTIFACT” 等业务需要的展示形式
    - 1期 UI 先不支持，openapi 可设置
