### ISSUE TITLE
增加自有机器集群负载视图

### ISSUE THREAD

**Issue by erwei5168** [TencentBlueKing/bk-ci#1094]
### 我希望
平台提供项目自有机器接入后并进行环境标签划分，能够查看具体标签的集成负载情况，类似jenkin机器标签组负载视图

### 以便于
- 能够分析团队资源消耗时间分布
- 能够预估项目资源扩展预期
- 项目资源是否充分使用

### 期望的验收标准
- 能够展示某一机器环境标签下 近一天，近一周，近一个月的负载情况，可用进程，排队进程，实际使用进程数曲线
类似：
![image](https://user-images.githubusercontent.com/39473058/79296333-b9feb000-7f0d-11ea-8d6f-b18a507d4d31.png)
- 其他非必须功能建议平台考虑：超过一定阀值失败排行节点，其他告机器告警类……

**Comment by iccengan** [comment]
https://github.com/Tencent/bk-ci/projects/7
这个需求会以extension（扩展）的方式来实现，敬请期待！

**Comment by irwinsun** [comment]
已通过将数据上报至蓝鲸监控实现
