### ISSUE TITLE
feat：Job 互斥组排队时，队列长度支持最长到 50 

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10975]
Job 互斥组排队时，队列长度上限调整到 50 
<img width="400" alt="image" src="https://github.com/user-attachments/assets/751d8d3c-ccf6-4592-a223-ec6f705aca38">

**Comment by irwinsun** [comment]
加个需求，互斥组名如果是变量，在重试时，希望能够支持加载到新的变化

<img width="1435" alt="image" src="https://github.com/user-attachments/assets/812bc9bf-302c-44ab-8c20-558e1b57e261">
