### ISSUE TITLE
feat：项目设置支持管理员配置项目下流水线的命名规范

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#11057]
1. 新增/编辑项目增加「命名规范提示」开关
<img width="800" alt="image" src="https://github.com/user-attachments/assets/586a173e-4f4e-4a89-a1d1-9559c95e3e78">
- 开关打开后，填写命名规范要求

2. 开启了「命名规范提示」的项目，新建流水线页面，展示流水线命名规范
<img width="800" alt="image" src="https://github.com/user-attachments/assets/be9bc300-0532-44e4-85f0-41057c38459c">

**Comment by mingshewhe** [comment]
模板实例化也需要提示
