### ISSUE TITLE
支持复用指定Job的环境

### ISSUE THREAD

**Issue by Sherlozk** [TencentBlueKing/bk-ci#1122]
当选择集群运行流水线的时候，我希望同一个任务的 stage 可以在同一个环境下面运行，不会发生 stage 1在 A 机器拉了代码，然后经过 stage 2 一系列的代码操作，在 stage 3中进行编译的时候却在 B 机器上面运行的问题

为此我希望可以有让 stage 继承上一个 stage 环境的属性，保证流程的同时，可以减少每个 stage 初始化环境的耗时。当然我也不希望这是一个强制固化的机制，而是一个可选项。

**Comment by zanyzhao** [comment]
如果stage1被跳过，stage3里要找哪些机器？

**Comment by sherlockZ** [comment]
> 如果stage1被跳过，stage3里要找哪些机器？

现在有跳过 stage 的功能吗？假设 stage1 被以外跳过，那 stage2 就无法继承 stage1 的环境，因为 stage1 并没有真正运行，所以没有选择机器，这时候 stage2 设置了继承 stage1 的环境，就应该报错「未指定执行环境 or 无法继承环境」，任务就此终止，不会到 stage3

**Comment by Ben-zl** [comment]
> > 如果stage1被跳过，stage3里要找哪些机器？
> 
> 现在有跳过 stage 的功能吗？假设 stage1 被以外跳过，那 stage2 就无法继承 stage1 的环境，因为 stage1 并没有真正运行，所以没有选择机器，这时候 stage2 设置了继承 stage1 的环境，就应该报错「未指定执行环境 or 无法继承环境」，任务就此终止，不会到 stage3

在集群上运行遇到过同样的问题，感觉可以优先选择上个stage所运行的机器和让其它任务暂时选择不了这台机器，通过在stage设置开关选项

**Comment by zanyzhao** [comment]
可以换个思路实现：
- 当stage1运行完，就新增一个stage1所在构建机别名的变量
- 配置流水线时在stage2/3中以指定构建机（注意不是指定集群）的方式输入这个变量

这样在也可以达到同样目的

**Comment by sherlockZ** [comment]
> 可以换个思路实现：
> 
> * 当stage1运行完，就新增一个stage1所在构建机别名的变量
> * 配置流水线时在stage2/3中以指定构建机（注意不是指定集群）的方式输入这个变量
> 
> 这样也可以达到同样目的

看起来应该可以满足需求

**Comment by zanyzhao** [comment]
ok @fitzcao 关注下：
我们加上这个变量`BK_CI_JOB_N_ALIASNAME`即可：
N为Job在流水线中的编排号，比如2_1、3_1

**Comment by irwinsun** [comment]
修改了标题，需要声明下，stage与job的的区别
stage是一堆 job的管理集合，多个job是并行的。 stage不具体管理环境。
job才是具体环境的拥有者，具体到某一台构建机器。

![image](https://user-images.githubusercontent.com/16686129/85944748-ddad9000-b96b-11ea-8c83-cc2677bf4bdb.png)

**Comment by LittleMali** [comment]
希望支持流水线级别的集群调度。
stage1下job1--git拉代码，stage2下job2--编译公共代码，stage3下有两个并行jpb，job3--编译中心1的代码，job4--编译中心2的代码。
如果是按照job级别的调度，那么，job1分配到机器A，job2分配到机器B，job2显然无法执行，毕竟git拉代码都没执行。

devHelper提出过解决思路，git拉代码可以利用蓝盾插件“归档到云端”，在编译代码的时候再利用蓝盾插件“从云端拉到本地”，那么，假设，git代码被正确拉到了不同的机器，job2分配到了机器A，编译好了公共代码，但是stage3下的两个并行job：job3分配到机器A，job4分配到机器B，显然，job4因为缺乏公共代码的输出而导致编译失败。

因此，基于job级别的调度，难以解决job前后依赖的问题——job前后显式或者隐式的依赖是十分正常的，先做什么再做什么，这种依赖关系必须调度到一个机器上。因此，若能有流水线级别的集群调度，就不必处理依赖问题。问题被简化为，第一次触发流水线，调度到机器A，机器A完成所有操作，第二次触发流水线，调度到机器B，机器B完成所有操作。希望有类似的功能。

**Comment by jeffchi975** [comment]
final stage可以通过配置job id，来复用指定job使用同一台资源，final stage和这个job可能还有时间差，不是无缝衔接的，同时要在这段时间机器锁定机器，不被其他任务调度到

**Comment by irwinsun** [comment]
相同需求 #10082
