### ISSUE TITLE
流水线支持设置图标

### ISSUE THREAD

**Issue by linjiex** [TencentBlueKing/bk-ci#1145]
### 作为
DevOps 团队里的Dev

### 我希望
流水线支持设置Icon，从而在流水线列表中能容易区分特定的流水线。 
Icon可以从默认集合中选择， 或者支持用户上传。

就像插件商店中的插件必须有一个图标一样。

### 期望的验收标准

* 流水线配置中增加选择 Icon， 或者支持用户上传Icon

**Comment by zanyzhao** [comment]
后续会增加一个“流水线组”的功能 #735 ，组里可以考虑加个ICON之类的

**Comment by irwinsun** [comment]
#流水线组功能已经实现
