### ISSUE TITLE
流水线支持置顶

### ISSUE THREAD

**Issue by linjiex** [TencentBlueKing/bk-ci#1146]
### 作为
DevOps 团队里的Dev，要管理团队中的流水线

### 我希望
流水线界面中支持 特定流水线 置顶。

置顶数量建议可以配置，比如1条，3条。
置顶流水线和其它流水线有明显的分隔。

默认是“全部流水线”中置顶

### 以便于

让使用者快速定位流水线。

### 期望的验收标准
* 流水线视图中有 置顶的选项

**Comment by iccengan** [comment]
关联需求：#1075

**Comment by irwinsun** [comment]
通过自建流水线组解决
