### ISSUE TITLE
feature: 人工审核插件可设置所有审批人都同意才继续执行

### ISSUE THREAD

**Issue by hellopao** [TencentBlueKing/bk-ci#1175]
### 我希望
人工审核插件可设置所有审批人都同意才继续执行

### 以便于
- 版本验证时，每个开发人员的版本都验证ok才走后续发布流程

**Comment by iccengan** [comment]
审批人是否需要顺序同意？

**Comment by hellopao** [comment]
@iccengan 不需要

**Comment by iccengan** [comment]
@hellopao 好的，我们评估下，给插件添加一个开关：是否需要所有审批人通过

**Comment by Yuliang-Lee** [comment]
这个能提上日程吗

**Comment by fayewong-v5** [comment]
stage 准入已支持添加多个审批步骤：

**Comment by irwinsun** [comment]
已通过审核流多步骤的方式解决
