### ISSUE TITLE
希望 正在执行中 stage 和 步骤 可以显示当前已执行时间

### ISSUE THREAD

**Issue by eternalsea** [TencentBlueKing/bk-ci#1189]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望

希望 正在执行中 stage 和 步骤 可以显示当前已执行时间，目前只有一个圈圈提示正在执行，不好评估已经执行了多久，无法根据历史经验预估还需要多久。

![image](https://user-images.githubusercontent.com/14304956/80086208-f7a5ad80-858b-11ea-8b00-3c4b24b4fbd2.png)

**Comment by lockiechen** [comment]
@ChicagoWen , 这个需要前端加一个计时器计算时间，跟进一下哈

**Comment by fayewong-v5** [comment]
我们先在 TASK 上加。

**Comment by irwinsun** [comment]
已实现
