### ISSUE TITLE
EnvInject

### ISSUE THREAD

**Issue by ByeDream** [TencentBlueKing/bk-ci#1249]
hi,  蓝盾是否可以添加Jerkins上的EnvInject一类的插件，将构档机的环境变量导入到shell/batch file执行环境, 我理解最好是能做到编译环境闭包，但有时一些复杂工程会有外部依赖，排查环境变量缺失比较麻烦。  感谢！

**Comment by irwinsun** [comment]
我理解这个功能有2个：
1、构建机agent在启动worker构建任务进程时，会采用 sh -l xxxx.sh 的方式，将当前shell的环境变量都导入到所有后续构建子进程中。 这个已经能满足所有要求。

2、 构建机详情页面具有脱离于构建机本地的环境变量，支持随意编排设定，灵活性更高
<img width="645" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/16686129/0f2e5b4c-9d1a-48b8-87e1-1719de5fcced">
