### ISSUE TITLE
推送至其它项目自定义仓库-可否去掉share父目录，增加一种节点用于自定义仓库拷贝文件

### ISSUE THREAD

**Issue by waterdorm** [TencentBlueKing/bk-ci#1254]
### 作为
项目文件发布的需求

### 我希望
在现有**推送至其它项目自定义仓库** 节点基础上去掉默认父路径，生成新的节点 **自定义仓库-拷贝文件**
目前缺少自定义仓库拷贝文件的节点功能。
### 以便于
- 在自定义仓库间自由移动文件

### 期望的验收标准
- 希望移动文件功能正常。

**Comment by fayewong-v5** [comment]
1、保留share目录，是避免多人操作时，项目下的文件被其他项目下的同名文件覆盖，导致异常问题出现，增加排查难度。

2、自定义仓库下的文件移动，现在已经有插件支持的，可以在研发商店搜索：自定义仓库-移动文件

3、自定义仓库下拷贝文件，是想如何拷贝呢？ 指定目标文件夹路径，将文件复制到目标文件夹下？

**Comment by waterdorm** [comment]
> 1、保留share目录，是避免多人操作时，项目下的文件被其他项目下的同名文件覆盖，导致异常问题出现，增加排查难度。
> 
> 2、自定义仓库下的文件移动，现在已经有插件支持的，可以在研发商店搜索：自定义仓库-移动文件
> 
> 3、自定义仓库下拷贝文件，是想如何拷贝呢？ 指定目标文件夹路径，将文件复制到目标文件夹下？

自定义仓库-移动文件 这个功能就不可用。

**Comment by waterdorm** [comment]
就是把 推送至其它项目自定义仓库 重新命个名，然后用于自定义仓库，目录拷贝，行为和现在一样，只是去掉share/项目名的结构，现在自定义仓库-移动文件的节点逻辑都不对，也没人维护，找对应的开发也不做任何修改。

**Comment by irwinsun** [comment]
推送至其它项目自定义仓库-new 插件类需求已由相应插件实现
