### ISSUE TITLE
能提供Dockerfile吗？

### ISSUE THREAD

**Issue by chimisu** [TencentBlueKing/bk-ci#1373]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
能够自己编译最新的Docker镜像

### 以便于
- 快速体验新的功能

### 期望的验收标准
- 根据Dockerfile构建镜像

**Comment by iccengan** [comment]
提供什么镜像的Dockerfile？

**Comment by irwinsun** [comment]
开源版的镜像可以查看这里
https://github.com/ci-plugins/base-images

**Comment by chimisu** [comment]
@irwinsun 我想要这个https://hub.docker.com/r/blueking/bk-ci镜像的Dockerfile，这样我就可以根据最新代码来自己构建镜像来体验最新的功能，谢谢哈。

**Comment by chimisu** [comment]
Any update?

**Comment by vuuv** [comment]
@chimisu  不好意思, 没有及时处理.
该镜像是基于演示用途临时制作的, 短期内不会更新. 

`Dockerfile` 本身没有多少内容, 基于本地制作好的基础服务二进制包和一些shell脚本. 因为二进制包分发不便, 故而没有提供 `Dockerfile`.

你可以先尝试下我们发布的二进制包? https://github.com/Tencent/bk-ci/releases

至于正式的企业版Docker化部署方案, 预期在下半年开始尝试. 如果你有Docker化部署的建议, 也可直接在此留言.

**Comment by irwinsun** [comment]
> Any update?
@chimisu 
可以看下 https://github/com/zanyzhao/bkci-server

**Comment by wenhao** [comment]
同求，部署太麻烦了。

**Comment by irwinsun** [comment]
关于容器化的方案可以看文档 https://github.com/TencentBlueKing/bk-ci/tree/master/docs/install
