### ISSUE TITLE
新增微信开发者代码管理git.weixin.qq.com的事件监听

### ISSUE THREAD

**Issue by zombieyang** [TencentBlueKing/bk-ci#1411]
与 #1180 类似。两者都是基于工蜂的git仓库，建议统一排期一起实现

**Comment by irwinsun** [comment]
目前是可以追加的，因为微信开发者代码管理底层也是用的腾讯工蜂TGit， 所以在蓝盾中直接使用 TGit类型添加，可以正常使用。

<img width="1204" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/16686129/98d77283-16ea-4a00-b298-bbfb92984502">



但最最最重要的webhook，可能因为【微信开发者代码管理】所使用的腾讯工蜂TGit版本原因不支持，或者是 【微信开发者代码管理】 平台自主将webhook 的功能做了屏蔽，所以导致无法正常发送webhook， 因此蓝盾平台在能力方面不存在问题，已经可以满足功能

<img width="1117" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/16686129/325e475c-247b-4d29-a971-33a4a25dcb2c">
