### ISSUE TITLE
在插件开发SDK(python_atom_sdk)中获取到插件的自定义名称

### ISSUE THREAD

**Issue by CCCindy** [TencentBlueKing/bk-ci#1416]
### 作为
DevOps 插件开发者

### 我希望
能在插件开发SDK(python_atom_sdk)中获取到插件的自定义名称

### 以便于
- 在插件开发时能获取到该自定义名称

### 期望的验收标准
- SDK方法中添加获取自定义名称的方法

**Comment by fayewong-v5** [comment]
支持 BK_CI_TASK_ALIAS 变量，当前task的别名

**Comment by fayewong-v5** [comment]
功能已实现：BK_CI_TASK_NAME
