### ISSUE TITLE
分支提交和MR显示优化

### ISSUE THREAD

**Issue by squirrel20** [TencentBlueKing/bk-ci#1519]
![image](https://user-images.githubusercontent.com/3339751/82184602-7f2bd580-991a-11ea-88c3-2f0684de84b1.png)

一条流水线的触发时间同时支持：

- push事件触发
- MergeRequest触发

此时，希望在构建列表这里可以区分出来上诉两个事件。

**Comment by zanyzhao** [comment]
跟我想到一块儿了，刚准备提issue就发现有类似的了。link issue #1130
