### ISSUE TITLE
根据构建ID获取流水线编译构建产出物

### ISSUE THREAD

**Issue by pekwjw** [TencentBlueKing/bk-ci#1521]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
根据构建ID获取流水线编译构建产出物

### 以便于
使用devops提供的跨流水线获取构建的插件（插件名：拉取构建-流水线仓库(new)）

### 期望的验收标准
- 创建一条流水线A，生成构建产出；
- 创建另外一条流水线B，可以通过构件号，获取对应的流水线A的构建产出；

**Comment by iccengan** [comment]
![image](https://user-images.githubusercontent.com/10875468/87644508-ce597f80-c77e-11ea-9b89-65786858b528.png)
看下最新的【拉取构件-流水线仓库(new)】插件是否能满足你的需求
