### ISSUE TITLE
希望将蓝盾流水线的启动权限和中止权限分开

### ISSUE THREAD

**Issue by reiwang** [TencentBlueKing/bk-ci#1548]
## Note  
策划和美术同学常常都有流水线的启动权限, 但是他们往往会中止流水线的执行, 然而构建流水的中止并不意味着蓝盾或者构建脚本能够清理掉所有的中间临时状态. 所以, 我们不希望非专业人士有中止权限.

## Required Information
希望将蓝盾流水线的启动权限和中止权限分开

**Comment by zanyzhao** [comment]
如果这样管制的话，会让流水线权限变得更复杂，是不是可以这么解决：
我们在流水线插件的流程控制中增加一个“忽略终止信号”的开关，默认关闭，对于你不想随便终止的插件，你可以主动开启它

**Comment by reiwang** [comment]
> 如果这样管制的话，会让流水线权限变得更复杂，是不是可以这么解决：
> 我们在流水线插件的流程控制中增加一个“忽略终止信号”的开关，默认关闭，对于你不想随便终止的插件，你可以主动开启它

建议是流水线级别的, 不要单个task

**Comment by irwinsun** [comment]
插件类需求已经有相应插件实现
