### ISSUE TITLE
【Feature】【流水线参数】流水线变量添加显示名称

### ISSUE THREAD

**Issue by cmdwin32** [TencentBlueKing/bk-ci#1666]
流水线操作员通常为pm
不希望看到英文的变量名，无法理解
流水线蓝图里不希望存在中文的变量名
所以希望流水线变量的展示名称和代码中的变量名分开设置

**Comment by fayewong-v5** [comment]
流水线蓝图里？ 具体是哪些地方，可以列举下吗
