### ISSUE TITLE
希望质量红线支持自动设置

### ISSUE THREAD

**Issue by mingervic** [TencentBlueKing/bk-ci#1681]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
十分迫切地希望能够支持自动修改质量红线的能力。
目前我设置了代码检查工具的质量红线，插件执行完成后希望能够将 最新扫描出来的 低于质量红线的值 自动设置为质量红线的值， 这样我们就不需要每天手动去修改质量红线了。
常常因为没有及时修改质量红线，导致有同事修复了代码问题， 但是因为没有及时更新质量红线的阈值，让新增的代码问题成了漏网之鱼。

**Comment by carrywang05** [comment]
可在插件代码库根目录下，通过名为quality.json的文件，定义质量红线指标的链接。具体如下：
 **"logPrompt": "xxx"    # 红线日志输出提示。展示在拦截日志后。**
可以使用html的写法，例如：
<a href='xxxx'> xxxxx</a>

**Comment by irwinsun** [comment]
质量红线本是由一堆设定好阈值的指标所组成的，必须很稳定的， 而不是忽高忽低，任意被调整的。
从描述上来看，像是配置上缺失了某一些指标，比如检查工具提供100个检查代码缺陷，目前你只设定了70个， 而剩下的30个没有被设定进质量红线中， 但有其他同事的代码可能违反了那30个，所以你希望能自动将剩下的30个指标也纳入。

这个需求看起来这是业务管理上问题，还是回到开头的地方，“质量红线本是由一堆设定好阈值的指标所组成的，必须很稳定的， 而不是忽高忽低，任意被调整的。”
