### ISSUE TITLE
复选框支持粘贴后自动选择

### ISSUE THREAD

**Issue by levinlinx** [TencentBlueKing/bk-ci#1709]
效果就跟企业微信里批量搜索

可能需要在select-input组件上支持下。

**Comment by levinlinx** [comment]
另外 手动触发有一个“手动触发执行时使用最近一次构建参数值”的功能，但这个仍然无法解决我们的场景。

例如：我们经常要一次性构建不同参数（复选框，要选的非常多）的包，给不同环境（例如A、B、C三个环境）进行测试，但此时发现中间一个包B有问题，但需要重复构建（复选中的参数可能多一少一），此时就没办法用”最近一次“了。

这时如果能句做到：复制原来流水线里的参数，直接粘贴到复制到”复选框上“，并自动选择上，就方便很多，而且不易出错。

**Comment by iccengan** [comment]
涉及到 复选框变量 的组件，需前端评估下 @lockiechen
