### ISSUE TITLE
增加password类型流水线变量

### ISSUE THREAD

**Issue by zanyzhao** [TencentBlueKing/bk-ci#1746]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
在字符串变量中增加`显示明文`的开关

**Comment by irwinsun** [comment]
这种类型是没有意义，敏感数据按数据规范是禁止回传至web前端展示。
web前端永远拿不到真正的值，比如 【凭证管理】中的凭证，前端永远是****。

而如果点一下就能展示明文，说明web前端是存放着明文数据的，用 F12打开devtool 就能看到，何必多此一举，掩耳盗铃。
