### ISSUE TITLE
内置系统变量，可获取前面Stage内的Job相关信息

### ISSUE THREAD

**Issue by zanyzhao** [TencentBlueKing/bk-ci#1748]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
内置系统变量，可获取前面Stage内的Job相关信息，比如：
- Job运行所分配的构建机（供`指定构建机`时使用）
- Job运行状态

```json
stage2-jobs-status = [
   {
      "id" : "2-1",
      "name" : "mod1",
      "status" : "success"
   },
   {
      "id" : "2-2",
      "name" : "mod2",
      "status" : "skipped"
   }
]
```

**Comment by irwinsun** [comment]
使用 **job.<属性名>** 获取当前Job的信息， 如果要特定job，则使用 **jobs.<job_id>.<属性名>**



属性名 | 值类型 | 说明 | 备注
-- | -- | -- | --
job.name | String | job 名称 | 缺省时，按照配置顺序为 job-1、job-2……job-N
job.id | String | 当前 pipeline 下 job 的唯一标识 | 当用户自定义标识时，自行保证唯一性。缺省时，系统内置生成
job.status | String | 当前 job 的状态，可能的取值为：SUCCEEDFAILEDCANCELEDSKIP | 当 continue-on-error=true 且 job 执行失败时，status=SUCCEED，outcome=FAILED
job.outcome | String | 当前 job 的状态，可能的取值为：SUCCEEDFAILEDCANCELEDSKIP | 当 continue-on-error=true 且 job 执行失败时，status=SUCCEED，outcome=FAILED
job.os | String | 当前 job 执行机器的操作系统：LINUXWINDOWSMACOS |  
job.container | Object |   |  
job.container.network | String | 当前 job 所在的网络区域，可能的取值为：IDCDEVNETOA |  
job.container.node_alias | String | 使用第三方构建机集群时生效，当前job调度到的节点别名 |  
job.stage_id | String | job 所属的 stage id |  
job.stage_name | String | job 所属的 stage name |  
job.index | String | 在 matrix job 下，从0开始的索引。和 matrix job 解析出来的顺序有关。 | 可以根据 index 去获取 matrix job 下指定 job 的具体步骤输出
