### ISSUE TITLE
【流水线】失败插件可手动忽略错误

### ISSUE THREAD

**Issue by zanyzhao** [TencentBlueKing/bk-ci#1749]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
![image](https://user-images.githubusercontent.com/1629409/84019834-6d3ad100-a9b4-11ea-92c9-ca7f44dec272.png)

**Comment by albertdengOvO** [comment]
在我们的生产环境发布流水线里也迫切想要这样的功能
有时候发布过程并不顺利，流水线出现错误后往往需要人工介入处理。处理完毕后我们希望能让流水线忽略当前错误并继续执行（父流水线也继续执行）。否则我们就只能重跑整条流水线或者后续操作全部手工执行。

**Comment by irwinsun** [comment]
已支持 手动跳过

<img width="482" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/16686129/dce2a521-01d4-42ef-928c-fe729543db2d">
