### ISSUE TITLE
feature: 期望 手动触发的构建不会被自动取消

### ISSUE THREAD

**Issue by eternalsea** [TencentBlueKing/bk-ci#2060]
背景：在 运行锁定 设置中如果设置了最大排队数。当排队数超过设定值时会自动去掉之前的构建。对于 git hook等自动触发的构建是比较适用的。

但是 手动触发 的构建往往是希望编译一个特定参数（非自动触发的默认参数）包，并不希望被自动触发的构建给自动取消了。

所以期望可以增加一个设置项 对于 手动触发 的构建不会被自动取消

![image](https://user-images.githubusercontent.com/14304956/87410728-4138ee00-c5f9-11ea-8f66-b96d55a9b5b9.png)

**Comment by iccengan** [comment]
@eternalsea 是希望有两条队列吗？根据不同的触发方式，会有不同的排队队列。
如果是的话，比较好的方式是利用两条流水线来完成。
平台不太好做这个功能，主要原因是平台无法分辨不同触发方式下的排队优先级。

**Comment by eternalsea** [comment]
@iccengan 这里应该不是指两个队列的意思，而是在同一个队列里。只是 手动触发 的不计入排队数量，也不会被自动取消，至于优先级仍然按它进入队列的次序排优先级

**Comment by zanyzhao** [comment]
嗯，场景清晰了，我们先内部讨论下再更新

**Comment by irwinsun** [comment]
目前的 并发组已经满足这类需要，同一条流水线可以根据触发设定不同的并发队列，自行设定一个流水线启动变量，手动执行时设定特定值即可


<img width="965" alt="image" src="https://github.com/user-attachments/assets/55a9d96e-c253-4185-8224-3e7e6ba5b82f">
