### ISSUE TITLE
Feature: 拉取构件插件支持glob模式匹配

### ISSUE THREAD

**Issue by chen3286822** [TencentBlueKing/bk-ci#2113]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
Entering this information will route you directly to the right team and expedite traction.
拉取构建插件的待下载文件路径，希望能支持glob模式匹配
比如 !(signed.shell).apk 过滤掉仓库中的已签名apk包

**Comment by zanyzhao** [comment]
我们先内部评估下

**Comment by zanyzhao** [comment]
> 我们先内部评估下

目前确实只支持*通配，我们可以改造为[Linux Standard Wildcards](https://tldp.org/LDP/GNU-Linux-Tools-Summary/html/x11655.htm)
![image](https://user-images.githubusercontent.com/1629409/89185628-1ffe6880-d5cd-11ea-9475-3d80805fd5b2.png)

**Comment by irwinsun** [comment]
已经支持标准的glob及Unix风格。
但issue说的 类似 !(signed.shell).apk 这类其实并非标准的glob，而是nodejs、python类语言特有的扩展实现
