### ISSUE TITLE
如何在已部署好蓝鲸的机器上部署bk-ci？在配置bkenv文件时看到可以对接蓝鲸，请问有无部署指引？

### ISSUE THREAD

**Issue by Ssstring** [TencentBlueKing/bk-ci#2140]

**Comment by vuuv** [comment]
目前开源版还在pre-release阶段, 暂无单独部署脚本, 最近计划提供一些简易脚本, 基于systemd启动, 后续随预编译包发布. 
预编译包地址: https://github.com/Tencent/bk-ci/releases

企业版2.5支持ci, 请咨询服务商升级处理.
社区版计划在6.0版本集成ci, 今年内发布, 欢迎关注"蓝鲸"公众号或者加入社区版交流群: 495299374.
