### ISSUE TITLE
优化流水线卡片的信息展示

### ISSUE THREAD

**Issue by iccengan** [TencentBlueKing/bk-ci#2190]
**Question, Bug, or Feature?**  
*Type*: Feature

### 现象
![image](https://user-images.githubusercontent.com/10875468/88502010-ccee4980-cfff-11ea-92a0-5ec0d6a8988a.png)
1. 不同的流水线状态下，功能按钮展示不统一。执行中和执行完成两个状态无法一键进行流水线的编辑、收藏、复制等操作。
2. “插件总数”、“已执行次数”，并不是用户在流水线总览页需要关注的内容。需重新提炼重点信息，并展示在流水线卡片上。

### 期望
1. 保证流水线卡片在不同的状态下，功能交互保持统一。
2. 重新评估需展示在卡片上的信息，并替换“插件总数”以及“已执行次数”两个字段。

**Comment by ObesityChow** [comment]
Mail delivered and will be read soon. Thank you for reaching out to me.
