### ISSUE TITLE
视图支持手动选择来添加流水线

### ISSUE THREAD

**Issue by iccengan** [TencentBlueKing/bk-ci#2287]
**Question, Bug, or Feature?**  
*Type*: Feature

### 现状
目前添加流水线进入视图，只能通过筛选条件。如果流水线名称或创建人无规律，无法简单地通过筛选条件来添加流水线进入视图（除非将流水线全名作为筛选条件）。

### 期望
流水线视图支持手动选择流水线来添加

**Comment by irwinsun** [comment]
已支持
