### ISSUE TITLE
Feature:子流水线参数可筛选部分流水线

### ISSUE THREAD

**Issue by hpsls** [TencentBlueKing/bk-ci#2330]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
项目中有100条流水线，子流水线参数会全部显示，希望能在编辑流水线时做筛选，无论是手动选择或者通配符匹配，能做到实际流水线的执行者只能选择参数中规定的流水线即可

**Comment by iccengan** [comment]
如：预设置的流水线变量里，可选子流水线有 100条。但实际上你在手动执行时，只想从其中的10条里选1条

**Comment by irwinsun** [comment]
可定义 【单选框】类型的流水线变量，预设好希望被执行者选择的的‘子流水线’或者是其他‘参数值’
