### ISSUE TITLE
流水线构建详情页面支持批量下载构件

### ISSUE THREAD

**Issue by iccengan** [TencentBlueKing/bk-ci#2409]
### 现象
流水线构建详情中，当归档的构件非常多时，需要挨个构件下载，体验不佳。
![image](https://user-images.githubusercontent.com/10875468/90872054-9e7d4780-e3ce-11ea-9599-3cdeca521890.png)

### 期望
流水线构建详情页面支持批量打包并下载构件物。

**Comment by Wonder233** [comment]
赞同！我这边归档有8个构建要下载，每次都要一个一个点，太麻烦了。
3年过去了，这个需求还是没上，哭泣

**Comment by irwinsun** [comment]
> 赞同！我这边归档有8个构建要下载，每次都要一个一个点，太麻烦了。 3年过去了，这个需求还是没上，哭泣

这个功能需要服务器先把所有存储里的文件下载到服务器，然后打包再传给用户，其实是很浪费资源和执行效率的。特别是文件多和大。

因为归档的制品本质是服务于自动化，为何不考虑一下采用拉取构件的插件，自动化的拉取到指定机器上, 你也省得老要去点击下载，

<img width="705" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/16686129/5504d862-0c93-4600-8401-b884b33a3c74">
