### ISSUE TITLE
feat: 增强流水线流程控制以及批处理job

### ISSUE THREAD

**Issue by wtao901231** [TencentBlueKing/bk-ci#2428]
## 需求背景
如图有这样一个总-分-总式的构建任务，我们约定 stage 的命名和序号，便于讨论：
- **split-apks** Stage2 需要批处理N（比如图示有50）个job，每个job有这样的约束，由于没有job模板来修改它的控制参数，因而要求能自动识别上阶段Stage的入参并正确分配编译模块，调用子流水线。这个约束是为了**快速、无脑式手动复制job**
- **build-cache** Stage1 分派Stage2的job任务，是fork行为
- **base.aab** Stage3 同步等待Stage2的所有job任务完成，是join行为

![image](https://user-images.githubusercontent.com/2307321/91379470-5c805580-e855-11ea-825d-85a4609213fc.png)

## 遇到的问题和期望解决
- 无法批量配置 job
- job 内部使用的变量是流水线作用域变量，如果采用参数流程控制，当N个job同时并发时可能出现先后异常值，执行错误
- 任意job失败后会导致stage失败，stage没有出错后仍继续执行选项
- 同步调用子流水线，等待返回结果耗时比较长，采用的是最低1分钟轮询结果的方法，不够灵活和执行时间上低效（可以理解这里的全局性能考虑，但还是希望有解决方案）
- 子流水线编译产物无法归档到父流水线，通过自定义归档、path目录穿透的方式归档是不安全的行为；同时还会导致流水线的**查看视图**被最后次归档覆盖、从而无法查看到归档结果

**Comment by irwinsun** [comment]
1、无法批量配置 job
----------
A: 使用matrix job 构建矩阵，只要维护一个job，根据条件裂变多个job， 可以解决你第1个点【无法批量配置job】的问题
<img width="606" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/16686129/ff8f14fa-1ba6-4c0c-9759-3eeb0fd41b1e">

--------
2、 job 内部使用的变量是流水线作用域变量，如果采用参数流程控制，当N个job同时并发时可能出现先后异常值，执行错误
----------

A： 可以精确的定位到哪个job下的哪个插件任务产生的变量，不会发生重复。 如果你使用了matrix job ，比如用bash/run插件或自定义插件当发生错误时，输出一个变量 
```shell
echo ::set-output name=<my_var_1>::<my_var_value_1>
```
就可以使用变量  ${{ jobs.<job_id>.<matrix_index>.steps.<step_id>.outputs.<my_var_1>  }}
<job_id> 代表你在这个Job的配置UI里设置的 Job ID
<matrix_index> 代表的是裂变后的第几个job
<step_id> 就是插件任务ui中设置的 step ID
<my_var_1> 就由你命名的变量名
<my_var_value_1> 就由你定义的值

不知道我说明白了没有， 这样可以精确的定位到哪个job下的哪个插件任务产生的变量，不会发生重复，同样适用于非matrix job
比如 ${{ jobs.<job_id>.steps.<step_id>.outputs.<my_var_1>  }}

--------
3、任意job失败后会导致stage失败，stage没有出错后仍继续执行选项
--------
A：插件可以设置 失败后继续：
<img width="593" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/16686129/a40aabb3-6177-4a7d-99ea-841246878819">

--------
4、同步调用子流水线，等待返回结果耗时比较长，采用的是最低1分钟轮询结果的方法，不够灵活和执行时间上低效（可以理解这里的全局性能考虑，但还是希望有解决方案）
--------
A： 插件目前是10秒轮循一次，已经足够。
<img width="295" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/16686129/c3cfd46b-ad7e-4ce7-affc-32b2b928e99c">

--------
5、子流水线编译产物无法归档到父流水线，通过自定义归档、path目录穿透的方式归档是不安全的行为；同时还会导致流水线的查看视图被最后次归档覆盖、从而无法查看到归档结果
--------
A： 正确使用目前新版本的归档插件的配置，可以归档到父流水线中
<img width="588" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/16686129/b485e5d0-6db3-4e79-918b-58369a47d6f3">
