### ISSUE TITLE
视图管理支持流水线名称的精确匹配

### ISSUE THREAD

**Issue by leohzhuang** [TencentBlueKing/bk-ci#2626]
在视图管理功能中配置新的视图时，默认情况下，流水线的名称是自动模糊匹配的，如下图所示：

![image](https://user-images.githubusercontent.com/3130490/93744615-b68df400-fc24-11ea-957f-3b70427013a4.png)

但有些时候，我需要精确匹配某个流水线，不需要模糊匹配功能；比如说，我只想精确匹配流水线AAA，不想匹配到AAAB，AAABBB这些。

希望增加开关，能由用户决定是否开启模糊匹配功能；或者说支持正则表达式匹配功能

**Comment by iccengan** [comment]
> 希望增加开关，能由用户决定是否开启模糊匹配功能；或者说支持正则表达式匹配功能

如果支持glob通配是否能满足你的需求

**Comment by leohzhuang** [comment]
> > 希望增加开关，能由用户决定是否开启模糊匹配功能；或者说支持正则表达式匹配功能
> 
> 如果支持glob通配是否能满足你的需求

可以的，能这样最好了

**Comment by irwinsun** [comment]
通过静态分组解决

<img width="430" alt="image" src="https://github.com/user-attachments/assets/30378a2a-b440-4914-a4dc-e49d05e9d4e8">
