### ISSUE TITLE
串行流水线重试排队超时

### ISSUE THREAD

**Issue by fitzcao** [TencentBlueKing/bk-ci#2686]
1.流水线设置串行执行
2.设置排队超时时间.
3. 在有其他构建执行的情况下,重试失败流水线, 重试的流水线会立刻进入排队超时状态

**Comment by irwinsun** [comment]
从描述来看不属于bug， 重试的流水线也是要接受 排队设定，先来的执行后到的排队。 时间一到也是要超时
