### ISSUE TITLE
拉取构件-流水线仓库插件的指定构建号配置兼容最新构建号

### ISSUE THREAD

**Issue by iccengan** [TencentBlueKing/bk-ci#2782]
### 现象：
【拉取构件-流水线仓库】插件通过流水线变量配置`指定构建号`时，无法通过变量兼容`最新构建号`，只能在启动流水线时人工查找指定流水线的最新构建，并传入数字。
![image](https://user-images.githubusercontent.com/10875468/96211963-461a8e80-0fa8-11eb-9da8-2854d1cdc4b4.png)

### 期望：
`指定构建号`支持特殊字符串标识（如：HEAD），当变量${My_build_no}传入HEAD字符串时，自动获取目标流水线${Pipeline_sample}的最新构建号。

**Comment by forzenheart** [comment]
类似于SVN的版本号指定功能
![image](https://user-images.githubusercontent.com/12236093/96212170-b3c6ba80-0fa8-11eb-8b83-518350408868.png)

**Comment by irwinsun** [comment]
假设流水线A 是支持并发的， 此时有 # 11 和 # 12 两个构建任务同时在跑， 或者是 # 12 运行完了，而 # 11 点击重试了，

如果 # 11 用 【HEAD】来拿，则会拿到 # 12 ，其实是非常危险的。  所以如果想拿最新的构建号，通常就是指的当前本次的构建，
比如 # 11 用 【HEAD】 应该拿到的就是 # 11 构建号， # 12 拿到的就是 # 12 .

按上面理解， 其实用  ${{ci.build_num}}  或者  ${{ BK_CI_BUILD_NUM }} 就可以拿到本次的构建号。
