### ISSUE TITLE
构建失败后无法按照修改配置后重试

### ISSUE THREAD

**Issue by yangpengben** [TencentBlueKing/bk-ci#2899]
希望重试可以按修改后的配置进行重试

**What would you like to be added**:
重试步骤需要支持重新up配置并产出新的构建命令.

**Why is this needed**:
时效性: 构建前面的步骤都是对的,但是耗时太久,如果重头开始构建时间成本太高,

**Comment by mario206** [comment]
希望重试功能可以支持设置更新，避免重新构建等半天。
现在重试功能有点鸡肋

**Comment by irwinsun** [comment]
如果需要灵活，建议将大量构建配置脚本写入自己维护的构建脚本中，这样可以达到在重试时按需变化
