### ISSUE TITLE
流水线插件前端组件，支持上传文件类型，供插件使用

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#2901]
【需求】
增加一个上传文件的组件，供插件前端使用
- 实现原理
    - 将文件上传到项目自定义仓库下，支持指定路径
    - 上传后，将文件在自定义仓库中的路径赋值给开发者指定的变量中
    - 插件中可以使用从仓库下载文件的api，从仓库获取文件到执行机本地进行处理
- 配置
  - 开发者可以指定文件上传后在自定义仓库中的路径存储的变量名
- UI
    - 上传按钮：导入文件和填好自定义仓库路径后，将文件上传至自定义仓库。 文案：上传文件 / Upload
    - 上传文件规则说明。 文案：最大上传10M的文件 / Maximum file size: 10M
    - 已上传文件：已从本地上传至自定义仓库的文件，展示文件logo、文件名、文件大小。

注：文件限制大小 10MB，不限制文件类型

报错
文件大小不能超过10M / File size exceeds limit(10M)
非法自定义仓库路径 / Invalid custom artifactory path

组件功能参考 #133

**Comment by irwinsun** [comment]
通过文件类型的流水线变量解决，而不是在插件中操作
