### ISSUE TITLE
feat: 构建详情页重构

### ISSUE THREAD

**Issue by iccengan** [TencentBlueKing/bk-ci#2981]
### 现象：
目前构建详情页展示的内容过于简单，构建历史列表所含的信息要比详情页展示的信息多，不合理。
![image](https://user-images.githubusercontent.com/10875468/98934414-04d0bc80-251d-11eb-8c9f-0b7deb0a4c93.png)

### 期望：
构建详情页重新改版（设计师介入重新设计）。除展示构建的状态、执行人、耗时外，需要将本次构建的信息列出。
包括但不限于下图所含内容：
![image](https://user-images.githubusercontent.com/10875468/98934599-524d2980-251d-11eb-9653-5b27e477b01f.png)

其中错误码需细化出错误类型，并以tips的方式告知错误类型的含义。

**Comment by iccengan** [comment]
关联需求：#4065
需添加触发人字段，并将目前执行人的文案优化为：最近编辑人

**Comment by zanyzhao** [comment]
![image](https://user-images.githubusercontent.com/1629409/119648404-ff511900-be53-11eb-8f11-3117e5ac4941.png)

**Comment by shuiqingliu** [comment]
同有这个困扰，构建页信息过少，不便于最新版本部署

**Comment by irwinsun** [comment]
需要增加 对插件暂停耗时的计算

**Comment by irwinsun** [comment]
#7983
