### ISSUE TITLE
预检测流水线运行权限

### ISSUE THREAD

**Issue by shunli0726** [TencentBlueKing/bk-ci#3044]
现状：
环境 ：主流水线X,包含子流水线A,B,C  最后修改人为david
操作 ：peter去执行流水线X, 但是此时peter和david都没有子流水线 C 的执行权限, 主流水线X正常执行 A->B->C,到C时才会汇报错误
影响 ： 如果A->B两个流水线时间过长,会比较影响整体进度和时间  

需求 ： 希望增加一个流水线执行的权限预检测,对当前要执行的流水线以及所有子流水线进行权限检测,提前预知风险

**Comment by shunli0726** [comment]
1

**Comment by irwinsun** [comment]
该功能已实现，在保存时预检测当前保存人对于子流水插件中选定的子流水线的权限，如不满足会报错无法保存。
前提是能获得明确的子流水线，如采用变量方式填写子流水线插件的，会导致无法正确识别出子流水线，则无法判断
