### ISSUE TITLE
内置变量增加 BK_CI_AGENT_POOL_TYPE，标识JOB的构建资源类型

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#3076]
![image](https://user-images.githubusercontent.com/54432927/100407762-3cef0800-30a4-11eb-961a-7657cf16861c.png)

**Comment by iccengan** [comment]
关联issue：#1129

**Comment by hn-verson** [comment]
需求场景：
主流水线插件会通过蓝盾Open API拉起一条子流水线，同时子流水线想要复用主流水线Job中的构建资源信息（包含构建资源类型、指定构建资源等），目前蓝盾并没有输出这些信息，导致无法动态获取到具体Job的构建资源，也就无法透传至子流水线中

**Comment by irwinsun** [comment]
此变量在多个Job下是存在互相覆盖的问题，应与Job相结合，区分不同Job，此需求已经无效。
