### ISSUE TITLE
希望支持指定脚本执行时的用户权限

### ISSUE THREAD

**Issue by piratf** [TencentBlueKing/bk-ci#3106]
**What would you like to be added**:
目前多种脚本执行插件，包括海外脚本执行插件的规则都是：“Agent 是什么权限，就按照什么权限执行”。
导致 Agent 常常需要以最大权限需求，也就是 root 来启动，而所有操作就跟着用 root 执行。这样导致后续维护和使用非常不方便。

**Why is this needed**:
导致脚本任务权限无法调整，写文件全是 root 权限，使用非常麻烦。

希望可以在流水线中为环境指定权限，agent 执行脚本时切换到对应权限执行。

**Comment by irwinsun** [comment]
目前支持在.agent.properties中设定指定用户 devops.slave.user 参数指定运行用户
