### ISSUE TITLE
Configure ACL with groups

### ISSUE THREAD

**Issue by ashi009** [TencentBlueKing/bk-ci#3593]
**What would you like to be added**:

Configuring ACL with organizational groups (eg. LDAP/AD groups)

**Why is this needed**:

It's always preferred to [grant permissions to groups instead of individuals][1], as permissions on individuals are ephemeral and difficult to audit.

In the BK context, this design leads to endless [toil][2] as long as more people join/leave the team.

[1]: https://cloud.google.com/iam/docs/using-iam-securely
[2]: https://sre.google/sre-book/eliminating-toil/

**Comment by irwinsun** [comment]
v2.0版本设计的新权限中心已支持按组织架构授权【除了管理员角色】
