### ISSUE TITLE
支持代码库group事件监听

### ISSUE THREAD

**Issue by iccengan** [TencentBlueKing/bk-ci#3612]
### 期望：
group下代码库触发的push、mr等事件，支持触发流水线构建

**Comment by JacobleeDJI** [comment]
目前我们使用trpc-go开发，使用小仓库开发模式，每个服务单独一个git仓库，所有服务在一个group下，按照目前的蓝盾流水线，MR的时候只能触发固定仓库下的流水线，期望能够监听整个GROUP下的MR，不然需要每个服务都跑一条流水线，或者新增服务需要在公用流水线上添加手动添加插件，对业务不友好

**Comment by zzzzzzzzzzq** [comment]
业务认为流水线应该是某一类语言或服务都是通用同一条流水线的，按照目前的蓝盾流水线，MR的时候只能触发固定仓库下的流水线，期望能够监听整个GROUP下的MR，不然需要每个服务都跑一条流水线，或者新增服务需要在公用流水线上添加手动添加插件，对业务不友好 
这里极其影响业务接入EPC的效率，希望能尽快优化实现
