### ISSUE TITLE
OpenAPI增加接口获取构建机状态

### ISSUE THREAD

**Issue by cateatcatx** [TencentBlueKing/bk-ci#3885]
**What would you like to be added**:
增加一个OpenAPI，可以获取指定构建机的状态，状态包括CPU、磁盘IO、网络IO、当前运行的任务列表等，就是把环境节点页面的显示数据可以用API查找

**Why is this needed**:
我需要根据构建机的状态，来实现构建调度算法。最终目标就是把构建任务派发到最空闲的构建机上。环境不能满足我的需求，因为环境的调度算法没有考虑构建机上是否有构建资料（代码资源等，这些资源很大，不可能每次都checkout），所以我自己写了个服务来调度构建，现在缺少构建机状态数据。

**Comment by irwinsun** [comment]
已通过蓝鲸监控实现，具体可内部找助手了解
