### ISSUE TITLE
BUG: python 插件 task.json的demands列表不生效

### ISSUE THREAD

**Issue by kayoch1n** [TencentBlueKing/bk-ci#3946]
**What happened**:

使用 python 开发插件时发现 task.json的execution demands列表不生效，没有在插件开始之前执行自定义的指令

![image](https://user-images.githubusercontent.com/59444375/113842516-4eb88880-97c5-11eb-9c9d-790f508fb9b3.png)

**What you expected to happen**:

在插件开始之前、demands的指令得到执行

**How to reproduce it (as minimally and precisely as possible)**:

1. 初始化python插件
2. 修改task.json的demands小节，插入echo命令
3. 流水线添加该插件，执行查看日志发现对应命令没有得到执行

**Anything else we need to know?**:

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fayewong-v5** [comment]
#3666
