### ISSUE TITLE
BK-CI没有实时构建日志，错误信息  Root mapping definition has unsupported parameters

### ISSUE THREAD

**Issue by frankin5** [TencentBlueKing/bk-ci#4023]
BK-CI 版本: 1.2.11
ES版本：5.6

![image](https://user-images.githubusercontent.com/3905968/115494664-af9d9180-a298-11eb-81b3-595856774335.png)

Application-log.xml配置如下：
![image](https://user-images.githubusercontent.com/3905968/115494786-e83d6b00-a298-11eb-97e4-8e9e55c8bf9a.png)

devops-log.log的异常信息如下：
![image](https://user-images.githubusercontent.com/3905968/115494817-f7241d80-a298-11eb-8c94-72a8acf6aad4.png)

**Comment by royalhuang** [comment]
你好，BK-CI 社区版1.2.11要求的ES版本是 ≥ 7.0，只需要升级一下你的ES组件版本~

部署时可以参考我们的文档：
https://bk.tencent.com/docs/document/6.0/127/7621
直接跳到ElasticSearch那一栏有相关的解释
