### ISSUE TITLE
多浏览器页签不同时间执行流水线时，推荐版本号会被重置为旧版本号

### ISSUE THREAD

**Issue by iccengan** [TencentBlueKing/bk-ci#4060]
### 复现路径：
1. 推荐版本号配置了【每次构建+1】
2. 浏览器页签A打开执行预览页面，不动。（此前推荐版本号为123）
3. 浏览器页签B打开执行预览页面，执行流水线多次。执行完后，推荐版本号已更新为125。
4. 回到浏览器页签A，执行流水线。执行完后，**推荐版本号被重置为124**。
![image](https://user-images.githubusercontent.com/10875468/115987201-996c3a00-a5e6-11eb-8356-3be08c5e4644.png)

**Comment by seedsnie** [comment]
麻烦尽快解决下，这个问题导致编译安装包版本号重用，这个对企业产品是个严重问题，错发了版本出去，是算严重事故的、

**Comment by irwinsun** [comment]
【推荐版本号】带有原罪，因并发操作等存在无法调和的矛盾。
**不推荐** 使用 【推荐版本号】，有强需求请用 自定义构建号
<img width="638" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/16686129/fcbed05c-0a8a-4f9d-ab36-80447497ea7f">
