### ISSUE TITLE
在流水线耗时后面，追加显示重试次数

### ISSUE THREAD

**Issue by Henry-T** [TencentBlueKing/bk-ci#4188]
![image](https://user-images.githubusercontent.com/4081321/118097720-a0c47d80-b405-11eb-800e-fd8daeb6e95f.png)

上图中，显示的构建时间长大2小时，其实是做了重试。应该体现重试次数信息。

**Comment by iccengan** [comment]
重构流水线构建历史列表时一并考虑

**Comment by fayewong-v5** [comment]
已支持展示执行次数
<img width="700" alt="image" src="https://github.com/user-attachments/assets/77c635b8-1130-4a19-917b-4018b1ade371">
