### ISSUE TITLE
关于取消定时任务的改进需求

### ISSUE THREAD

**Issue by Xnco** [TencentBlueKing/bk-ci#4462]
希望流水线取消定时任务的时候能出一个类iPhone定时闹钟取消的逻辑。
取消本次执行，而不是取消定时。
应用场景，有一个每晚12点都要定时执行的任务，但偶尔某一天不用执行，只能把定时取消掉，但是第二天又需要手动打开，经常会忘记重新开启定时任务。
iPhone的定时闹钟可以关掉下一次闹钟，比如有个早8点的闹钟，点击关闭，只关闭第二天8点的闹钟，不需要第二天再开启定时闹钟。

**Comment by irwinsun** [comment]
iphone 关本次闹钟
