### ISSUE TITLE
feat: 纯内网构建支持

### ISSUE THREAD

**Issue by vuuv** [TencentBlueKing/bk-ci#4514]
**What would you like to be added**:
希望能在纯内网(和互联网完全隔离)的场景下执行构建.

**Why is this needed**:
很多用户反馈内网完全隔离.

目前已经可以在纯内网环境中部署到蓝鲸社区版基础套餐.
编译环境可以填写用户转存到私有registry的 `bkci/ci` 镜像. 
但是无编译环境需要联网从docker hub获取 `bkci/ci:alpine`. 导致无编译环境无法使用.

**参考目标**:
- [x] 研发: 梳理dockerhost加载镜像时的联网检查更新的操作, 应该能在联网超时后回滚使用本地缓存镜像.
- [x] 研发: 能自定义agentless构建镜像名称, 并正常加载.
- [ ] 部署: 部署流程兼容纯内网部署, 提供部署文档.
- [ ] 公共: 制定纯内网构建时的私有registry接入规范, 并提供实施文档.

**Comment by junjie319** [comment]
希望能支持纯内网环境，无编译环境的镜像支持

**Comment by junjie319** [comment]
目前已经可以在纯内网部署？请问下是安装现有文档部署？我这边环境搭建和中间件都已安装成功，但是在nginx配置有问题，按照文档​
rm -rf /usr/local/openresty/nginx/conf
ln -s  __INSTALL_PATH__/gateway /usr/local/openresty/nginx/conf
已经把nginx配置软连到conf下了，并且OPENRESTY nginx，都安装成功了，但是页面显示“Welcom to openresty”,没能找到静态资源。请问能给个nginx配置模板，或者已有能正常显示的nginx配置Demo给出来吗？

**Comment by vuuv** [comment]
@junjie319 这里的部署指的是部署到蓝鲸社区版基础套餐中. 我已更新issue避免歧义. 

你的nginx不能正常使用的问题请检查nginx错误日志. 不属于此issue讨论范围.

**Comment by vuuv** [comment]
#4521

**Comment by vuuv** [comment]
先行提供内网构建建议: 
[TencentBlueKing/BKDocs/blob/master/ZH/6.0/部署指南/产品白皮书/增强包维护/蓝盾/Opitmize.md](https://github.com/TencentBlueKing/BKDocs/blob/master/ZH/6.0/%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97/%E4%BA%A7%E5%93%81%E7%99%BD%E7%9A%AE%E4%B9%A6/%E5%A2%9E%E5%BC%BA%E5%8C%85%E7%BB%B4%E6%8A%A4/%E8%93%9D%E7%9B%BE/Opitmize.md)
