### ISSUE TITLE
feat: 子流水线变量输出支持输出所有变量

### ISSUE THREAD

**Issue by hellopao** [TencentBlueKing/bk-ci#4720]
目前子流水线插件输出变量要一个个填写变量名，在子流水线存在很多变量或者变量名称不确定时配置很不友好，希望能增加通配符支持。
例：`子流水线输出变量`参数值为`*`，则输出所有变量

**Comment by irwinsun** [comment]
*输出变量会将所有子流水线变量都输出，存在安全隐患，不建议。

如果变量名称不确定，则输出回来也没有意义。

另外可以对该参数设定一个变量，由启动时输入，就可以做到灵活指定
<img width="445" alt="image" src="https://github.com/user-attachments/assets/507d70c5-8edc-44fc-a3c2-d19d7910643e">
