### ISSUE TITLE
希望支持分支进行上架测试

### ISSUE THREAD

**Issue by Toplife** [TencentBlueKing/bk-ci#4780]
背景
我的蓝盾商店的一个原子要变更，那目前我这边的做法是先拉一个分支，然后分支修改，修改完了合入master，然后在蓝盾的工作台新增测试版本，然后在流水线测试，如果测试有问题，那就需要重复上述步骤

问题：
1. 这样效率比较低
2. 其实合入的master不一定是OK的（因为很多情况是需要走完流程才可以验证的）

**Comment by yjieliang** [comment]
需对插件版本数据进行初始化处理
1、将所有T_ATOM表 LATEST_TEST_FLAG字段数据设置为false
UPDATE T_ATOM
SET LATEST_TEST_FLAG = b'0';

2、将最新构建的插件测试版本数据LATEST_TEST_FLAG字段设置为true
UPDATE T_ATOM t1
JOIN (
SELECT ATOM_CODE, MAX(UPDATE_TIME) AS max_update_time
FROM T_ATOM t2
WHERE ATOM_STATUS IN (4, 5)
GROUP BY ATOM_CODE
) t2 ON t1.ATOM_CODE = t2.ATOM_CODE AND t1.UPDATE_TIME = t2.max_update_time
SET t1.LATEST_TEST_FLAG = b'1';
