### ISSUE TITLE
bug:无编译环境特殊场景流水线卡死

### ISSUE THREAD

**Issue by fitzcao** [TencentBlueKing/bk-ci#4794]
以下场景会出现流水线卡死，需等到job超时流水线才会结束。
复现步骤：
1. job为无编译环境。
2. job下的第一个插件为内部插件。如：人工审核，作业执行等插件。
3. 后续插件内有“前置失败才运行”的触发条件。
4. 第一个插件最终状态为失败。如审核驳回，执行超时等。

**Comment by irwinsun** [comment]
经验证此功能已经被修复
