### ISSUE TITLE
模版流水线超过200个报错

### ISSUE THREAD

**Issue by hujingguang** [TencentBlueKing/bk-ci#4842]
![image](https://user-images.githubusercontent.com/11848843/127953077-9658e0c4-bd14-4eba-8dc7-cf0a2a0fbf2c.png)
且模版下的流水线全部无法显示

**Comment by fayewong-v5** [comment]
请提供下部署的蓝盾版本和报错时的process日志

**Comment by hujingguang** [comment]
![image](https://user-images.githubusercontent.com/11848843/129651311-36716b41-2dea-4a98-bf86-35c1ebe2c6b1.png)

**Comment by hujingguang** [comment]
bkci version: 1.5.4

**Comment by hujingguang** [comment]
> 请提供下部署的蓝盾版本和报错时的process日志

蓝盾版本： 1.5.4
