### ISSUE TITLE
BK CI Pipeline as code

### ISSUE THREAD

**Issue by ALINRUISU** [TencentBlueKing/bk-ci#4857]
**What would you like to be added**:
BK CI Pipeline as code, instead of using the gui we can add pipeline as yaml code for better user experience. 
Imaging I can create a slack bot filling the parameters > submit that as code to  BK CI

**Why is this needed**:
To better support functionality, great user experience and repeatability

**Comment by irwinsun** [comment]
PAC will release in v3.0
