### ISSUE TITLE
公共构建机流水线构建超时

### ISSUE THREAD

**Issue by MrRachelWong** [TencentBlueKing/bk-ci#4936]
**Environment**:
- bk-ci version : v1.5.9 （基于蓝鲸社区版本v6.0.3安装）
- OS: CentOS Linux release 7.9.2009 (Core)
- Kernel : Linux localhost 3.10.0-1160.el7.x86_64

流水线构建在 `Set up job` 环节就报错(超时)

![image](https://user-images.githubusercontent.com/4916195/129300022-158adeaf-3bec-48f3-ae24-78d83ffc3321.png)

**Comment by irwinsun** [comment]
提供排查思路：
buildId 表示是 构建id， 存在于执行详情url上以b-开头字符串，
比如
http://xxx.yyy/console/pipeline/aov/p-yyyy/detail/b-cefd73db3bf34886b8a9877762ea9015
这个 b-cefd73db3bf34886b8a9877762ea9015 就是构建id，具体以你为准


需要你查看 dockerhost所在机器 /data/devops/logs/{当前构建b-开头的buildId}/1/agent.log  看看里面报了什么错。

**Comment by MrRachelWong** [comment]
本次构建的日志存位置:
/data/bkce/logs/ci/docker/b-b85a73070df44b6d853dda6410782654/1/

这个目录下只有一个文件  docker.log

cat docker.log

输出日志只有这些:
start to download the docker_init.sh...
download docker_init.sh success, start it...

**Comment by MrRachelWong** [comment]
我找了一个早前可以成功构建的日志



```
# pwd
/data/bkce/logs/ci/docker/b-fdace90e3f7545b7afe1730803efee2b/1

# ll
total 688
-rw-r--r-- 1 root root 697065 Jun 29 17:49 agent.log
-rw-r--r-- 1 root root    145 Jun 29 17:46 docker.log
-rw-r--r-- 1 root root      0 Jun 29 17:46 runtime.log

# cat docker.log 
start to download the docker.jar...
download the docker.jar finished, ready to start it...
24b3eaf03ca8e036243ff409a1c645d3  docker.jar
93177470

## cat agent.log (这个日志输出内容也是正常的）
```

**Comment by irwinsun** [comment]
通常是内部xxx.yyy域名在docker下不通，要配置hosts或者是dns
