### ISSUE TITLE
Docker公共构建机执行报错，因 devops_gateway 环境变量不正确

### ISSUE THREAD

**Issue by tangyouyou** [TencentBlueKing/bk-ci#5370]
蓝盾默认的 bkci:latest 镜像，启动脚本中依赖变量 ${devops_gatway}，这个值映射进去是 bk-ci.service.consul。但是在 bkci 中没有挂载 Consul，所以无法解析域名。
![docker-3](https://user-images.githubusercontent.com/13697036/138043748-044ed67d-5fe1-4e30-b770-c63655457dc2.jpg)

**Comment by irwinsun** [comment]
属于部署配置不正确问题，
