### ISSUE TITLE
【拉取构件】插件同步内部版本的功能

### ISSUE THREAD

**Issue by iccengan** [TencentBlueKing/bk-ci#5400]
### 现象：
根据latest build No. 拉取制品时候， 如果有新的构建在跑但是还没有执行完成会导致报错。
![3da40bf2-0ff0-4ec0-87e5-6446cb2989b5](https://user-images.githubusercontent.com/10875468/138628729-a900388a-4e33-4667-af8d-928271b44bbd.png)

### 期望（与内部版本功能保持一致）：
1. 添加 Latest Succeessful BuildNo. 选项，即判断最近一次执行成功的构建号
2. Specific BuildNo. 支持传入流水线变量

**Comment by hummerstudio** [comment]
@iccengan 这个功能是需要在1.9才能实现吗？

**Comment by irwinsun** [comment]
<img width="493" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/16686129/2e00cd2a-2fc4-4c73-9d13-d06cdf41d2d2">
https://github.com/TencentBlueKing/ci-downloadArtifact/releases/tag/v1.0.5
