### ISSUE TITLE
支持Stage准出

### ISSUE THREAD

**Issue by iccengan** [TencentBlueKing/bk-ci#5456]
### 期望：
1. 质量红线控制准出
2. 红线结果影响流水线最终执行状态

### 准入准出差异：
1. `准入`强调能否执行后续步骤；`准出`强调已执行步骤是否符合预期
2. `准入`不影响流水线状态；`准出`影响流水线状态

### 待办：
1. 设计-配置质量红线准出的入口
2. 执行完成后的准出展示页面与Stream保持一致

**Comment by irwinsun** [comment]
code模式下已支持
