### ISSUE TITLE
'com.tencent.devops.dispatch.service.JobQuotaInterface' that could not be found.

### ISSUE THREAD

**Issue by wilsondlli** [TencentBlueKing/bk-ci#5507]
**What happened**:
release-1.7 分支的代码无法正常运行

**What you expected to happen**:
release-1.7 分支的代码正常运行

**How to reproduce it (as minimally and precisely as possible)**:
编译后打包进 https://hub.docker.com/r/blueking/bk-ci 这个 docker 镜像

**Anything else we need to know?**:
报错日志：
2021.11.08 07:09:44,513|| [        main]  INFO c.z.h.HikariDataSource                   110  DBPool-Project - Starting...
2021.11.08 07:09:44,664|| [        main]  INFO c.z.h.HikariDataSource                   123  DBPool-Project - Start completed.
2021.11.08 07:09:44,962|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|projectJooqConfiguration|com.tencent.devops.project.service.UserCacheService
2021.11.08 07:09:45,552|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|qualityJooqConfiguration|com.tencent.devops.quality.dao.v2.QualityRuleBuildHisDao
2021.11.08 07:09:45,565|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|qualityJooqConfiguration|com.tencent.devops.quality.service.v2.QualityIndicatorService
2021.11.08 07:09:45,575|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|qualityJooqConfiguration|com.tencent.devops.quality.service.v2.QualityMetadataService
2021.11.08 07:09:45,599|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|qualityJooqConfiguration|com.tencent.devops.quality.dao.v2.QualityRuleBuildHisOperationDao
2021.11.08 07:09:45,606|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|qualityJooqConfiguration|com.tencent.devops.quality.service.v2.QualityRuleBuildHisService
2021.11.08 07:09:45,625|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|qualityJooqConfiguration|com.tencent.devops.quality.service.v2.QualityRuleOperationService
2021.11.08 07:09:45,650|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|qualityJooqConfiguration|com.tencent.devops.quality.service.v2.QualityControlPointService
2021.11.08 07:09:45,659|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|qualityJooqConfiguration|com.tencent.devops.quality.service.v2.QualityRuleService
2021.11.08 07:09:45,697|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|qualityJooqConfiguration|com.tencent.devops.quality.service.v2.QualityHisMetadataService
2021.11.08 07:09:45,708|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|qualityJooqConfiguration|com.tencent.devops.quality.service.QualityNotifyGroupService
2021.11.08 07:09:45,721|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|qualityJooqConfiguration|com.tencent.devops.quality.service.v2.QualityCountService
2021.11.08 07:09:45,742|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|qualityJooqConfiguration|com.tencent.devops.quality.service.v2.QualityHistoryService
2021.11.08 07:09:45,747|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|qualityJooqConfiguration|com.tencent.devops.quality.service.v2.QualityRuleBuildHisOperationService
2021.11.08 07:09:45,770|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|qualityJooqConfiguration|com.tencent.devops.quality.service.v2.AuthQualityService
2021.11.08 07:09:45,786|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|qualityJooqConfiguration|com.tencent.devops.quality.service.v2.QualityTemplateService
2021.11.08 07:09:45,834|| [        main]  INFO f.a.AutowiredAnnotationBeanPostProcessor 367  Inconsistent constructor declaration on bean with name 'thirdPartyAgentMgrService': single autowire-marked constructor flagged as optional - this constructor is effectively required since there is no default constructor to fall back to: public com.tencent.devops.environment.service.thirdPartyAgent.ThirdPartyAgentMgrService(org.jooq.DSLContext,com.tencent.devops.environment.dao.thirdPartyAgent.ThirdPartyAgentDao,com.tencent.devops.environment.dao.thirdPartyAgent.ThirdPartyAgentEnableProjectsDao,com.tencent.devops.environment.dao.NodeDao,com.tencent.devops.environment.dao.EnvNodeDao,com.tencent.devops.environment.dao.EnvDao,com.tencent.devops.environment.dao.thirdPartyAgent.AgentPipelineRefDao,com.tencent.devops.environment.service.thirdPartyAgent.IAgentDisconnectNotifyService,com.tencent.devops.environment.service.slave.SlaveGatewayService,com.tencent.devops.common.environment.agent.ThirdPartyAgentHeartbeatUtils,com.tencent.devops.common.client.Client,com.fasterxml.jackson.databind.ObjectMapper,com.tencent.devops.environment.client.InfluxdbClient,com.tencent.devops.environment.service.AgentUrlService,com.tencent.devops.environment.permission.EnvironmentPermissionService,com.tencent.devops.environment.service.thirdPartyAgent.UpgradeService,com.tencent.devops.common.websocket.dispatch.WebSocketDispatcher,com.tencent.devops.environment.service.NodeWebsocketService,com.tencent.devops.environment.dao.EnvShareProjectDao)
2021.11.08 07:09:45,836|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|environmentJooqConfiguration|com.tencent.devops.environment.service.thirdPartyAgent.ThirdPartyAgentMgrService
2021.11.08 07:09:45,901|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|environmentJooqConfiguration|com.tencent.devops.environment.service.slave.SlaveGatewayService
2021.11.08 07:09:45,949|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|environmentJooqConfiguration|com.tencent.devops.environment.service.thirdPartyAgent.UpgradeService
2021.11.08 07:09:45,953|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|environmentJooqConfiguration|com.tencent.devops.environment.service.thirdPartyAgent.DownloadAgentInstallService
2021.11.08 07:09:46,001|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|environmentJooqConfiguration|com.tencent.devops.environment.service.thirdPartyAgent.AgentPipelineService
2021.11.08 07:09:46,016|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|environmentJooqConfiguration|com.tencent.devops.environment.service.thirdPartyAgent.ThirdPartyAgentPipelineService
2021.11.08 07:09:46,057|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|environmentJooqConfiguration|com.tencent.devops.environment.service.NodeService
2021.11.08 07:09:46,067|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|environmentJooqConfiguration|com.tencent.devops.environment.service.EnvService
2021.11.08 07:09:46,107|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|dispatchJooqConfiguration|com.tencent.devops.dispatch.docker.service.DockerHostZoneTaskService
2021.11.08 07:09:46,115|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|dispatchJooqConfiguration|com.tencent.devops.dispatch.docker.service.DockerHostBuildService
2021.11.08 07:09:46,153|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|dispatchJooqConfiguration|com.tencent.devops.dispatch.docker.utils.DockerHostUtils
2021.11.08 07:09:46,157|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|dispatchJooqConfiguration|com.tencent.devops.dispatch.docker.client.DockerHostClient
2021.11.08 07:09:46,164|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|dispatchJooqConfiguration|com.tencent.devops.dispatch.docker.service.DockerHostProxyServiceImpl
2021.11.08 07:09:46,196|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|dispatchJooqConfiguration|com.tencent.devops.dispatch.docker.service.DockerResourceOptionsService
2021.11.08 07:09:46,207|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|dispatchJooqConfiguration|com.tencent.devops.dispatch.docker.service.DispatchDockerService
2021.11.08 07:09:46,224|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|dispatchJooqConfiguration|com.tencent.devops.dispatch.docker.service.DockerHostDebugService
2021.11.08 07:09:46,243|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|dispatchJooqConfiguration|com.tencent.devops.dispatch.docker.controller.UserDockerHostResourceImpl
2021.11.08 07:09:46,266|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|dispatchJooqConfiguration|com.tencent.devops.dispatch.service.PipelineVMService
2021.11.08 07:09:46,279|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|dispatchJooqConfiguration|com.tencent.devops.dispatch.service.JobQuotaManagerService
2021.11.08 07:09:46,293|| [        main]  INFO c.t.d.m.c.JooqConfiguration              78   dslContext_init|dispatchJooqConfiguration|com.tencent.devops.dispatch.service.JobQuotaBusinessService
2021.11.08 07:09:46,297|| [        main]  WARN ConfigServletWebServerApplicationContext 591  Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jerseySwaggerConfig' defined in class path resource [com/tencent/devops/common/web/WebAutoConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'opJobQuotaProjectResourceImpl' defined in URL [jar:file:/data/bkce/ci/jars-private/biz-dispatch-1.6.0-RELEASE--da1d4702266eae5697608354e2652784.jar!/com/tencent/devops/dispatch/controller/OpJobQuotaProjectResourceImpl.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jobQuotaBusinessService' defined in URL [jar:file:/data/bkce/ci/jars-private/biz-dispatch-1.6.0-RELEASE--da1d4702266eae5697608354e2652784.jar!/com/tencent/devops/dispatch/service/JobQuotaBusinessService.class]: Unsatisfied dependency expressed through constructor parameter 5; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.tencent.devops.dispatch.service.JobQuotaInterface' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
2021.11.08 07:09:46,439|| [        main]  INFO c.z.h.HikariDataSource                   350  DBPool-Project - Shutdown initiated...
2021.11.08 07:09:46,448|| [        main]  INFO c.z.h.HikariDataSource                   352  DBPool-Project - Shutdown completed.
2021.11.08 07:09:46,464|| [        main]  INFO ConditionEvaluationReportLoggingListener 136

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021.11.08 07:09:46,487|| [        main] ERROR o.s.b.d.LoggingFailureAnalysisReporter   40

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 5 of constructor in com.tencent.devops.dispatch.service.JobQuotaBusinessService required a bean of type 'com.tencent.devops.dispatch.service.JobQuotaInterface' that could not be found.

Action:

Consider defining a bean of type 'com.tencent.devops.dispatch.service.JobQuotaInterface' in your configuration.

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by irwinsun** [comment]
release-1.7 分支还没正式发，还有一些PR需要CherryPick
