### ISSUE TITLE
在蓝盾用go写插件需要支持一个压缩包中同时放linux/mac/windows三个平台的可执行文件

### ISSUE THREAD

**Issue by onion822** [TencentBlueKing/bk-ci#5639]
需求：
在蓝盾用go写插件需要支持一个压缩包中同时放linux/mac/windows三个平台的可执行文件，现在只支持放一个平台的，希望能支持这个功能

**Comment by carlyin0801** [comment]
目前可以修改zip包中的task.json配置、把多个平台的可执行文件都打入zip压缩中就行。
task.json需要调整的execution配置如下：
![image](https://github.com/user-attachments/assets/278efe82-850b-4762-a952-d7634b001c79)

**go插件需支持多操作系统需要增加os配置，os配置如下：**
```
"os" : [
  {
    "osName":"linux", # 支持的操作系统名称【必填】
    "osArch":"amd64", # 支持的操作系统CPU架构【非必填】
    "target" : "./app", # 执行命令入口相关【必填】
    "demands" : ["echo hello"], # 执行前置命令【非必填】
    "defaultFlag": true # 是否为默认环境信息（每种操作系统默认环境配置有且只有1个,没有匹配的操作系统名称和cpu架构就使用该默认环境配置）【必填】
  }
]
```
osName和osArch各语言配置规则:

![企业微信截图_17224106126570](https://github.com/user-attachments/assets/5c3daa35-0093-4d15-b6a3-806cca5e011c)

**可执行文件名称命名规范建议：**
windows系统下可执行文件命名规则： windows-$osArch-app.exe，osArch为上面表格中的变量
linux系统或者mac系统下可执行文件命名规则： $osName-$osArch-app，osName和osArch为上面表格中的变量
