### ISSUE TITLE
流水线变量：变量类型选择 代码库、GIT分支/tag 获取不到代码库列表

### ISSUE THREAD

**Issue by ChangJinLong** [TencentBlueKing/bk-ci#5962]
**What happened**:
![5LLF1PO@B4)U90~ 2U0U2BK](https://user-images.githubusercontent.com/50789549/148202042-402ed561-7051-4db1-b263-0a8444d75c7e.png)
**通过接口传参和数据库对比发现repositoryType传递的参数不对**
错误参数：repositoryType=CODE_GIT
正确参数：repositoryType=CODE_GITLAB

**Comment by jackchenkai** [comment]
蓝盾版本都少？

**Comment by irwinsun** [comment]
早期版本已经修复
