### ISSUE TITLE
插件执行失败时，构建环境登录调试保留最近执行结束后的现场

### ISSUE THREAD

**Issue by iccengan** [TencentBlueKing/bk-ci#6101]
### 现状：
流水线Job执行结束后，容器就被销毁了。当插件执行失败登录调试时，不再保留容器创建记录，构建环境无法与流水线执行后保持一致，难以定位执行失败的问题。

### 期望：
流水线执行失败后，构建环境的登录调试支持保留最近执行结束后的现场（包括工作空间、环境变量等）

**Comment by reggieisrunning** [comment]
现状：
1. 流水线Job执行结束后，容器就被销毁了。当插件执行失败登录调试时，不再保留容器创建记录，构建环境无法与流水线执行后保持一致，难以定位执行失败的问题。

期望：
流水线执行失败后，构建环境的登录调试支持保留最近执行结束后的现场（包括工作空间、环境变量等）
