### ISSUE TITLE
前置编辑流水线的权限校验

### ISSUE THREAD

**Issue by iccengan** [TencentBlueKing/bk-ci#6332]
### 现象：
仅拥有查看流水线权限，仍能进入编辑界面。当完成编辑并点击”保存“时，提示无权限保存流水线。

### 期望：
1. 流水线构建历史页面添加流水线详情页签，可查看当前流水线描述、标签、编排等信息
<img width="809" alt="image" src="https://user-images.githubusercontent.com/10875468/158530484-ca17ecc5-f20d-4950-a14f-25a68ef1cd96.png">
2. 点击右上角”编辑“按钮时，校验是否有编辑权限。
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/10875468/158530770-64b8264c-d74d-4083-9c35-67cf5eff8878.png">

**Comment by irwinsun** [comment]
新版权限已经支持
