### ISSUE TITLE
禁用插件输出变量的命名空间配置

### ISSUE THREAD

**Issue by iccengan** [TencentBlueKing/bk-ci#6402]
### 现状：
用户仍能添加插件输出变量的命名空间。

### 期望：
对于未使用命名空间的Task，将命名空间编辑按钮置灰禁用，引导用户使用`上下文`方式，确保增量用户不再使用命名空间。
对于已使用命名空间的Task，保留现逻辑。用户可以更改命名空间，但只要把命名空间清空并保存流水线后，不再能使用命名空间功能。
![image](https://user-images.githubusercontent.com/10875468/159660584-c3305d49-efc7-444f-9693-f14477a9d7fe.png)

**Comment by irwinsun** [comment]
禁用 不现实，因为还有api用户通过api方式修改编排。
这种功能应交由用户决定。 不好用自然大家就不会用，而改用上下文
