### ISSUE TITLE
拉取P4插件支持输出当前构建的“源材料”、“commit id”、“提交人”、“提交时间”

### ISSUE THREAD

**Issue by iccengan** [TencentBlueKing/bk-ci#6486]
### 期望：
拉取P4代码的流水线构建，也能支持查看源材料以及代码变更记录。类似于拉取Git的场景。
![image](https://user-images.githubusercontent.com/10875468/161370812-8877eb40-b71c-4a73-abe6-d92c92339e97.png)
![image](https://user-images.githubusercontent.com/10875468/161370777-33955ab6-bfe5-4cab-8c1a-9e3033355971.png)

**Comment by fayewong-v5** [comment]
https://github.com/TencentBlueKing/bk-ci/issues/8375
