### ISSUE TITLE
请问检查代码的插件在哪里可以获取？

### ISSUE THREAD

**Issue by ghost** [TencentBlueKing/bk-ci#6498]
1. 请问检查代码的插件 codecc 是官方自带的插件还是使用者自己开发的？在哪里可以获取到？
2. Checkout gitlab插件的执行日志经常提示：”该插件已不推荐使用“，请问有新版的插件吗？

**Comment by JamiKX1** [comment]
回复下1：代码检查插件是蓝盾的官方插件，开源代码https://github.com/TencentBlueKing/ci-CodeCCCheckAtom ，可自行打包后在蓝盾-->研发商店-->工作台上架
