### ISSUE TITLE
自定义文件型变量，可以支持保留文件原名，不被复原

### ISSUE THREAD

**Issue by Dreamxjguo123** [TencentBlueKing/bk-ci#6534]
自定义文件型变量，可以支持保留文件原名，不被复原
需求场景：同时多个人执行时，文件会被相互覆盖，导致混乱

**Comment by irwinsun** [comment]
流水线仓库归档用于解决这类问题，请请用流水线仓库归档。 

自定义保留文件，就涉及到版本化管理，但版本化未必能用好，用不好会导致更隐蔽，带来更严重的问题

**Comment by irwinsun** [comment]
如果是 “文件”类型的变量， 在执行时，上传前可以先修改上传输入框的路径文件名，就不会互相覆盖的。
但不支持解析 上传的文件名并覆盖输入框的路径文件名，因为这是破坏性的调整，体验上发生重大变化，直接会对现有用户造成影响
