### ISSUE TITLE
流水线增加"分支未更新时不触发"的能力

### ISSUE THREAD

**Issue by JackStronger** [TencentBlueKing/bk-ci#668]
诉求：
想每天定时执行流水线，如果流水线选择的分支没有新的提交就不执行流水线

现状：
目前流水线的`定时触发`中可以设置`源代码未更新时不触发`。

希望：
增加一个设置项目`分支未更新时不触发`。这样就可以满足这个诉求。

**Comment by irwinsun** [comment]
为何不使用 git事件触发？

**Comment by JackStronger** [comment]
git事件触发无法满足诉求哈，git事件触发的频率是很高的。
诉求是：想每天定时执行流水线，如果流水线选择的分支没有新的提交就不执行流水线

**Comment by JackStronger** [comment]
> 为何不使用 git事件触发？
git事件触发无法满足诉求哈，git事件触发的频率是很高的。
诉求是：想每天定时执行流水线，如果流水线选择的分支没有新的提交就不执行流水线

比如我想监听一个分支，每天早上9点只出1个包，但是如果昨天到现在没人在这个分支上提过代码，那我今天就不出包了

**Comment by JackStronger** [comment]
> 为何不使用 git事件触发？

git事件触发无法满足诉求哈，git事件触发的频率是很高的。
诉求是：想每天定时执行流水线，如果流水线选择的分支没有新的提交就不执行流水线

**Comment by JackStronger** [comment]
> 为何不使用 git事件触发？

git事件触发无法满足诉求哈，git事件触发的频率是很高的。
诉求是：想每天定时执行流水线，如果流水线选择的分支没有新的提交就不执行流水线

比如我想监听一个分支，每天早上9点只出1个包，但是如果昨天到现在没人在这个分支上提过代码，那我今天就不出包了

**Comment by irwinsun** [comment]
> > 为何不使用 git事件触发？
> 
> git事件触发无法满足诉求哈，git事件触发的频率是很高的。 诉求是：想每天定时执行流水线，如果流水线选择的分支没有新的提交就不执行流水线
> 
> 比如我想监听一个分支，每天早上9点只出1个包，但是如果昨天到现在没人在这个分支上提过代码，那我今天就不出包了

定时触发与代码库耦和 这个功能其实存在弊端， 目前因为是扫描流水线中的“拉代码”插件来判断是关联了哪些代码库，是属于比较烂的设计， 
如果定时触发要做成一个基础能力，则需要考虑增加以下3个配置项，需要指定：
1、监听代码仓库
2、监听的分支
3、是否有更新

这样才能实现所需要的功能。

**Comment by irwinsun** [comment]
这个需求在蓝盾Stream已经实现， 后续Stream与蓝盾 的 PAC 一体融合需求来处理

可关注该需求 【支持从代码库维度查看对应的代码库事件 #8122】
