### ISSUE TITLE
feat: 打开单流水线详情页时，浏览器页签title显示流水线名称

### ISSUE THREAD

**Issue by reggieisrunning** [TencentBlueKing/bk-ci#6905]
场景：
       项目中流水线频繁的创建、销毁，收藏和搜索有时并不满足锚定近期需求打开的流水线，但没有最近打开的流水线记录
需求：
       打开单流水线详情页时，浏览器页签title显示流水线名称

**Comment by irwinsun** [comment]
see #9000
