### ISSUE TITLE
【内置插件】bash 机制优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#7000]
**What would you like to be added**:

优化 bash 机制，当执行失败时，能根据提示中的失败行数找到源代码准确的位置

**Why is this needed**:
![image](https://user-images.githubusercontent.com/54432927/173788286-66cac04f-53a3-46fa-803d-83972e4d6bb8.png)

**Comment by carlyin0801** [comment]
已实现
