### ISSUE TITLE
bugfix: 修复turbo启动失败

### ISSUE THREAD

**Issue by stubenhuang** [TencentBlueKing/bk-ci#7272]
修复turbo启动失败

本issue 主要解决因升级开源组件导致的问题 feat: 升级存在漏洞的开源依赖组件 #6691

原漏洞组件
[spring-cloud-openfeign-core/3.0.3](https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-openfeign-core/3.0.3)
的漏洞经过评估，平台不在影响范围，所以仍然先恢复回3.0.3 解决3.1.2高版本带来的兼容问题

**Comment by irwinsun** [comment]
[spring](https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-openfeign-core/3.0.3)
的恢复经过评估，平台不在影响范围，所以仍然先恢复回3.0.3 解决3.1.2高版本带来的兼容问题
