### ISSUE TITLE
【蓝盾】【产品-线下评审】流程控制选项“自定义变量满足条件”优化

### ISSUE THREAD

**Issue by reggieisrunning** [TencentBlueKing/bk-ci#7313]
### 我作为：
蓝盾流水线编排的用户

### 我希望：
1. Stage\Job\Task中流程控制选项能让我基于自己的场景使用自定义变量编辑判断条件，而不是只能支持“自定义变量全部满足时运行”和“自定义变量全部满足时不运行”

### 这样我就可以：
1. 可以完成“==, !=, >, >=, <, <=, &&, ||, !, ()”基本逻辑场景去控制Stage\Job\Task是否运行

### 期望的验收标准：
1. Stage、Job、Task的流程控制选项中，去除“自定义变量全部满足时才运行”、“自定义变量全部满足时不运行”两个选项；
2. Stage、Job、Task的流程控制选项中，增加“条件表达式”选项；
3. 选择“条件表达式”选项后，下方出现代码编辑器，样式如下图：
![image](https://user-images.githubusercontent.com/82890468/181426955-44e2769e-fd9a-4aab-8324-8f95f1a0ae08.png)
4. 允许多行输入；
5. 代码编辑器中只允许输入“条件”部分，比如：判断语句bash脚本是「 `if ${{ variabes.fooBarVar1 }}==3 && ${oldFooBarVar1}!=2` 」，则编辑器中只允许出现「`variabes.fooBarVar1 == 3 && env.oldFooBarVar1 != 2`」的部分 ；
6. 不符合正确的表达式，下方出现红色波浪线提示语法错误；
7. 支持与bash插件variables一致的关键字联想；
8. 输入不正确的表达式，不可保存，使用通用错误提示样式，错误文案：“条件表达式语法错误”
9. 存量的自定义变量条件需转换为“条件表达式”；

**Comment by reggieisrunning** [comment]
以下issue将合并至该issue统一设计：
#1522 
#1747

**Comment by reggieisrunning** [comment]
补充条件表达式错误时，提示错误的样式

**Comment by irwinsun** [comment]
https://github.com/TencentBlueKing/bk-ci/issues/10467
https://github.com/TencentBlueKing/bk-ci/issues/10474
