### ISSUE TITLE
流水线超时之后无法重试的设计意图

### ISSUE THREAD

**Issue by WCJ-Chance** [TencentBlueKing/bk-ci#7404]
我注意到，流水线超时之后会停止，并且和一般的手动停止或者job出错不一样的是：超时停止之后无法重试。请问这一块这么设计的意图是什么？

**Comment by reggieisrunning** [comment]
@WCJ-Chance 
hi，这里的超时场景是怎样的？是“stage人工审核超时”还是其他

**Comment by WCJ-Chance** [comment]
> 

这里的场景是人工审核超时，也只有人工审核才会让超时时间达到流水线系统超时上限
