### ISSUE TITLE
单体部署报错

### ISSUE THREAD

**Issue by leizeonban** [TencentBlueKing/bk-ci#7506]
![image](https://user-images.githubusercontent.com/31756777/187222650-bd6492ff-22cc-4e55-9bb2-a55bf1122f19.png)

**Comment by zanyzhao** [comment]
目前的出包方式不适合单体包部署（即便有，也是在1个容器中安装一堆组件），我们还在考虑今年出一个单包应用，但改造成本略高，还需要进一步评估。

目前最佳的体验方法是：通过[蓝鲸智云7.0内置的k8s部署方案](https://bk.tencent.com/docs/document/7.0/172/29314)体验
