### ISSUE TITLE
环境管理：对于已经接入的机器，出现异常时进行告警说明

### ISSUE THREAD

**Issue by dengweisysu** [TencentBlueKing/bk-ci#777]
对于成功接入（状态显示正常）的机器，后续因为其他原因（比如agent被kill），建议增加告警机制，告警到该机器的接入负责人，可以尽快进行处理，避免发布时才发现问题，影响发布流程。

**Comment by zanyzhao** [comment]
这issue挂太久了，我们可以拆分下，优先支持agent离线告警功能吧，其它类型的主机告警后续再加

**Comment by irwinsun** [comment]
Agent 的状态依赖于Agent端上报心跳到服务端， 当Agent被Kill或机器关机等具体原因在事发时是无法得知， 服务端仅能根据心跳异常（1分钟未收到心跳）来判断Agent是否正常。

**Comment by fayewong-v5** [comment]
需支持可配置，有些场景，如用户本地开发机，晚上关机，上班时间开机，无需告警。
