### ISSUE TITLE
perf: API支持获取到红线和其他失败状态

### ISSUE THREAD

**Issue by royalhuang** [TencentBlueKing/bk-ci#7787]

**Comment by carrywang05** [comment]
为了更好的满足通用需求，需要进行更加通用的设计。之前基于流水线变量的设计存在2个问题：

1、只包含了质量红线的信息，还会有Step的失败、Job的失败、Stage的失败等；

2、流水线变量只能存放4000个字节，可能会导致有些情况下数据无法储存。

因此改为OpenAPI的方案。具体如下：

接口能力：应用态API、用户态API、流水线插件SDK

请求参数：项目ID、流水线ID、构建ID

返回数据：

（1）Stage失败或取消

Stage失败或取消一般是一个，主要是因为Stage准入/Stage准出失败。

数据需要包含：

Stage名称、Stage ID（可能为空）、errorType、errorCode、errorMsg、失败时间

（2）Job失败或取消

Job失败或取消可能是一个，也可能是多个（由于Job并行等特性）。主要是构建机启动失败或者发生异常而中断。

数据需要包括：

Job名称、Job ID（可能为空）、errorType、errorCode、errorMsg、失败时间

（3）Step失败或取消

Step失败或取消可能是一个，也可能是多个（由于Job并行、插件失败后继续执行等特性）。主要是插件本身出错或者构建机资源不足等。

数据需要包括：

Step名称、Step ID（可能为空）、errorType、errorCode、errorMsg、失败时间

（4） QualityGate失败或取消

质量红线失败或取消可能是一个或者多个。

数据需要包括：

红线名称、红线ID、红线状态码、审核人、拦截/通过时间等

红线状态码如下：

qualityGateStatus=0 存在指标不符合红线要求，但是人工审核通过
qualityGateStatus=-1 存在指标不符合红线要求，红线自动失败
qualityGateStatus=-2 存在指标不符合红线要求，人工审核拒绝而失败
