### ISSUE TITLE
feat: 蓝盾对接权限中心RBAC

### ISSUE THREAD

**Issue by reggieisrunning** [TencentBlueKing/bk-ci#7794]
**What would you like to be added**:

**Why is this needed**:

**Comment by mingshewhe** [comment]
# 1. 蓝盾从1.0升级到2.0
> 2.0相对于1.0的版本,权限从对接权限中心v3升级到对接权限中心rbac，对鉴权数据做了较大的变更 所以升级后, 需要调用命令做变更后数据迁移

说明：
- 如果全新部署, 不需要关注本文档
- 当前环境 版本<2.0.0的, 需要关注, 按步骤处理

## 1.1 升级步骤
1. 在auth服务,执行
```
curl -XPOST http://127.0.0.1:{AUTH_PORT}/op/auth/migrate/allToRbac
```
参数数据:
- AUTH_PORT: auth服务端口，容器化中是80

2. 检查迁移结果

连接devops_ci_auth数据库，执行
```
select * from devops_auth.T_AUTH_MIGRATION where STATUS=0;
```
说明：
- status有三个值，0-迁移中,1-迁移成功,2-迁移失败
- 迁移中的项目不要访问，请求可能会报资源不存在

## 1.2 异常处理
迁移命令可以重复执行，如果异常可以重复迁移
