### ISSUE TITLE
bk-booster涉及到的/etc/bk_dist路径希望可以支持配置

### ISSUE THREAD

**Issue by sworda** [TencentBlueKing/bk-ci#7835]
bk-booster涉及到的/etc/bk_dist路径希望可以支持配置，或者install脚本支持一个安装目录参数，所有用到的文件都安装或生成到安装目录下，不然每次安装还要考虑是否有/etc目录的权限问题

**Comment by tming** [comment]
如果安装到指定目录，在运行时涉及到查找配置文件的问题

**Comment by dazuo168** [comment]
后续安排实现

**Comment by irwinsun** [comment]
请关注到 bk-
