### ISSUE TITLE
bug：流水线使用【checkout】插件拉取代码后代码变更记录页面上显示“unknown repo”

### ISSUE THREAD

**Issue by ZeroLin0** [TencentBlueKing/bk-ci#7924]
**What happened**:
在流水线上使用【checkout】插件拉取代码后，代码变更记录页面上本应该是会显示commit信息点击后可以跳转到代码库，目前无法点击跳转，仓库名也显示“unknown repo”

![image](https://user-images.githubusercontent.com/37146260/199673232-838d5684-469c-49fd-ad50-90dda5d72be9.png)

**Comment by mingshewhe** [comment]
已修复
