### ISSUE TITLE
【蓝盾-产品-已评审】流水线支持展示运行进度

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#7932]
**What would you like to be added**:
1、流水线详情页面，正在运行中的 step 支持展示进度
- step 进度支持插件运行过程中自行上报
- 上报方式：
  - 在插件日志中输出如下关键字：::set-progress-rate 0.3758
- 未上报进度则不展示
- 进度 为小于 1 的浮点数，精度4
- 展示示例：
  <img width="200" alt="image" src="https://github.com/user-attachments/assets/fd6e1633-d185-44f4-95de-771812863a2e">

2、流水线执行历史页面，正在运行中的 stage 支持展示完成度
   <img width="300" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/0f3838cc-a25f-444c-80e4-292a24ae2907">

  - stage 完成计算公式：(stage下已完成的步骤个数 + Sum stage下运行中的步骤上报的进度) / stage下总步骤数
  - 若 stage 下所有步骤都已经运行完成，但 stage 还在做收尾操作（如准出判定）时，进度展示 99%，直至 stage 状态完成
  - 包含 post action
  - 进度 为小于 1 的浮点数，精度4
  - 只有运行中的stage hover 时需要展示
  - 展示出正在运行的步骤：
      - 如果步骤上报了进度，展示对应的进度
      - 如果未上报，不展示进度

**Why is this needed**:
有些构建节点，会跑个2小时以上，如果没有进度的话，非构建人员去看的时候，会比较懵，不知道当前啥进展了

**Comment by EchoQT** [comment]
ok

**Comment by irwinsun** [comment]
在脚本中 echo "::set-progress-rate 0.3758"  
即可，不需要额外提供 sdk方法， 
如此一来业务的 shell脚本都能无缝使用起来
