### ISSUE TITLE
【蓝盾】【产品-已评审】超时时间字段支持填写变量

### ISSUE THREAD

**Issue by reggieisrunning** [TencentBlueKing/bk-ci#7954]
# 背景：
- 在使用同一个流水线模板的情况下，每次填入的任务类型不同，则任务需求的超时时间不同。这些任务的编排一致，只是入参有区别，但是超时时间现在只能直接配置死，不能动态更改。

# 我作为：
     需要超时时间可动态变化的用户

# 我希望：
     Job、Task中的“执行超时时间”配置可支持填写变量

# 这样我就可以
     根据流水线跑的任务不同，动态调整超时时间。而不用每次都修改流水线，或使用多个「编排一致、超时时间不一致的」流水线模板

# 期望的验收标准：
    1. Job、Task中的“执行超时时间”可填写进入变量；
![image](https://user-images.githubusercontent.com/82890468/201000742-f1df2a9b-b25a-449e-96a0-fe2fad0c4aa2.png)
![image](https://user-images.githubusercontent.com/82890468/201000747-2e6ed91e-618a-44f6-8a51-2ffc7b9818ce.png)

**Comment by EchoQT** [comment]
ok

**Comment by irwinsun** [comment]
这个需求并不难，但需要产品明确：
如果运行到这个设置超时逻辑时，当变量出现非法的值，是要直接执行失败，还是以默认值（900分钟）来执行超时逻辑

**Comment by irwinsun** [comment]
包袱：
原timeout为数字型，并且暴露到API协议中被下游平台广泛应用，不适合直接修改，需要新增一个timeoutVar 字段。
界面设定以timeoutVar字段值为准，原timeout继续保留有效。

**Comment by EchoQT** [comment]
> 这个需求并不难，但需要产品明确： 如果运行到这个设置超时逻辑时，当变量出现非法的值，是要直接执行失败，还是以默认值（900分钟）来执行超时逻辑

这个后来有结论吗？极端情况参数传入value非法时可以按默认值来执行超时逻辑，但还是应该以某种方式对用户进行报错。



> 包袱： 原timeout为数字型，并且暴露到API协议中被下游平台广泛应用，不适合直接修改，需要新增一个timeoutVar 字段。 界面设定以timeoutVar字段值为准，原timeout继续保留有效。

不太理解，如果和faye他们已讨论清楚的话，我会找他们了解情况。

@fayewong-v5 @irwinsun

**Comment by irwinsun** [comment]
> > 这个需求并不难，但需要产品明确： 如果运行到这个设置超时逻辑时，当变量出现非法的值，是要直接执行失败，还是以默认值（900分钟）来执行超时逻辑
> 
> 这个后来有结论吗？极端情况参数传入value非法时可以按默认值来执行超时逻辑，但还是应该以某种方式对用户进行报错。

这个有结论了，在保存时，如果使用的变量是已经定义了，会进行值校验，如果校验不通过则无法保存。 而针对在运行过程中才产生的变量，当value出错时，采用默认值来作为超时逻辑， 同时在日志中会提醒用户发生了改变。



> 
> > 包袱： 原timeout为数字型，并且暴露到API协议中被下游平台广泛应用，不适合直接修改，需要新增一个timeoutVar 字段。 界面设定以timeoutVar字段值为准，原timeout继续保留有效。
> 
> 不太理解，如果和faye他们已讨论清楚的话，我会找他们了解情况。
> 
> @fayewong-v5 @irwinsun


增加字段原因只有一个： 
 原timeout字段 类型从int 整数型转换为 string 字符串类型后会导致 下游平台解析出错：
timeout涉及到运算和类型转换，如果突然把timeout 变成字符串， 下游平台拿到后做数字转换就会出错，下游平台数量众多，而且可能有些已经无后续开发，不太好强制让所有平台做统一的解析调整。
