### ISSUE TITLE
【蓝盾-评审会已评审】feat：流水线构建详情页重构需求

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#7983]
【变更要点】
1. 完善构建 summary 信息，如构建描述、触发人、触发时间、触发库、源材料、编排版本等
2. 完善耗时信息：总耗时包括 系统耗时、执行耗时、等待耗时
  - 系统耗时(systemElapsed)：启动运行后到运行结束之间，由系统操作引入的耗时。
    - 影响因素包括：
      - 构建机调度/准备/启动时间
      - 插件下载/安装/启动时间
      - 参数解析处理时间
      - 构建资源释放时间
    - 注意，Stage/流水线 上计算系统耗时时，需根据时间线来汇总处理，而不是将所有 task 的执行时间相加
  - 执行耗时(executeElapsed)：启动运行后到运行结束之间，Sum（插件启动到插件运行完毕之间的耗时）
    - 插件运行完毕：插件逻辑运行结束，且输出信息已处理完成，对应步骤已为结束态
    - 注意：
      -  人工审核插件也属于此范畴（占用公共资源）
      - Stage/流水线 上计算执行耗时时，需根据时间线来汇总处理，而不是将并发 Job 的等待时间相加
  - 等待耗时：启动运行后到运行结束之间，处于等待的耗时。
    - 影响因素包括：
      - 第三方构建机等待资源耗时
      - stage准入人工审核等待耗时
      - stage准入的质量红线等待审核耗时
      - 插件暂停到启动/终止的等待耗时
      - Job依赖等待被依赖Job运行完毕
      - Job互斥等待
    - 注意，Stage/流水线 上计算等待耗时时，需根据时间线来汇总处理，而不是将并发 Job 的等待时间相加
3. 增加排队时间(queueElapsed)： 系统接收到触发事件的时间，到真正启动执行之间还有一些耗时。
  - 影响因素包括触发事件解析、触发条件判定、运行策略判定（如只能串行时需等待前置构建运行完毕）等
4. 汇总错误信息，支持定位到具体错误步骤
5. 在重新构建/重试失败场景下，优化对应构建的查看方式
6. 支持隐藏/展开跳过的步骤
7. 编排展示中，去调原来的stage1（触发器+启动参数）的展示：
  - 启动参数单独一个tab展示
  - 触发方式在 summary 中体现
8. POST ACTIONS 默认收起
9. 去调右下角的小地图
10. 查看全部日志时，按照流水线编排聚合日志（增加索引，参考目前job日志查看），补充系统日志
  

【交互详情】
1. 改版后的构建详情页面如下图所示：
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/54432927/203886683-462d5571-8348-4088-84fd-94a723a09c27.png">

2. 当构建失败时：
2.1 进入详情页默认定位到第一个错误点
  <img width="945" alt="image" src="https://user-images.githubusercontent.com/54432927/201628369-95901013-e73e-4bdc-9f5e-5ad599b33039.png">

2.2 错误列表点击错误位置时，定位到具体的位置

2.3 错误列表是针对当前次运行的，切换重试次数后，错误列表展示的信息可能不一样

3. 当构建被取消时，summsry 信息中的构建状态hover 提示操作人信息
<img width="966" alt="image" src="https://user-images.githubusercontent.com/54432927/201629057-f4cc5e21-39ee-444e-ada8-b9afcce685fc.png">

4. 当多个源材料时，点击后原地展开：
<img width="558" alt="image" src="https://user-images.githubusercontent.com/54432927/201630423-ef46a11f-9e13-4060-a83b-9d4bb7476976.png">

5. 当重试失败时，当前次触发未运行的步骤弱化展示
<img width="406" alt="image" src="https://user-images.githubusercontent.com/54432927/201630352-4fe80adf-dfc9-4e08-96a6-badbb52d934e.png">

6. 进入详情页面时，默认隐藏跳过的步骤，可一键展开/收起
<img width="633" alt="image" src="https://user-images.githubusercontent.com/54432927/203887040-9d5efd04-dd3f-4f30-ac56-e63119c01404.png">

7. 可以查看当前次运行的所有日志，点开后侧滑展示，日志结构参考目前 job 日志展示的形式
<img width="553" alt="image" src="https://user-images.githubusercontent.com/54432927/203887172-a9e29752-06c0-4fed-b050-9dc0da6b9e77.png">

**Comment by EchoQT** [comment]
@fayewong-v5  确认一下：
隐藏跳过步骤不勾选时，那些因为逻辑而被跳过的步骤会如何显示？
既然首次执行时不允许勾选步骤，出现跳过一般是因为逻辑分支导致的，对吧？
出现失败并点击重试的时候，已经执行成功的步骤会重新执行还是会直接跳到失败步骤重新执行，这个点应该讨论过，帮我recall一下。

**Comment by fayewong-v5** [comment]
> 

1、隐藏跳过步骤不勾选时，那些因为逻辑而被跳过的步骤会如何显示？
----- 不勾选时，因逻辑跳过的步骤灰色，别名上有中划线：
<img width="150" alt="image" src="https://user-images.githubusercontent.com/54432927/210324722-7f9acb4c-8c2a-4aef-91fd-c7a21c8c2115.png">

2、既然首次执行时不允许勾选步骤，出现跳过一般是因为逻辑分支导致的，对吧？
----- 是的

3、出现失败并点击重试的时候，已经执行成功的步骤会重新执行还是会直接跳到失败步骤重新执行，后者的话样式上有什么区别？这个点应该讨论过，帮我recall一下。
----- 已经执行成功的步骤不会再次执行，从失败的 job or task 开始执行。样式上如下图 stage1，弱化展示标识非当前次运行
<img width="500" alt="image" src="https://user-images.githubusercontent.com/54432927/210325208-00744c3c-60be-43a5-a143-5a094162ccb0.png">

4、确认一下右下角的小地图去掉的原因，新设计是用失败信息作为交互主线索，所以感觉小地图没啥用而且占用空间？
----- 考虑到几点：
1）新设计有失败信息索引，可以快速定位到错误点
2）很多编排比较复杂的流水线，是在一条流水线里编排了多个场景。支持了「隐藏跳过的步骤」功能之后，查看一次运行的步骤也少了很多，不太需要小地图预览
3）当一次运行里执行了很多步骤时，要查看细节，使用小地图定位和页面滚动条拖动定位差别感觉不是很大

**Comment by EchoQT** [comment]
ok

**Comment by royalhuang** [comment]
并行job运行中的重试操作在后续版本中改造 #8253
