### ISSUE TITLE
怎么对接gogs/gitee这种除了tencent外的源码管理服务

### ISSUE THREAD

**Issue by xx-zhang** [TencentBlueKing/bk-ci#7993]
**What would you like to be added**:

**Why is this needed**:

修改git https时候只能选择 `code.tencent, code.git.tencent`, 但是我们实际上使用gogs居多；

**Comment by irwinsun** [comment]
这个要去对接不同的git库的api才能获得 webook的事件推送

如果只是单纯使用，完全可以直接贴url到 checkout插件中，即可拉代码。

**Comment by xx-zhang** [comment]
> 这个要去对接不同的git库的api才能获得 webook的事件推送
> 
> 如果只是单纯使用，完全可以直接贴url到 checkout插件中，即可拉代码。

时隔两年，这个解决方案我早已知晓。
