### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：代码库列表展示的内容优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8117]
【需求】
1、标识已经开启 Pipeline as Code 的代码库
<img width="400" alt="image" src="https://user-images.githubusercontent.com/54432927/207223160-fabc674a-8152-457b-9ac8-0f2860634ef0.png">

2、去掉“类型”列，代码库类型通过地址前的 logo标识
<img width="400" alt="image" src="https://user-images.githubusercontent.com/54432927/207223351-1165b314-344e-4432-864b-c8acebb03bd6.png">

3、新增“最近修改人”、“最近修改时间” 两列

4、操作列，去掉“编辑”
编辑入口改到新增的详情页内

5、代码库别名，点击进入详情页

6、代码库地址，点击新开 tab 跳转到代码库

**Comment by EchoQT** [comment]
ok

**Comment by fabio-he** [comment]
1.表格展示列名和表格设置名称没有对齐
![image](https://github.com/TencentBlueKing/bk-ci/assets/56472792/f7b79e84-3a70-4722-b654-9a4b8ce25c88)

2.序列是去掉了吗? issue上面没有写要去掉
![image](https://github.com/TencentBlueKing/bk-ci/assets/56472792/a915c341-5aa2-40b1-a1df-457ebc1e3e2c)
