### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：新增代码库详情页

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8118]
【需求】
在代码库列表点击“别名”进入此详情页，页面如下：
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/54432927/207224963-356b33eb-022b-405c-b8c7-32e121f3f605.png">

1、页面左侧为代码库导航，展示代码库别名列表：
<img width="234" alt="image" src="https://user-images.githubusercontent.com/54432927/207809534-fce9ea80-33eb-4a0b-b545-bfc979f91085.png">
- 可以通过“展开列表”入口，回到列表方式的页面
  - 宽窄表 和 全列表 方式，属于用户偏好，记住用户上一次操作时访问的方式
- 可以点击 别名 快速切换到对应代码库详情
- 可以新增代码库和按别名搜索代码库，功能和代码库列表页一致

2、页面右侧上方为代码库别名和代码库路径
- hover 别名出现修改别名和删除代码库入口
  <img width="385" alt="image" src="https://user-images.githubusercontent.com/54432927/207812135-633692fd-a26f-4a77-ade3-8f00e1336079.png">
- 删除代码库时，若存在关联的流水线，提示用户修改流水线后再删除
- 代码库路径可以一键复制
- 代码库路径点击后新开tab，打开代码库
 

3、页面工作区展示如下信息：
- 用户授权
  - 重置授权见：#8145 
- PAC开启状态，当已开启时，可以快捷查看关联的流水线，点数字跳转到流水线界面，根据代码库搜索出流水线：
  <img width="400" alt="image" src="https://user-images.githubusercontent.com/54432927/207863157-e7894303-e155-48f1-a86a-2eadb6c1bee3.png">
  - 关闭 PAC 操作见：#8146
  - 开启 PAC 时：
    - 检测默认分支 .ci 目录下的文件，自动同步流水线，同步规则见：#8130
    - 检查授权方式，一期仅支持 OAUTH 授权
      <img width="200" alt="image" src="https://user-images.githubusercontent.com/54432927/207878260-5f738b3b-6b1e-4d80-8fdc-bfefbfa8594d.png">

~~- 通用设置支持代码库维度 开关 “阻塞合并请求“~~
  - 打开后， mr 触发的流水线，当流水线运行中、或运行失败时，不允许合并 MR 
- 展示创建人、创建时间、修改人、修改时间

**Comment by EchoQT** [comment]
可以通过“展开列表”入口，或上方导航上的“代码库”回到代码库服务首页
-----这里的理解有点问题，所谓的详情页其实就是代码库服务的首页。这种宽窄表的设计其实是同一个页面，展开或收起只是用户的偏好，系统记住这个偏好即可。

**Comment by EchoQT** [comment]
页面右侧上方为代码库别名和代码库路径

----代码库别名如何修改？

**Comment by EchoQT** [comment]
打开后， mr 触发的流水线，当流水线运行中、或运行失败时，不允许合并 MR

-----这是出于什么考虑？不能做到当前版本运行着，允许我mr并只作用到后续的流水线运行吗？

**Comment by fayewong-v5** [comment]
> 可以通过“展开列表”入口，或上方导航上的“代码库”回到代码库服务首页
> 
> -----这里的理解有点问题，所谓的详情页其实就是代码库服务的首页。这种宽窄表的设计其实是同一个页面，展开或收起只是用户的偏好，系统记住这个偏好即可。

已更正需求描述：
<img width="400" alt="image" src="https://user-images.githubusercontent.com/54432927/209789135-9c91052b-47e8-4ca2-a63e-3d7c8bec920e.png">
