### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：支持从代码库视角查看关联的触发器

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8119]
【需求】
支持用户从代码库视角查看当前代码库触发 CI 的场景，界面如下：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/208344996-37a3f5de-c694-4477-bff8-f50e25139df8.png">
1、从触发器配置的条件是否相同，来区分是不是同一种触发场景，条件包括：
- 代码库
- 触发器类型
- 若为定时触发：
  - 定时规则
  - 源代码未更新时是否触发
- 若为代码库事件触发，则包含影响“是否触发”的所有条件，以 Git Push 事件触发为例：
    - 监听/排除分支
    - 监听/排除路径
      - 路径过滤规则
    - 监听/排除用户
    - 自定义触发控制 - 接口地址
    - 自动移触发控制 - 接口鉴权
 
注：触发器别名不作为场景唯一性判定条件。若多条流水线里同一个触发场景，仅别名不一样，展示最新的一个别名即可

2、手动/远程/定时触发，和代码库弱相关，仅针对当前流水线。则从代码库维度来查看时，可以从当前流水线是否同时定义了代码库事件触发器来做判定：
- 若流水线同时定义了 （手动 || 远程 || 定时触发） && 代码库 A 的事件触发，则从代码库 A 的维度查看时，可以看到对应的手动/远程/定时触发。让用户从代码库A 维度查看时，知道不仅仅是代码库事件触发关联的流水线，手动/远程/定时也会触发
- 若流水线仅仅定义了 手动 || 远程 || 定时触发， 则从代码库维度看不到

3、点击流水线个数，可以跳转到流水线列表，过滤出此种触发场景下的所有流水线

4、点击 “详情” ，侧滑打开当前触发场景的配置（和流水线触发器查看页面一致）

5、将触发器添加到多条流水线见 issue #8121 

6、支持根据触发器类型、触发器别名、事件类型 搜索触发场景

**Comment by EchoQT** [comment]
2、手动/远程/定时触发，和代码库弱相关，仅针对当前流水线。则从代码库维度来查看时，可以从当前流水线是否同时定义了代码库事件触发器来做判定：
若流水线同时定义了 （手动 || 远程 || 定时触发） && 代码库 A 的事件触发，则从代码库 A 的维度查看时，可以看到对应的手动/远程/定时触发。让用户从代码库A 维度查看时，知道不仅仅是代码库事件触发关联的流水线，手动/远程/定时也会触发
若流水线仅仅定义了 手动 || 远程 || 定时触发， 则从代码库维度看不到

-----感觉最后一句有点问题，比如如果流水线的触发方式只是手动方式、并且拉取代码库A并执行，为何从A的视角看不到这个触发？是系统做不到吗？
