### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：支持从代码库维度查看对应的代码库事件

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8122]
【需求】
支持用户查看代码库事件的触发结论：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/208384873-8fab7df9-928d-424b-ba19-beceae497f96.png">

1、“事件” 由 “谁的” “什么动作” “在什么时间点”触发，触发“成功的流水线数/总流水线数”
- [master]Commit [5d301be0] pushed by xxx
-  Note [85047862] submitted by xxx
- [{来源分支}]Tag [xxx] pushed by xxx
- Merge requests [!2] push-update by xxx

总流水线数：监听了此事件的流水线个数
成功的流水线数：满足触发条件，成功触发运行的流水线数

2、每个事件可能触发 1～n 条流水线
若没有流水线监听对应的事件，不展示

3、触发成功的流水线，展示对应的构建号，如 <img width="16" alt="image" src="https://user-images.githubusercontent.com/54432927/208387850-9d18947f-f158-4df2-8eaf-f01cd64e5d6d.png">，点击新 tab 打开对应的构建详情

4、触发失败的流水线，展示失败类型 + 失败详情

5、触发事件 可以点击后新开 tab 打开对应的事件详情
- push：代码库提交信息页面
- mr：mr 详情页面
- Note：评论可能是针对代码提交、issue、 mr 的，打开对应的页面并定位到对应的评论
- issue： issue 详情
- code review： review 详情

7、当需要时，可以重放事件，详见 issue #8124 

8、支持根据如下条件查询事件：
- 触发时间段
- 事件类型
- 触发人
- 流水线名称
- 事件ID

**Comment by EchoQT** [comment]
3、触发成功的流水线，展示对应的构建号，如 image，点击新 tab 打开对应的构建详情
4、触发失败的流水线，展示失败类型 + 失败详情
-----问：失败的不需要提供构建号及其链接吗？

5、触发事件 可以点击后新开 tab 打开对应的事件详情
push：代码库提交信息页面
mr：mr 详情页面
Note：评论可能是针对代码提交、issue、 mr 的，打开对应的页面并定位到对应的评论
issue： issue 详情
code review： review 详情
-----问：这些新开的tab是工蜂界面还是蓝盾的界面？

**Comment by fayewong-v5** [comment]
> 3、触发成功的流水线，展示对应的构建号，如 image，点击新 tab 打开对应的构建详情 4、触发失败的流水线，展示失败类型 + 失败详情 -----问：失败的不需要提供构建号及其链接吗？
> 
> 5、触发事件 可以点击后新开 tab 打开对应的事件详情 push：代码库提交信息页面 mr：mr 详情页面 Note：评论可能是针对代码提交、issue、 mr 的，打开对应的页面并定位到对应的评论 issue： issue 详情 code review： review 详情 -----问：这些新开的tab是工蜂界面还是蓝盾的界面？

-----问：失败的不需要提供构建号及其链接吗？

**Comment by EchoQT** [comment]
> > 3、触发成功的流水线，展示对应的构建号，如 image，点击新 tab 打开对应的构建详情 4、触发失败的流水线，展示失败类型 + 失败详情 -----问：失败的不需要提供构建号及其链接吗？
> > 5、触发事件 可以点击后新开 tab 打开对应的事件详情 push：代码库提交信息页面 mr：mr 详情页面 Note：评论可能是针对代码提交、issue、 mr 的，打开对应的页面并定位到对应的评论 issue： issue 详情 code review： review 详情 -----问：这些新开的tab是工蜂界面还是蓝盾的界面？
> 
> -----问：失败的不需要提供构建号及其链接吗？ 触发失败时，还未生成构建号，没有详情链接
> 
> -----问：这些新开的tab是工蜂界面还是蓝盾的界面？ 是工蜂的界面，这里跳转到的是触发源详情页面

对对，刚刚想岔了。
