### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：新建/编辑流水线支持以 Code 方式编排流水线

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8125]
1、新建流水线时，支持选择模版：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/207881997-72c9f61b-954f-406b-ac90-99c21501e57b.png">
- 模版展示按新版设计重构：
  - 项目下的模版包括“空白模版” + 项目自定义模版 + 从研发商店安装到当前项目的模版
  - 空白模版固定第一个展示，其他模版按照字母顺序A～Z排序

2、模版上 hover 时，可以「预览」模版，支持通过 Code or UI 方式预览，issue 详见 #8159

3、选择模版、填写名称，点「创建」后开始编排：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/208616413-87060319-9dad-49cd-86f2-4ca407e1cd4d.png">
- 编排方式继承用户上一次的偏好，比如用户预览模版时选了 Code 方式，进入此页面后默认 Code 编排
- 若新增/修改了编排内容，点击「保存草稿」 后，才可以切换编排方式

4、使用 Code 编排过程中，因插件配置可能比较复杂，可以通过插件UI编辑来生成 Code 片段：
- 点击 「添加插件」进入选择插件页面：
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/208619324-a61b0aab-849e-4304-8a99-d39a8d9a79ff.png">
- 选中插件后，可以填写插件入参：
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/208619668-3a1d9190-028c-44b5-9b25-cf9fa39734e2.png">
- 可以预览插件 Code 配置片段
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/208620275-78dbc660-6dc1-4dbf-b746-aeaced8698a8.png">
- 点「确定」后将插件配置片段添加到流水线编排中，若点击「添加插件」按钮前：
  - 光标在一个新 step 添加区域，则在对应区域添加
  - 光标在一个已有的 step 配置区域，则在该 step 之后 添加一个新的 step
  - 光标在 job 配置区域，则在 job下的 steps 末尾添加一个新的 step
  - 光标在 stage 配置/流水线配置区域，则在最后一个 stage 的最后一个 job 末尾添加一个新的 step
- 新添加的 step 配置段 高亮，开始修改编排时去掉高亮

5、已添加的 step，光标在对应 step 配置区域时，出现 「插件设置」
<img width="200" alt="image" src="https://user-images.githubusercontent.com/54432927/208622205-8433b146-0df2-4781-a67e-e6a407f57477.png">
- 「插件设置」行为系统预留的行，不参与代码文件行数计算
- 点击「插件设置」，侧滑打开插件编辑界面，与4中的新增选中后界面/操作一致

6、Code 编排过程中，支持语法检测 #8162，支持语法提示 #8163

7、点击「语法指引」，新 tab 打开语法说明文档
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/208624198-915ab0ca-f923-4334-940d-689b870657a5.png">

8、流水线编排ok，保存草稿之后，可以进行调试，详见 #8164
- 保存草稿前，进行语法检测，不合法则无法保存

9、流水线调试 ok 之后，点击「发布」提交一个正式版本
- 新增流水线时，可以选择流水线仅保存在蓝盾，在蓝盾管理；或者提交到代码库，同时在代码库和蓝盾管理
- 新增流水线时，默认仅保存在蓝盾，界面如下：
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/208627243-c87d7ac9-c5b9-45a5-903b-27f178e297dc.png">
  - 可以填写版本描述，说明当前版本进行了什么变更
  - 标签根据 Code 配置里的 label 属性渲染，Code模式下不支持在此界面编辑标签
    -  stream label 配置支持 key-value 模式见 issue #8166
  - 根据标签、名称等信息自动填充「动态流水线组」
  - 可以手动选择加入哪些「静态流水线组」  
  - 点击「发布」后，自动生成一个正式版本
    - 版本号生成规则详见 #8161
- 若流水线希望同时可以在代码库中管理，可以「开启PAC」
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/208633246-47315d20-afbb-44d1-acb7-89ddbd1b4ccb.png">
  - 一期代码库仅支持工蜂
  - 选择代码库：仅能选择已开启 PAC 模式的代码库
  - 填写YAML文件路径，合法性校验：
    - .ci 下仅支持 1 级目录
    - 文件为 .yml 或 .yaml 结尾 
  - 填写版本描述，版本描述将作为提交代码库的 commit msg
  - 选择目标分支，有两种方式
    - 直接提交到默认分支，前提是当前用户有默认分支的提交权限，并且项目组允许提交到默认分支，否则提交将失败
    - 新建分支并创建 MR：
      - 系统使用当前用户的 OAUTH 新增一个分支
      - 把当前流水线提交到此分支
      - 自动创建 MR 到默认分支
        - 若 MR 没有合并，当前版本虽然已经生成版本号，但状态为「等待合入默认分支中」 
          - 此时不能再发布新版本，需要合入默认分支后再发布
- 发布成功后，提示用户多分支场景下 YAML 的生效规则：（规则内容）
  <img width="400" alt="image" src="https://user-images.githubusercontent.com/54432927/208645976-e64280a0-c179-4d11-b155-5688c5fc54af.png">
   - 生效规则：
     1. Push/Tag 触发时，流水线配置以 触发分支/Tag 上对应的 YAML 文件为准
     2. MR 触发时，以源和目标分支最新 YAML为准。当源和目标分支同时修改了 YAML 文件，则需要先将目标分支变更同步到源分支
     3. 其他触发方式（定时、手动、issue、review、note等）时，流水线配置以 默认分支 上对应的 YAML 文件为准
     4. 流水线查看页面，展示 默认分支 上对应的 YAML 文件内容
    - 点击「查看流水线」进入流水线详情
    - 点击「返回列表」进入流水线列表

**Comment by EchoQT** [comment]
提示用户多分支场景下 YAML 的生效规则

-----对这段文本提一个同样的问题，规则描述要先说清楚主要规则，再说次要规则，而不是全部按触发类型去描述。

**Comment by mqshen** [comment]
问下，像 CodeGitlabElement 这些插件什么时候会把 as code 的编排功能合入开源版本？
