### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：开启PAC模式的代码库支持自动同步代码库YAML变更到蓝盾

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8130]
【前提】
代码库已开启 PAC（Pipeline As Code）模式

【YAML文件管理规范】
- YAML 文件统一在 .ci 目录下管理
- 流水线模版在 .ci/templates 下管理
- .ci 目录下的一个 YAML 文件唯一标识一条流水线
- .ci 目录下的流水线 YAML 仅支持 1 级子目录管理

【需求】
1、当代码库 .ci 目录下新增YAML 文件时：
- 在对应的蓝盾项目下，自动创建流水线
  - 流水线唯一性：以代码库 + 文件路径为流水线唯一性判定依据。当文件路径不变时，视为同一条流水线。
  - 流水线名称：若 YAML 中定义了顶级关键字 name，则取对应配置，否则默认为 YAML 文件名（不带路径，如 a.yml）
  - 流水线创建人：取 push 文件到代码库的用户名
  - 版本生成规则：详见 issue #8161
    - 若当前分支为默认分支，则生成一个正式版本
    - 若当前分支为非默认分支，则生成一个分支版本
- .ci/templates 为模版目录，其下文件变更时忽略
- .ci 目录下仅支持 1 级子目录，有更深的子目录时忽略
- 同步流水线到蓝盾时，自动加到代码库对应的流水线组下：组条件issue见 #9682 
  - 组名为 [PAC][{gitProjectId}]{gitProjectName}
  - 动态流水线组，条件为 “代码库”
- 若 .ci 下的流水线在 1 级子目录下管理，则 1 级子目录也作为流水线组
  - 组名为“[PAC][{gitProjectId}]{gitProjectName}-{.ci 下1级子目录名称}” 
  - 动态流水线组，条件为 “代码库” + “.ci 下 1 级子目录名称”
- 流水线的权限，自动和代码库对齐，详见 #8202 
 
2、当代码库  .ci 目录下修改 YAML 文件时：
- 若当前分支为默认分支，生成一个正式版本
  - 流水线修改人：取 push 文件到代码库的用户名
  - 更新流水线修改时间
- 若当前分支为非默认分支，生成一个分支版本
  - 若分支 YAML git 版本落后于默认分支：
    - 发通知提醒用户及时同步主干
    - 此类版本增加警告标识

3、 当删除分支、或代码库  .ci 目录下删除 YAML 文件时：
- 若触发过CI的所有分支上对应的 YAML 均已删除，则删除对应的蓝盾流水线
  

【Tips】
- 从蓝盾修改后提交的版本，已事先在蓝盾保存，提交到代码库后触发的事件无需重复创建版本

**Comment by EchoQT** [comment]
ok
