### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：已开启 PAC 模式的代码库，支持关闭 PAC

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8146]
【前提】
代码库已开启 PAC 模式
<img width="686" alt="image" src="https://user-images.githubusercontent.com/54432927/207873194-326f9d4f-e143-48a0-a616-53f882bf5ef5.png">

【需求】
1、关闭 PAC 模式时：
- 检查代码库默认分支下是否还存在 .ci 目录：
  - 若不存在，则直接关闭
  - 若存在，则提示用户修改或删除后才可以关闭
  <img width="200" alt="image" src="https://user-images.githubusercontent.com/54432927/207874004-d5ec551a-127c-41db-bcc1-7304848076b6.png">

2、关闭 PAC 模式后，蓝盾流水线脱离和代码库 YAML 文件的同步关系，但仍然正常运行。若不希望流水线运行，手动删除流水线。

**Comment by EchoQT** [comment]
检查代码库默认分支下是否还存在 .ci 目录：
若不存在，则直接关闭
若存在，则提示用户修改或删除后才可以关闭

-----删除和禁用其实都可以走这个思路？界面上只给提示，没有按钮可操作。
