### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：新建/编辑流水线，选择模版界面支持预览模版

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8159]
【需求】
支持 Code 和 UI 两种方式预览模版

1、hover 模版/设置项，出现预览入口：
<img width="500" alt="image" src="https://user-images.githubusercontent.com/54432927/208609664-a854a127-7bf8-4bc3-85a6-5707f50b3920.png">
- 当模版没有对应的设置项时，置灰，无需进入预览

2、Code 方式预览模版：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/208607742-bfbddc6c-c771-474d-a35d-7586835fcbd9.png">
- 根据预览的是编排 / 通知设置 / 并发策略 / 标签，高亮对应的配置项

3、 UI 方式预览模版
- 预览编排
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/208647068-97ae4b2a-f6b7-4093-beb6-261e57620cea.png">
- 预览触发器
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/208645067-d0687eaf-24c8-47d3-9469-035d4b343d6f.png">
- 预览通知
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/208645199-a7d0cff4-1bef-4a45-bdd2-ad2b9d8b0a73.png">
- 预览设置
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/208645328-89a50d61-6899-49e0-bf1a-02419f91eb1b.png">

**Comment by EchoQT** [comment]
预览弹窗标题要加上模板名称

**Comment by fayewong-v5** [comment]
3.0 已实现
