### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：流水线版本管理机制

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8161]
【背景】
PAC 场景下，流水线可能是在蓝盾进行修改，也可能是在代码库进行修改。不同修改途径下，需要理清版本状态变更脉络。

【需求】
1、版本生成路径如下：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/208682403-5c09f6cf-0978-4094-87d2-b2147490e31f.png">

2、有 3 种版本状态：
- 草稿：一条流水线同一时间只有一个草稿
- 分支：可能有一个或多个分支修改了 YAML 文件，且还未合并到「默认分支」
  - A 分支上多次提交代码时，对应的版本是同一个。当A上的修改合入「默认分支」后，再在A上的修改才重新生成一个版本
  - A 分支上的 YAML 文件落后于「默认分支」时，生成的分支版本增加警告，直至同步了「默认分支」上的变更后才去掉警告
- 正式：当修改同步到「默认分支」上时，才生成对应的「正式版本」
  - 若由「普通分支」合并到 「默认分支」，对应的分支版本状态由 “分支版本” 扭转为 “正式版本”
  - 若由 「草稿」提交到「默认分支」，对应的草稿版本状态由“草稿”扭转为“正式版本”

3、当「分支版本」对应的分支被删除时，同步删除「分支版本」
- 蓝盾DB软删除

4、当「默认分支」由 X 分支修改为 Y 分支时
- 若已存在的分支版本为 Y 分支生成的，则扭转为「正式版本」
- 存量的「正式版本」不发生变化
- 在流水线的操作记录记一条变更：代码库「ggg」默认分支由「X」更新为「Y」，操作人 xxx

5、版本号规范：
- 模式为 Vd(Px.Ty.z)，如 V1(P1.T1.1)
- P 代表 pipeline ，流水线编排。stage/job/task/variables 设置发生变化时，x 递增
- T 代表 trigger，触发器。触发器发生变化时，y 递增
- 当流水线其他信息变化时，z 递增
- d 为当前正式版本的个数

注意：
- 每个版本需记录基线版本
- 分支版本记录来源分支

**Comment by EchoQT** [comment]
ok
