### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：Code 方式编排流水线时，支持语法检测，展示错误提示

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8162]
【需求】
1、在使用 Code 编排流水线时，检测当前编辑框内的内容语法是否正确
- 语法包括：
  - YAML 基本语法（缩进、列表、字符串等）
  -  Stream 语法 （pipeline 支持的关键字和语法，包括插件入参检测）
- 检测时机：
  - 用户进入 Code 编辑页面时
  - 用户输入属性名后的冒号后
  - 用户输入代码换行后
  - 保存草稿时
  - 提交发布时

2、语法不正确时的展示如下：
![image](https://user-images.githubusercontent.com/54432927/208865343-77c5c163-61a4-4884-bd7d-4639cfd8c584.png)
- 语法不正确的地方，红色波浪线提示
  - hover 波浪线 展示完整的错误信息
- 语法不正确的行，左侧行号旁边展示错误icon，点击 icon 定位到下方的错误列表对应行
- 工作区下方展示错误列表
  - 每行一个错误，提示对应的行数，以及对应的起始列数
  - 每行点击时代码区域定位到对应行列 
  - 列表先按照行数顺序排列，再按照列数顺序排列

**Comment by EchoQT** [comment]
行数有，列数是怎么来的？

**Comment by fayewong-v5** [comment]
> 行数有，列数是怎么来的？

发生错误的起始点：
- 如下图所示的关键字出错，则行为6，列为 5
  <img width="200" alt="image" src="https://user-images.githubusercontent.com/54432927/209802352-3eacdbe2-36a4-4eaf-8153-05d7935dab96.png">
- 如下图为值不正确，则行为 4，列为 17
  <img width="200" alt="image" src="https://user-images.githubusercontent.com/54432927/209802586-ba904307-7a76-4942-8de0-643bacedfa17.png">

**Comment by EchoQT** [comment]
> > 行数有，列数是怎么来的？
> 
> 发生错误的起始点：
> 
> * 如下图所示的关键字出错，则行为6，列为 5
>   <img alt="image" width="200" src="https://user-images.githubusercontent.com/54432927/209802352-3eacdbe2-36a4-4eaf-8153-05d7935dab96.png">
> * 如下图为值不正确，则行为 4，列为 17
>   <img alt="image" width="200" src="https://user-images.githubusercontent.com/54432927/209802586-ba904307-7a76-4942-8de0-643bacedfa17.png">

好吧，有必要么。。

**Comment by fayewong-v5** [comment]
3.0 已实现
