### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：新建/编辑流水线时支持调试流水线

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8164]
【需求】
流水线编辑，保存草稿后，可以进行调试，调试成功后再发布正式版本：
1、调试入口：
![image](https://user-images.githubusercontent.com/54432927/208888953-9c413d23-b364-440e-ad4e-0c73e794ce8c.png)
- 流水线有修改时，保存后才可以调试

2、点击【调试】进入入参填写界面：
![image](https://user-images.githubusercontent.com/54432927/208889244-74a9abef-0205-4bd7-a9a2-773db9b7f783.png)
- 只有勾选 “是否为入参“ 的全局变量才展示在这里
- 参数按照字母序列A~Z顺序展示
- 参数值默认填充上一次调试时的值，可以一键恢复默认

3、参数填写完毕，点击【下一步】进入步骤选择界面：
调试流水线时，可以选择本次运行哪些步骤
![image](https://user-images.githubusercontent.com/54432927/208891812-b9283120-caa4-4769-b83e-8722c23db14d.png)

4、点击【执行】后进入流水线构建详情界面，见 #7983 

5、可以在编辑流水线界面查看 调试历史
![image](https://user-images.githubusercontent.com/54432927/208892870-994c1f01-7ce2-43d8-8c9a-ce08a1914030.png)
- 调试历史和流水线的正式执行历史是隔离的，不会影响正式执行历史的构建号自增等逻辑
- 调试历史列表展示和 正式执行历史列表一致，见 #
- 当版本完成调试，发布后，清理调试历史

**Comment by EchoQT** [comment]
调试时填写入参这里，恢复默认和恢复上一次可以来回切换比较好？
