### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】perf：UI方式新增/编辑流水线重构

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8167]
【背景】
- 新增/编辑流水线需同时支持 Code 和 UI 方式编辑
- UI 方式编辑的流水线也可以开启 PAC 模式
- 现有版本变量管理和触发器管理交互不太直观，需进行优化

创建/编辑流水线流程中涉及的变更见 #8125 ，这里不再重复，此需求仅说明 UI 方式编辑时的改动

【需求】
1、进入编排页面时，默认 Code 方式 or UI 方式编辑，由用户偏好决定
- 比如用户在新建的第一个步骤预览模版切换到了 UI 方式查看，则下一步进入编排时也是 UI 方式编排

2、将原有编排中的 stage-1 下的触发器和变量管理入口拆分出去，拆分后的新入口如下图所示：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209043230-c511a88f-248b-4a5a-9a92-5bc500ab443c.png">

3、触发器管理 tab 如下：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209043328-008cc2f0-928d-4ff1-ae14-e8d57b87a911.png">
- 新增流水线时，默认添加手动触发器
  - 手动触发器配置优化见issue #8188 
- 点击「新增触发器」侧滑打开选择触发器添加界面，交互和现有版本保持一致
- 点击 触发器名称，侧滑打开触发器编辑界面，交互和现有版本保持一致
- 可以禁用触发器
  - 已经开启 PAC 模式的流水线，触发器禁用后：
    - 若切换到 Code 方式查看，看到的代码示例：
      ```
      on:
        push: disabled
      ```  
    - 若是编辑流水线，禁用前的触发器配置在DB中仍然保留，在蓝盾页面上重新启用时将恢复配置
- 可以删除触发器
  - 当删除最后一个触发器时，提示用户当前流水线将自动禁用 
    -  提示语：最后一个触发器删除后，将不能通过任何方式触发此流水线，流水线自动禁用，确定删除吗？
  - 注意：PAC 模式的流水线，可以省略 on 配置，省略后有默认的 4 个触发器，这类触发器管理见 issue #8184

4、流水线变量 tab 在编排右侧展示：
<img width="300" alt="image" src="https://user-images.githubusercontent.com/54432927/209051299-2e709e31-ea46-413a-894a-237e8bdd41cd.png">
- 可以收起和展开
- 推荐版本号是比较特殊的几个内置变量组合而成，单独展示，默认不启用
- 新增/编辑变量时，侧滑打开界面，详见issue #8185

5、若当前tab 内容有变更，尚未保存时切换到其他配置 tab，则在 tab 标题增加修改过的提示
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209075200-be8487b7-7440-4cc7-b78c-9c96abf53fe9.png">

6、通知页面如下：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209076125-c18612b4-4654-4191-b4c6-36b2c42e8ea5.png">
- 构建成功/失败时，都可以添加多个通知
- 新增/修改通知界面如下：
  - 当不需要发送群消息时
    <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209077042-13442ac3-5c34-4b8c-b7f8-a74dd0e4a66b.png">
  - 当需要发送群消息时，增加 群ID 和 是否 Markdown 的 选项：
    <img width="300" alt="image" src="https://user-images.githubusercontent.com/54432927/209077168-e4cddb4f-2f3f-48ea-9435-be764a84c845.png">

7、设置页面如下：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209077506-a9e7cdd1-f37d-4fdd-8e21-2825b121eadf.png">
- 设置下包括「基础信息」和「执行设置」
  - 现网基础设置下的徽章，入口迁移，见 issue #8187  
- 基础信息包括：流水线名称、标签、描述
- 执行设置包括：自定义构建号 和 并发设置

8、调试好流水线，点击「发布」后
- 若未开启 PAC，和 Code 方式编辑完成提交一样，见 #8125 
- 若已开启 PAC，增加预览 YAML 入口，点击后侧滑打开 YAML 查看界面
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209079220-5c1db5a3-e5d0-4f67-9a76-40dd386cf438.png">
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209079531-11f2db6b-c0a1-4eff-b857-7f7fb902a627.png">

**Comment by EchoQT** [comment]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/108731654/209765477-a4c4657b-4e2a-429f-a568-31c2dd772144.png">

普通通知人和群通知ID为何中间隔着通知内容？这排版有点奇怪。

**Comment by EchoQT** [comment]
<img width="518" alt="image" src="https://user-images.githubusercontent.com/108731654/209765875-0cc2b1c1-7760-4676-92c5-f8f5e5f78884.png">
<img width="570" alt="image" src="https://user-images.githubusercontent.com/108731654/209766041-b3ddaf56-8b6f-4db6-8b6c-980e0a650bd0.png">

这两个地方的构建号设置是不是合并一下比较好？

**Comment by EchoQT** [comment]
预览yaml好像可以去掉？
用户本来就可以随时切换yaml方式查看和编辑，而且当用户更习惯于UI方式的时候，发布时提供预览yaml的目的是什么呢？

**Comment by fayewong-v5** [comment]
done
