### ISSUE TITLE
【蓝盾-需评审】【PAC】perf：手动执行流水线交互优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8168]
【需求】
1、手动执行流水线时，先进入入参填写界面：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/210481844-c2e103b9-2ad3-4f0b-9289-b7ec4ec98234.png">
- 进入页面时填充变量的默认值
    - [ ] #11025

    <img width="200" alt="image" src="https://user-images.githubusercontent.com/54432927/209086799-89d0eeb8-5932-4b63-a786-37a67ba75aba.png">
- 可以一键填入上一次执行时使用的入参
  - 若填入参数时，发现有变更，则提示用户
    <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/210499196-44186d49-b9eb-4d95-889d-19df31ae03e9.png">
  - 用户可能在进入执行页面后手动修改了个别入参，再一键填入；也可能未做修改直接一键填入。变更指的是和当前页面上的内容相比

2、填写好参数后点击「下一步」，进入步骤选择页面：
- 若手动触发上勾选了「手动触发执行时可跳过插件」，则可以选择本次运行的步骤。若未勾选，则不能选择。（现网已有逻辑，暂时不变更）
- 若用户仅勾选部分步骤运行，埋点记录，作为后续是否支持执行方案的参考。记录如下信息：
  - 流水线
  - 操作人
  - 流水线版本
  - 当前选中的步骤集合：用于评估是否有规律

3、启动运行，提交成功后跳转到运行详情页面，见 #7983 
- 若提交不成功，弹框展示提交失败原因

**Comment by EchoQT** [comment]
复用上一次入参的玩法，还需要进一步明确规则。
上一次执行有可能是其他人手动执行的、或是非手动执行的，等等。

**Comment by EchoQT** [comment]
<img width="366" alt="image" src="https://user-images.githubusercontent.com/108731654/209761051-89b9bcee-dbf8-4ab8-a383-2ab9db23baa9.png">
这个提示有必要吗？纯手动填写参数的情况下也会提示给用户哪些和默认值不一致吗？

**Comment by fayewong-v5** [comment]
除了必填有默认值场景，其他功能done
