### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：支持回滚到历史版本

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8172]
【需求】
从两个入口可以进行回滚操作：
- 编辑流水线界面切换到历史版本，见 #8173
- 流水线查看页面，版本列表，见 #8195 

1、点击「回滚到此版本」后：
- 若已存在草稿版本，则提示用户是否覆盖草稿
- 若确定覆盖或原本无草稿，进入编辑页面
- 将选中版本的内容加载到编辑页面

2、可以直接保存草稿 or 修改后保存草稿、进行调试、发布一个新版本

**Comment by EchoQT** [comment]
ok。
所以看起来，PAC模式下的回滚操作，用户不需要走分支提交了，系统直接把草稿升级为正式版本了对吧？

**Comment by fayewong-v5** [comment]
Done
