### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：编辑流水线时支持查看版本列表

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8173]
【需求】
1、流水线编辑页面，可下拉出历史版本列表
<img width="250" alt="image" src="https://user-images.githubusercontent.com/54432927/208688220-bddef1bc-cf42-4091-a88a-837ec5740d12.png">

2、列表根据版本的最近修改时间逆序排列

3、从草稿版本切换到其他版本时，若尚未保存变更，则提示用户保存
<img width="150" alt="image" src="https://user-images.githubusercontent.com/54432927/208692111-344c2394-d1e5-4237-a2f5-c3ec9771ceef.png">

4、切换到历史的正式版本时
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/208692379-91ed64fe-5fa7-46cb-9114-279f07f38128.png">
- 代码编辑框只读
- 支持「回滚到此版本」操作，操作详见 #8172 

5、切换到分支版本时
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/208692977-814c7ecd-cf35-47a2-a520-8e50091e6dfd.png">
- 代码编辑框只读
- 支持「调试」操作，操作详见 #8164 
  - 去调试时，若已存在草稿版本，则提示：
    <img width="219" alt="image" src="https://user-images.githubusercontent.com/54432927/208693724-e7af5274-c6ce-4964-ba29-7e4ef119d982.png">

**Comment by EchoQT** [comment]
ok

**Comment by fayewong-v5** [comment]
3.0已实现
