### ISSUE TITLE
【蓝盾-需评审】【PAC】feat：PAC模式下的流水线触发器支持省略配置

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8184]
【背景】
目前 stream 下，支持省略触发器 on 配置，省略后默认有如下 4 个触发器
<img width="300" alt="image" src="https://user-images.githubusercontent.com/54432927/209105640-ed8a57ae-2fc1-41ff-b894-e5f588f5b4db.png">
省略的目的是简化用户配置
将 stream 功能和蓝盾融合时，需要兼容此特性

【需求】
1、当 YAML 文件中省略了 on 关键字时，保存后自动生成以上 4 个默认触发器
- 在 UI 方式查看触发器时，可以查看到，提示 “YAML 文件缺省触发器 on 配置，默认监听”
- 在 Code 方式查看时，查看用户原本的配置文件，还是省略 on 的 

2、当在 UI方式 编辑/删除 此类默认触发器后，生成的 YAML 里自动加上对应的 on 配置

**Comment by EchoQT** [comment]
ok。
另外，用户输入on:时也是会自动联想这段结构的，对吧。

**Comment by fayewong-v5** [comment]
Done
