### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】perf：流水线运行状态徽章交互优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8187]
【背景】
现网徽章在流水线设置界面才展示，隐藏太深，很多用户不知道有这个功能

【需求】
1、去掉流水线设置页面的徽章，改为流水线详情页面展示：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209080647-b5cbc7b1-ab79-42fa-87c2-3a8cb136fa01.png">

2、徽章展示最近一次运行完成的流水线状态
<img width="89" alt="image" src="https://user-images.githubusercontent.com/54432927/209081544-6a422430-e942-4a01-ba1f-e893a5a173a7.png">

3、点击徽章打开操作
- 复制 Markdown 链接，点击后复制链接到剪贴板
  - 提示icon，hover展示：可将徽章链接添加到代码库 README.md 中，便于项目组成员快速关注流水线信息
- 复制图片链接，点击后复制链接到剪贴板

**Comment by EchoQT** [comment]
ok

**Comment by fayewong-v5** [comment]
Done
