### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】perf：手动触发器配置优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8188]
【需求】
1、“手动触发执行时使用最近一次构建参数值” 功能已经在调试和运行界面提供入口，去掉此配置
2、“手动触发执行时可跳过插件”，去掉此配置
- 调试流水线时，都可以选择当前次运行哪些插件
- 执行流水线时，不再提供选择插件功能，详见 #8168 

注意：
- 存量流水线已开启“手动触发执行时可跳过插件”保持功能不变，仅对新流水线生效

**Comment by EchoQT** [comment]
ok

**Comment by fayewong-v5** [comment]
保留配置，不挑战用户使用习惯。
