### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】perf：禁用流水线功能优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8190]
【需求】

1、禁用/启用操作入口有：
- 流水线列表页，流水线行的「更多操作」
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209258020-3c2e7eef-8c08-473f-a31a-9ab36c830329.png">
- 流水线详情页，右上角的「更多操作」
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209257852-3a6a1bca-18e5-47e6-bbbc-5144eb6d0e9c.png">
- 去掉基础设置中的禁用入口
  <img width="500" alt="image" src="https://user-images.githubusercontent.com/54432927/209258189-fcf03cfe-335c-416e-b1b1-5c33cc182b11.png">

2、非 PAC 模式下，禁用流水线时提示用户：
<img width="300" alt="image" src="https://user-images.githubusercontent.com/54432927/209258358-d9c25cc8-c5db-4f42-89a1-454f13d7b199.png">

3、PAC 默认下，不支持直接禁用流水线，需要在 YAML 文件中增加禁用配置
<img width="300" alt="image" src="https://user-images.githubusercontent.com/54432927/209258511-78e6c1ac-2c68-42cf-8f43-94c4a09d90fd.png">

- 关键字为 pipeline ，配置示例：
```
pipeline: disabled
```
- 没有关键字 pipeline 或者 pipeline: enabled 时，流水线为启用状态
- 只有部分分支有禁用配置时，仅对应分支的提交不触发
- 当流水线最新的正式版，以及当前的分支版本都禁用后，流水线才显示禁用状态

3、禁用后的流水线
- 列表页：
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209259124-59124571-78a6-4484-ae86-5333dcdcad39.png">
- 查看页：
  - 执行按钮不可用，hover 提示流水线已禁用

**Comment by EchoQT** [comment]
当流水线最新的正式版，以及当前的分支版本都禁用后，流水线才显示禁用状态

-----PAC模式下删除流水线操作就可以给类似的说明。
-----另外，在部分分支禁用或删除该文件的情况下，该文件在蓝盾流水线列表界面上是否可以有一个特殊的状态标识？
