### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】perf：流水线查看-执行历史展示优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8192]
【需求】
1、默认的列表展示字段如下所示
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209494264-b8bd7b7a-37ca-4db8-bc58-eab3333676ce.png">
- 和现网默认字段相比，设计稿少画了「流水线版本号」、「备注」、「错误码」三个字段 --- 这三个字段保留
  - 当相邻的两次运行之间，流水线版本号变更时，提示流水线版本号已变更（已有功能），根据版本号规则细化提示内容：
    - 流水线编排已变更
    - 流水线触发器已变更
    - 流水线设置、通知、或名称等已变更 
- 新增「耗时」字段，展示流水线对应次构建耗时

2、表格内源材料最多展示三行，超过3行时，出现…，源材料点击后展示如下
<img width="250" alt="image" src="https://user-images.githubusercontent.com/54432927/209494696-f34408cf-91b8-485f-a85c-f0acf00102ea.png">
- 每行源材料后的数表示「当前源材料拉取了几次」

3、有制品生成时，点击制品个数展示：
<img width="250" alt="image" src="https://user-images.githubusercontent.com/54432927/209494935-49661990-fac7-4750-9592-27b3ca966029.png">
- 「查看制品详情」：跳转到对应的构建详情页面，产出物 tab，选中「制品」
- 流水线仓库的制品，「复制至」操作交互和构建详情页面的构建操作一致，详见 #8199

4、有制品生成时，可以点击二维码打开：
<img width="99" alt="image" src="https://user-images.githubusercontent.com/54432927/209495389-7b77f052-447d-44b5-8a78-bb3d9c795075.png">
- 扫描二维码将唤起蓝盾APP，跳转到对应的构建详情页面展示构件列表

5、错误详情展示如下：
<img width="150" alt="image" src="https://user-images.githubusercontent.com/54432927/209495608-4bce369e-e5a9-462b-8791-dad8e6513539.png">
- 表格内最多展示 3 行
- 点击错误码详情图标，展示详情
<img width="300" alt="image" src="https://user-images.githubusercontent.com/54432927/209495705-e759da84-e753-4821-b736-a4a735bcccc7.png">

6、备注展示如下：
<img width="200" alt="image" src="https://user-images.githubusercontent.com/54432927/209495778-9fa53552-9bec-423b-b925-acf7686e1a67.png">
- 表格内最多展示三行
- 点击编辑备注
<img width="200" alt="image" src="https://user-images.githubusercontent.com/54432927/209495841-3b5ecf5b-0843-4518-8610-cdaba80d012d.png">
- 备注内容可点击，点击后弹框展示全部备注，和错误详情展示类似

**Comment by EchoQT** [comment]
ok

**Comment by fayewong-v5** [comment]
3.0 版本已实现
