### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：流水线查看-支持查看触发事件

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8193]
【需求】
1、支持流水线维度查看触发事件以及触发结果：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209493652-6061241f-73c5-4ed2-85f4-953900fe4661.png">

2、事件信息和代码库维度查看保持一致，详见 #8122

3、重新触发详见 #8124

4、支持根据如下条件查询事件：
- 触发时间段
- 触发器类型
- 事件类型
- 触发人

**Comment by EchoQT** [comment]
ok
