### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：查看流水线

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8195]
【需求】
1、进入查看页入口：
- 流水线列表，点击 流水线名称 进入
- 流水线详情页面，点击面包屑上的 流水线名称 进入

2、查看页，顶部导航如下
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209264024-56f9e6d4-1021-4847-bc81-a2a54bb1e657.png">
- 面包屑上，点击 「流水线」到达流水线列表界面
- 流水线名称后展示是否开启 PAC 标识：
  - 若已开启：
    - 高亮
    - 点击展示对应的代码库 和 YAML 路径
      <img width="200" alt="image" src="https://user-images.githubusercontent.com/54432927/209264574-40037f55-e429-404d-bb6b-dc19c6d83237.png">
    - YAML 路径后的 入口点击可在新 tab 打开代码库查看文件页面：
      - 若默认分支已有此文件，跳转到默认分支
      - 若尚未发布到默认分支，跳转到最新的分支版本对应的分支 
  - 若未开启：
    - 灰色
    - 点击提示：尚未开启 PAC 默认，了解更多
- PAC 标识后展示流水线徽章，详见 issue #8187 
- 右侧根据工作区内容展示对应的主操作
- 更多操作包括：
  <img width="80" alt="image" src="https://user-images.githubusercontent.com/54432927/209265290-00f27bc3-2a24-4873-850e-5d4a2348f62e.png">

3、进入查看页，默认展示「执行历史」列表
- 若无任何执行历史：
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209265461-660b30d4-d221-4589-aa63-936ed965fd86.png">
- 执行历史列表展示优化见 issue #8192

4、新增当前流水线「触发事件」列表，详见 issue #8193

5、新增当前流水线「产出物」列表，详见 issue #8194

6、流水线配置-流水线编排界面：
- 当开启了 PAC 默认的流水线未提交到默认分支时
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209268963-b942fd16-d3d7-41f3-9423-e89f38763332.png">
  - 提示尚未提交
  - 提示流水线配置生效规则，具体的生效规则以 #8125 为准
- 支持 UI 方式查看
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209269268-7164b9f3-9a63-40f4-9a95-70db0f95ee3a.png">
  - 默认 UI or Code 由用户偏好决定
  - stage/job/task等点击侧滑展示配置详情
  - 变量名点击侧滑展示变量定义
  - 变量区域可以收起/展开
- 支持 Code 方式查看
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209269607-b588fe02-d6f0-49d0-b47f-1cac820c8ef3.png">
  - 高亮编排区域
  - 若有分支版本，提示用户尚未合入

7、流水线配置-触发器页面：
- 支持 Code 方式 查看
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209269785-fcce11f8-ae28-42dd-bb51-df5cefd6caa3.png">
  - 打开 YAML 文件，高亮触发器配置
  - 当有分支版本时，和编排类似，提示分支尚未合入
- 支持 UI 方式查看
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209270018-232c75ae-9eb6-436f-b8f0-49bd17d43451.png">

8、流水线配置-通知配置，支持 Code 和 UI 方式查看，和触发器查看类似，详见设计稿

9、流水线配置-基础设置，支持 Code 和 UI 方式查看，和触发器查看类似，详见设计稿

10、更多-权限设置，见权限中心升级v3

11、更多-版本历史：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209286930-062c5949-01d9-4640-b894-d9c0b9bf4da8.png">
- 草稿版本，可以编辑
- 分支版本，可以去调试（生成草稿并调试）
- 可以回滚到历史的正式版本
- 所有版本都可以点击进行版本对比，详见issue #8196

12、更多-操作历史：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209289264-62145e87-f0c2-4c63-ba6a-c6003bc8c726.png">
- 需要记录操作日志的操作，详见 issue #8197
- 可以根据操作人/操作时间查询日志

**Comment by EchoQT** [comment]
<img width="651" alt="image" src="https://user-images.githubusercontent.com/108731654/209755173-0095f13a-2995-40b1-ae45-fc4de8ca3e24.png">
这个图不知道能不能看到，说明上可以再优化一下，最好先说清楚在蓝盾里默认分支的默认逻辑，再说一些特殊情况下使用触发分支。

**Comment by EchoQT** [comment]
分支版本，可以去调试（生成草稿并调试）

-----此种情况，有草稿也有分支，那么，调试完成后提交版本的路径是怎样的，是必须通过分支路径（现在的离线提交方式）去提交，还是也可以通过草稿直接提交版本（现在的蓝盾方式）？
