### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：流水线支持查看版本对比

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8196]
【需求】
点击版本对比，打开对比界面
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209298064-a7b38def-0993-4ede-b78f-6ed9f23b695d.png">
- 一期仅支持 Code 方式对比
- 左侧为点击「版本对比」按钮时所在的版本
- 右侧默认为「当前正式版本」
  - 若左侧也为当前正式版本，则右侧为空
- 右侧可以切换到其他版本
- 流水线变更示意，和代码库查看文件变更类似

**Comment by EchoQT** [comment]
左侧右侧都可以有默认版本逻辑，但弹出后都可以切换，不做锁定的逻辑。
其他ok

**Comment by fayewong-v5** [comment]
Done
