### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：二进制制品复制到自定义仓库交互优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8199]
【背景】
现网另存到自定义仓库时，另存到了一个固定的路径下，路径规则：自定义仓库/_from_pipeline/{流水线名称}/{buildNo}/
<img width="150" alt="image" src="https://user-images.githubusercontent.com/54432927/209491819-b7829175-6e85-41c4-ba0a-068b0d0e0286.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/209491952-4cb85a0e-1ac1-4b9f-9699-f7778766f44e.png">

这种方式下：
- 用户不知道另存的目的地在哪，需要去制品库查看才知道
- 用户不能选择目的地

【需求】
1、支持用户选择复制的目的地
<img width="500" alt="image" src="https://user-images.githubusercontent.com/54432927/209492796-ec87e68c-5e68-4001-9037-d4c17305ed0c.png">
- 可以搜索目标目录
- 搜索到的目录平铺展示

2、复制后有去制品库查看的入口
<img width="300" alt="image" src="https://user-images.githubusercontent.com/54432927/209492828-885c64db-a949-4bf0-9d82-d03eef24a4dd.png">

**Comment by EchoQT** [comment]
ok

**Comment by fayewong-v5** [comment]
Done
