### ISSUE TITLE
【蓝盾-评审会已评审】feat：repo-hook 监听凭据支持 OAUTH token

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8216]
【背景】
X 部门在 stream 上封装了自己的平台 A，给他们部门的业务提供 CI/CD 标准化服务。
底层使用 stream  repo-hook 功能来实现在一个公共仓库下管理一批业务仓库流水线的功能。
目前 repo-hook 的鉴权仅支持工蜂的 personal access token，希望支持 OAUTH token。用户在使用平台 A 时，对 A 平台进行了 OAUTH 授权，A 平台在调用 Stream 服务时，使用此授权进行鉴权

【需求】
1、凭据管理新增凭据类型 “OAUTH Token”，支持用户/openapi新增 OAUTH 类型的 token （当前场景下是由平台A通过接口创建凭据）
2、repo-hook 的 credentials 凭据，鉴权时支持此类型的 token

**Comment by EchoQT** [comment]
ok
