### ISSUE TITLE
【蓝盾-无需评审会】perf：流水线搜索交互优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8268]
【现状】
1、聚焦搜索框
2、选择查询条件
3、输入内容
4、回车搜索

【问题】
用户聚焦搜索框后，第一反应是输入内容，输入后回车，发现搜不了，需要删除输入的内容，再去选择查询条件，有挫败感
<img width="200" alt="image" src="https://user-images.githubusercontent.com/54432927/212821237-ddb4fba8-b190-4e06-af19-812825594f99.png">

【需求】
输入内容，回车后触发搜索，默认按照「流水线名称」搜索，类似作业平台的作业搜索：
<img width="200" alt="image" src="https://user-images.githubusercontent.com/54432927/212821213-ad696f41-dd46-42ad-85f1-8c8d79314ad6.png">

**Comment by EchoQT** [comment]
ok

**Comment by vuuv** [comment]
建议增加搜索字段： 最近修改人
