### ISSUE TITLE
fix：流水线列表最近执行人展示的内容不正确

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8285]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/215649492-2b1b3b71-8e22-45c4-844d-07a7708b1d4c.png">
图示的红框位置，展示的内容应该是触发了此流水线运行的用户（和执行历史列表、详情页展示的触发人对齐），而不是使用了谁的权限运行此流水线

**Comment by irwinsun** [comment]
PAC后已经解决
