### ISSUE TITLE
【蓝盾-无需评审会】流水线组列表按照字母序A～Z排序

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8286]
【背景】
目前流水线组列表展示如下：
<img width="120" alt="image" src="https://user-images.githubusercontent.com/54432927/215653016-b3a6ec2d-a75c-45e0-92fe-354076b52f7f.png">
存在两个问题：
1、用户添加的流水线组列表，未排序
2、添加流水线组时，默认加到列表最后，但手动刷新后位置变化
添加成功后：
<img width="150" alt="image" src="https://user-images.githubusercontent.com/54432927/215653313-8bcbf3bf-cde3-4492-97c4-6b597df09b7e.png">
手动刷新后：
<img width="150" alt="image" src="https://user-images.githubusercontent.com/54432927/215653402-7524a9bc-04b0-4139-8214-52282c8307b9.png">

【需求】
1、流水线组列表，按照字母序A～Z顺序排序
- 排序是在各小区域内，区域顺序为：
  - 系统流水线组
  - 置顶的用户流水线组
  - 非置顶的用户流水线组

2、添加流水线组成功后，自动刷新流水线组列表
- 局部刷新，比如添加了项目流水线组，则刷新「项目流水线组」列表

**Comment by EchoQT** [comment]
ok
