### ISSUE TITLE
bug：sg 环境流水线插件详细描述中上传图片502

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8320]
**What happened**:
插件详细描述中上传图片时，502
<img width="800" alt="image" src="https://user-images.githubusercontent.com/54432927/216613206-7cbad6eb-0905-458b-9a00-6e99d11b51e6.png">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- 蓝盾 sg 环境

**Comment by irwinsun** [comment]
确认fix在 issue #8292 

前端PR #8310
后端PR #8303
