### ISSUE TITLE
feat：流水线组列表支持展开/收起

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8321]
【背景】
当工作视角不是进行流水线管理，而是运行、查看流水线时，希望可以收起左侧流水线组导航，留出更多空间展示流水线

【需求】
1、左侧流水线组列表可以展开/收起
<img width="250" alt="image" src="https://user-images.githubusercontent.com/54432927/217521813-4b756a5f-8ef3-4703-85ae-127187c7a826.png">  <img width="210" alt="image" src="https://user-images.githubusercontent.com/54432927/217522176-9e7533c2-2094-4a0a-a394-e2d8a0106476.png">

2、hover 展开/收起的把手时，变蓝，详见设计稿

**Comment by EchoQT** [comment]
ok
