### ISSUE TITLE
WorkRunner类中异常不退出worker-agent

### ISSUE THREAD

**Issue by Grapefruit-Shu** [TencentBlueKing/bk-ci#8360]
bk-ci version release-1.8 和master都存在
woker-agent中有个bug
![image](https://user-images.githubusercontent.com/34914897/218427265-1a72d718-890f-47a7-877b-5059c0dd2974.png)

src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/WorkRunner.kt
这个类中有个异常 try catch 但是没有退出worker-agent，会造成worker不会退出，agent就一直存在某个build

**Comment by Grapefruit-Shu** [comment]
这里应该需要添加一个 exitProcess(-1)

**Comment by irwinsun** [comment]
不知你是否方便，可以直接提交fix pr，
需要注意 [commit信息规范](https://github.com/TencentBlueKing/bk-ci/blob/master/CONTRIBUTING.md#git%E6%8F%90%E4%BA%A4%E8%A7%84%E8%8C%83)

**Comment by Grapefruit-Shu** [comment]
好的好的，我明天提交一下

**Comment by irwinsun** [comment]
我看到你已经提交到个人Fork库中了，是否有准备提交PR到主库

**Comment by Grapefruit-Shu** [comment]
=我这边那边提交一直显示失败，都以为没提交上去。那您帮我操作下吧
