### ISSUE TITLE
stage-1排队时取消或者超时显示异常

### ISSUE THREAD

**Issue by Grapefruit-Shu** [TencentBlueKing/bk-ci#8361]
release-1.8中，当流水线构建出现排队的时候，手动取消或者等待超时，stage-1的状态依然显示running，后续的stage状态显示正常，跟踪代码逻辑发现是stage-1中不存在container的原因，后续流程流转的时候，把该stage-1 设置为了skip状态，导致后面不更新build_detail中model字段中的stage-1下面container的状态
StageControl  步骤控制器-> 流转到 CheckConditionalSkipStageCmd 这个类时，判断container为空，设置改stage为skip
![image](https://user-images.githubusercontent.com/34914897/218431202-b7632654-75dd-4827-8dbd-eaaeca39007d.png)

**Comment by irwinsun** [comment]
其实并不是container为空的问题，排队中的构建，是不会进入到ContainerControl。

取消会发BuildCancelControl事件， 而超时会发BuildEndControl事件。 都不会直接进入ContainerControl。


这个问题的根源是BaseBuildDetailService在结束时遍历detail查缺补漏时，跳过了Stage-1， 导致的。 这个问题在2022年5月修改， 可以见下面的commit，因为这边已经没有release-1.8的验证环境，欢迎你直接修复并提交，

<img width="1290" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/16686129/3cf6abf7-dce6-43a5-8327-6f969986f9b9">

https://github.com/TencentBlueKing/bk-ci/pull/6760/commits/d3a7c36da4421c0f4f6e32d407e465fc17154c58
