### ISSUE TITLE
worker-agent中 bat脚本支持编码类型当失败的时候编码设置失败

### ISSUE THREAD

**Issue by Grapefruit-Shu** [TencentBlueKing/bk-ci#8383]
perf: Windows构建机的batch脚本执行编码问题 https://github.com/TencentBlueKing/bk-ci/issues/4601

![image](https://user-images.githubusercontent.com/34914897/220227207-cde677bd-47f2-4ff6-93ce-5533166d7a28.png)
当插件报错时，输出error日志的时候，编码失效。应该在 errorStream 里面和 outputStream 一样重写 processBuffer 方法

**Comment by yongyiduan** [comment]
@Grapefruit-Shu 你好，请问你这边使用的是什么版本出现的问题？

**Comment by Grapefruit-Shu** [comment]
release-1.8分支
