### ISSUE TITLE
feat: 修改第三方构建机监控指标

### ISSUE THREAD

**Issue by tangruotian** [TencentBlueKing/bk-ci#8418]
1、使用rename修改telegraf指标上报为蓝鲸监控需要的
2、修改telegraf文件为可下发的文件

**Comment by irwinsun** [comment]
指标如下：

<html xmlns:x="tencent"><style type='text/css'></style><body>

system.cpu_summary | usage | metric | 使用率
-- | -- | -- | --
system.cpu_summary | idle | metric | 处理器空闲率
system.cpu_summary | iowait | metric | 等待IO的时间占比
system.cpu_summary | stolen | metric | 分配给虚拟机的时间占比
system.cpu_summary | system | metric | 系统程序使用占比
system.cpu_summary | user | metric | 用户程序使用占比
system.io | await | metric | 平均等待时长
system.io | svctm | metric | 平均服务时长
system.io | r_s | metric | 读次数
system.io | rkb_s | metric | 读速率
system.io | w_s | metric | 写次数
system.io | wkb_s | metric | 写速率
system.io | util | metric | IO使用率
system.io | avgrq_sz | metric | 平均数据大小
system.io | avgqu_sz | metric | 平均队列长度
system.env | uptime | metric | 启动时间
system.env | procs | metric | 进程数
system.cpu_detail | usage | metric | 单核处理器使用率
system.cpu_detail | idle | metric | 单核处理器空闲率
system.cpu_detail | iowait | metric | 单核处理器等待IO的时间占比
system.cpu_detail | stolen | metric | 单核处理器分配给虚拟机的时间占比
system.cpu_detail | system | metric | 单核处理器系统程序使用占比
system.cpu_detail | user | metric | 单核处理器用户程序使用占比
system.mem | buffer | metric | buffered大小
system.mem | cached | metric | cached大小
system.mem | free | metric | 物理内存空闲量
system.mem | total | metric | 物理内存总大小
system.mem | usable | metric | 应用程序内存可用量
system.mem | pct_usable | metric | 应用程序内存可用率
system.mem | used | metric | 应用程序内存使用量
system.mem | pct_used | metric | 应用程序内存使用占比
system.mem | psc_used | metric | 物理内存已用量
system.mem | psc_pct_used | metric | 物理内存已用占比
system.netstat | cur_tcp_closewait | metric | closewait连接数
system.netstat | cur_tcp_timewait | metric | timewait连接数
system.netstat | cur_tcp_closed | metric | closed连接数
system.netstat | cur_tcp_closing | metric | closing连接数
system.netstat | cur_tcp_estab | metric | estab连接数
system.netstat | cur_tcp_finwait1 | metric | finwait1连接数
system.netstat | cur_tcp_finwait2 | metric | finwait2连接数
system.netstat | cur_tcp_lastack | metric | lastact连接数
system.netstat | cur_tcp_listen | metric | listen连接数
system.netstat | cur_tcp_syn_recv | metric | synrecv连接数
system.netstat | cur_tcp_syn_sent | metric | synsent连接数
system.netstat | cur_udp_indatagrams | metric | udp接收包量
system.netstat | cur_udp_outdatagrams | metric | udp发送包量
system.disk | free | metric | 空闲空间大小
system.disk | total | metric | 总空间大小
system.disk | used | metric | 已用空间大小
system.disk | in_use | metric | 已用空间占比
system.net | speed_packets_recv | metric | 网卡入包量
system.net | speed_packets_sent | metric | 网卡出包量
system.net | speed_recv | metric | 网卡入流量
system.net | speed_sent | metric | 网卡出流量
  | pgid | metric | 进程组id
system.proc | ppid | metric | 父进程ID
system.proc | state | metric | 进程状态
system.proc | cpu_usage_pct | metric | CPU使用率
system.proc | mem_usage_pct | metric | 内存使用率
system.proc | fd_num | metric | 文件句柄数
system.proc | mem_res | metric | 物理内存
system.proc | mem_virt | metric | 虚拟内存
system.inode | free | metric | 可用inode数量
system.inode | total | metric | 总inode数量
system.inode | used | metric | 已用inode数量
system.inode | in_use | metric | 已用inode占比
system.swap | free | metric | SWAP空闲量
system.swap | total | metric | SWAP总量
system.swap | used | metric | SWAP已用量
system.swap | pct_used | metric | SWAP已用占比
system.proc_port | proc_exists | metric | 进程存活状态
system.proc_port | port_health | metric | 进程端口状态
uptimecheck.tcp | task_duration | metric | 耗时
uptimecheck.tcp | available | metric | 单点可用率
uptimecheck.udp | task_duration | metric | 耗时
uptimecheck.udp | available | metric | 单点可用率
uptimecheck.udp | times | metric | 重试次数
uptimecheck.http | task_duration | metric | 耗时
uptimecheck.http | available | metric | 单点可用率
uptimecheck.http | content_length | metric | 响应长度
uptimecheck.http | steps | metric | 请求步骤数
uptimecheck.heartbeat | reload | metric | 重载次数
uptimecheck.heartbeat | running_tasks | metric | 运行任务数
uptimecheck.heartbeat | success | metric | 成功事件数
uptimecheck.heartbeat | uptime | metric | 启动时间
uptimecheck.heartbeat | fail | metric | 失败事件数
uptimecheck.heartbeat | error | metric | 错误事件数
uptimecheck.heartbeat | reload_timestamp | metric | 重载时间
uptimecheck.heartbeat | loaded_tasks | metric | 历史载入任务数
system.load | load1 | metric | 1分钟平均负载
system.load | load5 | metric | 5分钟平均负载
system.load | load15 | metric | 15分钟平均负载
system.cpu_summary_cmdb_level | idle | metric |  
system.cpu_summary_cmdb_level | iowait | metric |  
system.cpu_summary_cmdb_level | stolen | metric |  
system.cpu_summary_cmdb_level | system | metric |  
system.cpu_summary_cmdb_level | usage | metric |  
system.cpu_summary_cmdb_level | user | metric |  
system.disk_cmdb_level | free | metric |  
system.disk_cmdb_level | in_use | metric |  
system.disk_cmdb_level | total | metric |  
system.disk_cmdb_level | used | metric |  
system.cpu_detail_cmdb_level | idle | metric |  
system.cpu_detail_cmdb_level | iowait | metric |  
system.cpu_detail_cmdb_level | stolen | metric |  
system.cpu_detail_cmdb_level | system | metric |  
system.cpu_detail_cmdb_level | usage | metric |  
system.cpu_detail_cmdb_level | user | metric |  
uptimecheck.icmp | avg_rtt | metric | 平均rtt
uptimecheck.icmp | available | metric | 可用率(1-loss_percent)
uptimecheck.icmp | loss_percent | metric | 丢包率
uptimecheck.icmp | max_rtt | metric | 最大rtt
uptimecheck.icmp | min_rtt | metric | 最小rtt
uptimecheck.icmp | task_duration | metric | 平均rtt(与avg_rtt相同)
system.proc | uptime | metric | 启动时间
beat_monitor.heartbeat_total | config_error_code | metric | 整体配置错误码
beat_monitor.heartbeat_total | uptime | metric | 启动时间
beat_monitor.heartbeat_total | tasks | metric | 运行任务数
beat_monitor.heartbeat_total | config_load_at | metric | 配置加载/重载时间
beat_monitor.heartbeat_total | published | metric | 数据上报数
beat_monitor.heartbeat_total | errors | metric | 采集错误数
beat_monitor.heartbeat_total | error_tasks | metric | 错误子任务数
beat_monitor.heartbeat_total | bk_biz_id | dimension | 业务ID
beat_monitor.heartbeat_total | bk_cloud_id | dimension | 云区域ID
beat_monitor.heartbeat_total | bk_supplier_id | dimension | 开发商ID
beat_monitor.heartbeat_total | ip | dimension | IP
beat_monitor.heartbeat_total | status | dimension | 状态码(目前仅为0)
beat_monitor.heartbeat_total | version | dimension | 采集器版本信息
beat_monitor.heartbeat_child | config_error_code | metric | 子配置错误码
beat_monitor.heartbeat_child | bk_biz_id | dimension | 业务ID
beat_monitor.heartbeat_child | bk_cloud_id | dimension | 云区域ID
beat_monitor.heartbeat_child | bk_supplier_id | dimension | 开发商ID
beat_monitor.heartbeat_child | ip | dimension | IP
beat_monitor.heartbeat_child | name | dimension | 采集任务名
beat_monitor.heartbeat_child | path | dimension | 采集任务配置名
beat_monitor.heartbeat_child | taskid | dimension | 任务ID
beat_monitor.heartbeat_child | version | dimension | 版本号

</body></html>
