### ISSUE TITLE
支持用户清理构建机缓存

### ISSUE THREAD

**Issue by lunaazhang** [TencentBlueKing/bk-ci#8469]
用户在执行流水线的时候，执行出现问题时，会出现定位到是缓存问题的情况。
基于以上问题，蓝盾在流水线中提供一个清理构建机缓存的接口：
1）包括公共构建机和私有构建机；
2）清理工作空间中的缓存，即代码以及编译的产物等等；
3）清理的缓存中不包括环境依赖的缓存，即构建容器拉起时部分路径的挂载。

**Comment by irwinsun** [comment]
shell插件
rm -rf ${{ci.workspace}} 
是否可以解决？


清理还是比较敏感和高危的操作， 平台无法直接控制构建机在机器上做任何的操作。 都是由构建机自下而上的请求平台获取到构建任务来执行。 所有一切只能通过流水线的任何方式运行， 因此像这类问题，只要你加一个插件，清理你想要的目录即可。
