### ISSUE TITLE
流水线名称的排序没有按a~Z，导致了中英混杂的情况

### ISSUE THREAD

**Issue by carrywang05** [TencentBlueKing/bk-ci#8508]
**What happened**:
流水线名称的排序没有按a~Z，导致了中英混杂的情况，不符合用户常识，影响了用户体验。

**What you expected to happen**:
希望流水线名称按照a~Z排序，而不是将中文名转为拼音后再进行排序。这样更符合大家的使用习惯，无论是excel，还是Github的排序都是如此。
以下为示例：
<img width="157" alt="image" src="https://user-images.githubusercontent.com/46527215/225585320-48ba5196-b927-4596-9154-45f1adeec35d.png">
<img width="190" alt="image" src="https://user-images.githubusercontent.com/46527215/225585685-36cdd487-ab8c-4f14-be37-a3d80127d09b.png">

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by irwinsun** [comment]
来源于原来社区用户贡献的开发功能：
[流水线页面 按名称A-Z 支持中文按拼音排序 #5100](https://github.com/TencentBlueKing/bk-ci/issues/5100)

特意将中文拼音化加入排序，于2021年10月份上线，并不是新特性

**Comment by irwinsun** [comment]
最终下掉按拼音排序的功能，
删除pinyinUtils和相关第三方依赖包，和相关的op刷数据接口

按PIPELINE_NAME 排序，  PINYIN字段暂时不删除，只作废
