### ISSUE TITLE
【蓝盾-评审会已评审】feat：P4事件触发支持自主选择对大小写是否敏感

### ISSUE THREAD

**Issue by lunaazhang** [TencentBlueKing/bk-ci#8540]
【背景】
由于P4服务器在unix系统上支持对大小写敏感，在windows系统上对大小写不敏感。
当用户使用的P4时设置了对大小不敏感，但是蓝盾这边监听路径对大小写敏感，就会导致有一些行为监听不到。
【需求】
支持用户可以自主选择P4触发器对大小写是否敏感
【解决方案】
由于P4用户的服务器和客户端对大小写是否敏感是保持一致的，
因此，我们在用户关联代码库的时候，提供一个‘服务器对大小写是否敏感’的选择，
后续蓝盾P4事件触发是否对大小写敏感，将于你的服务器是否对大小写敏感保持一致。
具体位置如下图（其中我们默认对大小写敏感）
![截屏2023-04-03 17 22 41](https://user-images.githubusercontent.com/125845811/229468459-99b8f132-de05-43d0-990f-52e49e5d727f.png)
注：用户已经关联好的代码库，可以通过代码库界面的编辑功能，重新设置。

**Comment by EchoQT** [comment]
界面选项上还是叫服务器吗？是不是叫服务端好些？
其他没有问题

**Comment by lunaazhang** [comment]
> 界面选项上还是叫服务器吗？是不是叫服务端好些？ 其他没有问题

服务端确实更好一些，那我这边修改一下。

**Comment by mingshewhe** [comment]
系统能够调用p4接口获取p4服务端是否大小写敏感，不需要添加新的配置
