### ISSUE TITLE
feat：关联代码库页面优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8621]
# 关联 svn 代码库页面优化：
优化前
<img width="400" alt="image" src="https://user-images.githubusercontent.com/54432927/231465930-e4a089ca-bc9a-4010-af19-530ba473569a.png">
优化后：
<img width="400" alt="image" src="https://user-images.githubusercontent.com/54432927/231466486-e0aad3e1-0a11-4261-96bf-891d51648d1e.png">

1.「linkSVNCode Repositories」更新为「Link SVN Code Repository」
2.「源代码拉取方式」选项前空白太多，应减少至如图所示
3. 「HTTP」修改为「HTTP/HTTPS」
4. 「URL」修改为 「Address」
5.  placeholder应为：「please enter SVN address」
6.  增加示例

# 关联 github/gitlab/TGit/Perforce 代码库页面优化
1. 「linkGithub Code Repositories」更新为「Link Github Code Repository」
2. 「linkTGitCode Code Repositories」更新为「Link TGit Code Repository」
3. 「linkP4Code Code Repositories」更新为「Link Perforce Code Repository」
4. 「linkGitlabCode Code Repositories」更新为「Link Gitlab Code Repository」

**Comment by fabio-he** [comment]
![image](https://user-images.githubusercontent.com/56472792/234485236-8b5af974-d339-49c9-98d1-7282861445a8.png)
「linkSVNCode Repositories」更新为「Link SVN Code Repository」 其它代码库也漏了code
