### ISSUE TITLE
feat：新增环境页面优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8622]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/231472255-c32e5315-be41-4e7d-8269-684021c22414.png">

1. New Pool
2. 「remark」修改为「Description」
3. 隐藏「Type」行
4. 隐藏「self-hosted agent」的单选

**Comment by fabio-he** [comment]
![image](https://user-images.githubusercontent.com/56472792/234461188-9dd70e71-137e-4882-ab1f-6dd4994bb06a.png)
