### ISSUE TITLE
perf：metrics 服务小优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8623]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/231481147-9d69860b-60c4-43e0-949c-cc646b6e735c.png">

1. 切换项目时，metrics 相关的页面没有刷新数据
2. 「无数据」未翻译，「No Data」

**Comment by fabio-he** [comment]
![image](https://user-images.githubusercontent.com/56472792/234484262-31579aae-1ecb-4767-aefc-545de45a200b.png)
「linkSVNCode Repositories」更新为「Link SVN Code Repository」 其它代码库关联界面的title也漏了code

**Comment by vhwweng** [comment]
![image](https://user-images.githubusercontent.com/67886588/234501735-d608d3a9-6738-4402-8485-45831847c37a.png)

**Comment by vhwweng** [comment]
![Uploading image.png…]()

**Comment by vhwweng** [comment]
![image](https://user-images.githubusercontent.com/67886588/234501906-52e0ae89-93ec-40b7-beb2-29ebd7efa2b5.png)

**Comment by fabio-he** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
