### ISSUE TITLE
期望提供归档功能

### ISSUE THREAD

**Issue by hello-soon** [TencentBlueKing/bk-ci#866]
为发布创建一个流水线，版本发布后，期望能归档。
1，不在常规流水线面板显示。
2，有归档流水线面板可以查看，搜索，和恢复（发补丁需要）

其主要目的是保存当时版本所填写的流水线参数，编译参数，渠道，等等。

**Comment by iccengan** [comment]
#1120 是否能满足你的需求？

**Comment by zanyzhao** [comment]
> #1120 是否能满足你的需求？

看起来不行，用户希望长时间隐藏一种流水线，在需要的时候恢复

**Comment by soongao** [comment]
> > #1120 是否能满足你的需求？
> 
> 看起来不行，用户希望长时间隐藏一种流水线，在需要的时候恢复

对。目的是归档。 某某发布的版本，有对应已经归档的流水线。

**Comment by irwinsun** [comment]
将某条执行历史归档到另外一个位置， 而执行历史数据目前是有过期允许被清除， 归档数据则会有一些永久或者保留期限？

**Comment by irwinsun** [comment]
此需求由 #9397 实现
