### ISSUE TITLE
Goagent版本优化

### ISSUE THREAD

**Issue by tangruotian** [TencentBlueKing/bk-ci#8671]
goagent版本升级到19之后出现了和centos7系统库不兼荣，如ulimit命令非root权限不可使用

**Comment by irwinsun** [comment]
https://github.com/influxdata/telegraf/issues/12502
https://github.com/awnumar/memguard/issues/144

**Comment by irwinsun** [comment]
另一个问题是因为进程的 max core file size 受到 memguard  init 影响，设置为0， 导致构建过程中 尝试修改ulimit 会报错。
