### ISSUE TITLE
【蓝盾-无需评审会】feat：子流水线调用触发的运行，触发材料显示父流水线

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8682]
**【背景】**
目前由「子流水线调用」插件触发的子流水线执行详情界面，不方便回溯父流水线

**【需求】**

<img width="700" alt="image" src="https://user-images.githubusercontent.com/54432927/233073115-b0cca016-c545-4b0f-82d9-a1d46243654a.png">

当由子流水线调用触发时：
- 触发方式为「子流水线调用」
- 触发材料为：父流水线名称 + 对应的构建号
  - 点击构建号可在新 tab 页中打开父流水线对应的构建详情界面
  - #9733

**Comment by fayewong-v5** [comment]
预审结论：可以支持
- 查看父流水线时，可以自动定位到对应的步骤，并打开日志侧滑框 --- 已补充到需求描述
- 其他场景：
  - 比如 openapi 触发时，可以让调用方传入一个链接（以便于用户能通过这个链接回到触发源） --- 单独需求支持
  - 代码库触发时展示的触发材料逐步补齐，比如 Git 触发相关材料在 #8233 下支持
  <img width="350" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/9f1f5a81-1537-45a1-99c5-e9329b2407ac">

**Comment by EchoQT** [comment]
ok
