### ISSUE TITLE
feat：流水线国际化相关优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8683]
- 批量管理：Bulk Operations
- 回收站修改为：recycle bin
  <img width="210" alt="image" src="https://user-images.githubusercontent.com/54432927/233101830-435148e6-28db-457d-83bc-1a2038e6f532.png">
- 少了空格
  <img width="190" alt="image" src="https://user-images.githubusercontent.com/54432927/233102184-666699ca-980c-4af9-80ac-d3174516a51b.png">
- 权限申请页面： Execute   PIPELINE
  <img width="403" alt="image" src="https://user-images.githubusercontent.com/54432927/233102443-0ce042d1-785e-416d-a84c-fc017fe23fe4.png">
- 输出参数前缀提示：Deprecated. Please use Step ID to set the namespace of plugin fields and access them through context.
  <img width="567" alt="image" src="https://user-images.githubusercontent.com/54432927/233102858-b76bcf6e-8a20-4806-9ccd-521e6f56ae95.png">
- 内置参数：
  <img width="410" alt="image" src="https://user-images.githubusercontent.com/54432927/233105257-718f08ed-740a-4f7d-a393-81abca615538.png">
  - BK_CI_START_USER_NAME：Triggering user
  - BK_CI_START_TYPE：Triggering type
  - BK_CI_BUILD_NUM：Build Number (an identifier assigned to the current build, starting from 1 and incrementing by 1)
  - BK_CI_PROJECT_NAME：Project identifier in English
  - BK_CI_PIPELINE_ID：Pipeline ID
  - BK_CI_PIPELINE_NAME：Pipeline Name
  - BK_CI_BUILD_ID：Current build ID of the pipeline, 34 characters in length and globally unique.
  - BK_CI_BUILD_JOB_ID：Current Job ID, 34 characters in length and globally unique.
  - BK_CI_BUILD_TASK_ID：Current Task ID, 34 characters in length and globally unique.
- 暂无代码变更记录：No code changes compared to the last run
- 流水线执行成功状态：Succeed
  <img width="168" alt="image" src="https://user-images.githubusercontent.com/54432927/233283415-99dff9c5-1639-4253-b29c-7bd577a65563.png">
- 流水线未保存时离开的提示：Please save the pipeline before exiting, otherwise all changes will be lost.
  <img width="200" alt="image" src="https://user-images.githubusercontent.com/54432927/233284100-25b44cc3-66ad-4c34-b6c2-ef7cfa879e84.png">
- 回收站中的删除人：Deleted by
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/233627940-645ee7b5-91cf-4165-bf49-f70a2f0bab21.png">

**Comment by fabio-he** [comment]
流水线执行成功状态：Succeed

![image](https://github.com/TencentBlueKing/bk-ci/assets/56472792/7d686bc8-2b68-4979-84bb-cb24802c762e)

**Comment by fabio-he** [comment]
内置参数：
![image](https://github.com/TencentBlueKing/bk-ci/assets/56472792/0a601634-882c-493c-9481-1444ed4e0ed9)

**Comment by fabio-he** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
