### ISSUE TITLE
【蓝盾-无需评审会】feat：支持开通蓝盾项目权限的同时开通对应的监控空间权限

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8935]
## 背景和问题
蓝盾的构建机基础性能监控（CPU/内存使用率、磁盘/网络IO）数据，将上报至对应的监控空间下，复用监控平台的报表和告警功能。
目前用户的操作是割裂的，需要手动到监控平台创建对应的监控空间，并进行相应的权限管理，比较麻烦。希望能自动初始化对应的监控空间，并根据构建机管理和使用权限，默认开通对应空间权限。

### 1、蓝盾系统在成功创建蓝盾项目时，需要：
  - 自动创建对应的蓝鲸监控平台研发空间
     <img width="200" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/032d19dc-b78e-4829-9b3d-706b5e92e55e">

- 注册蓝盾权限模型到 IAM 时，需同时关联蓝鲸“监控平台”，使得蓝盾用户组中可以添加监控平台相关操作
<img width="800" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/f38c1708-f952-4951-9a3e-f20fe75a9c97">

### 2、默认的蓝盾项目级用户组中：
- 管理员、运维人员组，默认拥有监控平台“业务运维”操作集合的所有操作权限
  - 即目前 IAM 中监控平台下除了「全局」之外的所有操作
  <img width="200" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/d72a8e3e-ca44-4296-883d-4260f9d02a14">

- 其他组（开发人员、产品人员、质管人员、测试人员、访客），默认拥有监控平台“业务查看”操作集合的所有操作权限
  - 即目前 IAM 中监控平台下除了「全局」之外、操作名称中不带「管理」的所有操作
    <img width="200" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/d1a23159-8ef0-4412-9eb9-20ad23e03855">

### 4、是否自动创建对应的监控空间并注册监控权限，由当前环境是否部署了监控平台服务决定
- 若当前环境未部署监控平台相关服务，不进行对应的操作

### 5、存量项目处理策略
- 最近一年活跃的蓝盾项目，自动初始化对应的监控空间，生成默认的权限数据

**Comment by EchoQT** [comment]
IAM需支持：
1、更强的角色概念：角色定义=操作组合，从现在的权限模板升级而来即可。可以考虑每个角色都限定某一种资源类型的操作组合（可跨系统组合），更便于所有角色的组织、消费和管理
2、对CI这种权限托管模式，提供角色修改的管理员功能，开发不要把蓝盾的角色需求写死在代码里，和普通权限模式的角色管理方式保持基本一致

faye和edwin有需要找我当面讨论吧
