### ISSUE TITLE
bug: Job运行状态问题修复

### ISSUE THREAD

**Issue by royalhuang** [TencentBlueKing/bk-ci#8942]
1. stage配置的fastKill对互斥中的job无效
<img width="534" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/58923885/f3a30f6f-ca41-4d06-9e6f-8701c7295ce7">

2. job启动失败时以FAILED状态作为结束
<img width="742" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/58923885/5f7c32d1-2c28-4f57-a81d-d8d6628f1609">

3. 增加job级别失败的错误码信息：如工作空间加载异常而取消，需要提供日志提示

**Comment by irwinsun** [comment]
![Uploading image.png…]()
