### ISSUE TITLE
怎么启动辅助容器

### ISSUE THREAD

**Issue by Wondershare2023** [TencentBlueKing/bk-ci#9016]
你好，我有一个问题需要咨询，我用蓝盾构建了一个web后端应用，构建完之后需要运行起来做一些测试，这时就需要启动一个辅助的数据库容器，保证我的应用能正常运行起来，请问该怎样启动这个辅助容器。

**Comment by fayewong-v5** [comment]
> 你好，我有一个问题需要咨询，我用蓝盾构建了一个web后端应用，构建完之后需要运行起来做一些测试，这时就需要启动一个辅助的数据库容器，保证我的应用能正常运行起来，请问该怎样启动这个辅助容器。

是私有化部署的蓝盾吗，部署的是哪个版本

**Comment by irwinsun** [comment]
如果是私有化部署的版本，可以参考安装这个插件，在【Docker公共构建机】 构建资源下可以拉起一个mysql数据库容器 https://github.com/TencentBlueKing/ci-mysqlservice

而如果是腾讯内，也有上架相应的插件，自行在研发商店搜索MySQL
