### ISSUE TITLE
ui text wrong in en system

### ISSUE THREAD

**Issue by Yuandiaodiaodiao** [TencentBlueKing/bk-ci#9017]
**What happened**:
<img width="264" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/33371662/71bdc1e2-e1f1-4e67-aa46-6cba59ba64f2">
pipline template
<img width="172" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/33371662/c71360f2-06c2-4620-9f7e-d165441373b6">

**What you expected to happen**:
bk.dialog  is not expected?

**Environment**:
- bk-ci version  unknown i access bk in tencent
- Cloud provider or hardware configuration: macos14 en
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by irwinsun** [comment]
look like missing i18n cfg bug

@lockiechen
