### ISSUE TITLE
【蓝盾-评审会已评审】feat：流水线支持归档目录

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#9320]
【需求背景】
PC 应用UE4构建工程生成结果不是单个文件，是一个目录（目录下有很多文件、有多级目录），在开发过程中希望支持归档目录，并且能下载整个目录，方便开发同学下载制品进行自测

【需求】
1、归档构件插件，支持归档目录
<img width="200" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/5ef1c4a9-fb41-40fe-bb36-837095eb1145">
- 配置流水线时，支持指定归档的目录
- 仅支持归档单个目录，目录下不超过 500 个文件
- 归档后，保持目录原来的结构。父目录延续原来流水线仓库和自定义仓库的设计

2、归档后，制品Tab，支持下载归档后的目录、支持展示目录概览
<img width="800" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/f6355bc3-d0b0-4a93-b83b-c5390f90e2ed">
- 可以下载整个目录
- 右侧展示目录信息概览，包括目录下的所有文件大小、文件个数、目录个数
- 当需要查看目录下的层级和具体文件时，可以“去制品库”查看

**Comment by EchoQT** [comment]
ok
