### ISSUE TITLE
bug: 引擎重试变量被用户修改导致运行时异常

### ISSUE THREAD

**Issue by royalhuang** [TencentBlueKing/bk-ci#9341]
<img width="1408" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/58923885/b47432d2-107a-49b6-ad7d-d46037b05114">

<img width="862" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/58923885/ad45c101-0a8d-40e5-bb7c-5c501963e1d8">

**Comment by irwinsun** [comment]
该问题是因为用户对 系统内置只读变量 进行修改或依赖导致出错，可以自行规避。 但

根据PAC 3.0大版本，由 #10576 决定是否启用 【内置只读变量覆盖】 进行报错，还是只告警。
用户根据自身需要去决定是不是继续这么操作
