### ISSUE TITLE
feat：完善权限申请单内容

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#9394]
**背景**
目前权限申请单界面展示的内容太简单，缺少申请的目标信息，如所属项目、哪条流水线、哪个代码库

**需求**
1、希望权限审批单中能展示如下信息：
<img width="600" alt="企业微信截图_c0ce4e06-154d-4e92-897d-2b78a433e5a0" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/1d5c228f-c618-4175-8530-c3ba46cbeb58">
- 资源名称可能有链接，也可能没有，有链接时，点击在新tab中打开资源详情，比如流水线查看页面
- 用户组，可点击，点击侧滑打开，页面中展示用户组下的操作、以及操作对象

2、希望权限审批提醒，如企业微信提醒中，也带上所属项目、资源名称

**Comment by fabio-he** [comment]
#9453
