### ISSUE TITLE
new project  show PROCESS has no dataSource available 

### ISSUE THREAD

**Issue by linpanru** [TencentBlueKing/bk-ci#9516]
![image](https://github.com/TencentBlueKing/bk-ci/assets/56077231/02a8fbfe-c3f4-4243-bbdd-326a8a678f13)

![image](https://github.com/TencentBlueKing/bk-ci/assets/56077231/7e12a1e5-c7d9-41e6-a215-edb6a1245357)

**Comment by linpanru** [comment]
bk-ci is   v1.12.0-rc.8   helm install all pod is  running

**Comment by HYH21** [comment]
how to fix this？
