### ISSUE TITLE
feat：流水线名称长度放开到 128 个字符

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#9536]
目前名称长度不超过 40 个字符，放开到 128 个字符

- 新增页面
<img width="600" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/447ced5c-02f9-440d-845d-6c8c72257226">

- 编辑页面
<img width="600" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/e08ca51a-201b-4383-8069-fa8ba24a51ae">

**Comment by fabio-he** [comment]
![image](https://github.com/TencentBlueKing/bk-ci/assets/56472792/e7095bf4-d9b3-4635-b5c2-6279ca7b4a2f)
![image](https://github.com/TencentBlueKing/bk-ci/assets/56472792/5d08ed3a-c75d-4d90-b165-8910504812d3)
![企业微信截图_16975973353291](https://github.com/TencentBlueKing/bk-ci/assets/56472792/6a8e7df4-aead-4b50-946d-6ddd7c06b4a5)

**Comment by fabio-he** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
