### ISSUE TITLE
feat:【蓝盾】【产品评审会-已评审】支持为单个流水线模板设置权限

### ISSUE THREAD

**Issue by carrywang05** [TencentBlueKing/bk-ci#9574]
**背景**
目前蓝盾流水线模板的权限设计较为简单，为项目管理员可以编辑所有模板。这导致对于有较多模板的大型项目，无法对于单个模板进行单独授权，例如无法授权某一个开发人员（非项目管理员）来编辑和管理一个流水线模板。
近期亦有不少用户反馈。

**期望**
1、在蓝鲸权限中心注册资源【模板】，并为该资源增加相应操作：
- 模板列表
- 创建模板
- 查看模板
- 编辑模板
- 模板权限管理
- 删除模板

【模板】资源和流水线资源一样，都是归属于某一个蓝盾项目下。

2、项目管理员拥有模板的所有权限（该逻辑保持不变），其他项目默认用户组模板权限如下：
<img width="1322" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/46527215/7a0326b7-4676-4646-8cb8-df11f29b7add">

3、每个模板新增拥有者、编辑者两种角色，具体如下：
<img width="784" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/46527215/f676d0b2-b6e7-497a-a6ed-3a2f586e2db2">

4、页面UI如下（采用了嵌入蓝鲸权限中心页面的形式，类似于目前流水线权限管理的方案，实现成本较低）：
<img width="1206" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/46527215/39571c89-18c8-4777-a986-409191fcbccf">

备注：
该需求与流水线模板PAC耦合度很低，可以提前开发上线。

**Comment by EchoQT** [comment]
涉及到各个功能的权限对接方案需要明确，之前只明确了流水线部分。

**Comment by arsenalpoll** [comment]
用户信息打个码吧~

**Comment by carrywang05** [comment]
> 用户信息打个码吧~

已打码

**Comment by carrywang05** [comment]
> 涉及到各个功能的权限对接方案需要明确，之前只明确了流水线部分。

已补充模板【资源】【操作】和页面嵌入方式。

**Comment by EchoQT** [comment]
ok

**Comment by fcfang123** [comment]
后端迭代时间：
1、iam模型书写注册。0.5d
2、数据库 - 默认用户组配置表刷新组配置，0.5d
3、代码编写，3d。
4、前后端联调，2d。

**Comment by zhanxu33** [comment]
前端迭代时间：
1. 权限组件扩展支持模板 3天
2. 权限组件内嵌到页面 1天
3. 接口联调 2天
