### ISSUE TITLE
feat:【蓝盾】【无需评审会】流水线模板实例增加一个复制实例的功能

### ISSUE THREAD

**Issue by carrywang05** [TencentBlueKing/bk-ci#9579]
**背景**
目前部分游戏业务的流水线模板实例拥有超过100个入参，这些入参很多已经不是模版设置的默认值了。
例如有这样一个实例A，用户希望再新建一个类似的实例B，只有一两个入参数值的差异。目前用户只能基于模版去实例化，一个个入参去修改数值。但如果能够复制实例A，进行微改就可以得到实例B，就可以极大提升用户效率。

**期望**
（1）复制实例功能入口：
- 在流水线模板-实例列表，提供复制实例按钮
- 在流水线列表，对于模板实例化出的流水线实例，提供“复制为模板实例”按钮
- 在流水线详情页面，若为模板实例化出的流水线实例，提供“复制为模板实例”按钮

<img width="1495" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/46527215/f4c85a00-cde8-4cbc-8e43-fd43d3d3b1f8">

<img width="1495" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/46527215/b8cd3cfd-7fe8-437b-960e-846d8bbdcf71">

<img width="1495" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/46527215/6d9562a3-d5b7-4b1c-b64f-1654cb966487">

（2）点击按钮后进入新建实例页面
- 点击复制实例按钮，进入新建实例的页面。此时实例的版本、入参的数值、流水线实例名称（xxxx_copy）都已填好
- 如果实例名称不合适，可以点击编辑icon进行实例名称修改

<img width="1495" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/46527215/9d82186e-45fb-489f-8bf3-801a3f4b56f0">

备注：
该需求在新版流水线模板PAC的设计中也考虑到了。由于开发成本较低（只需要前端调整）且用户收益明显，所以想先在目前版本的模板功能中快速支持下。

**Comment by EchoQT** [comment]
流水线克隆不一起提供吗？
模板实例克隆的入口不局限于模板管理场景，流水线列表中也可以提供。
对模板实例的克隆可以暂时只考虑仍然归属于该模板的功能，后续有需要也可以再加克隆但与模板脱钩的功能。
明确一下，图示中的克隆出来的模板实例的3个参数是否是该模板的全部入参？有区分哪些入参是只读的吗？

**Comment by carrywang05** [comment]
> 流水线克隆不一起提供吗？ 模板实例克隆的入口不局限于模板管理场景，流水线列表中也可以提供。 对模板实例的克隆可以暂时只考虑仍然归属于该模板的功能，后续有需要也可以再加克隆但与模板脱钩的功能。 明确一下，图示中的克隆出来的模板实例的3个参数是否是该模板的全部入参？有区分哪些入参是只读的吗？

已经补充在流水线列表和流水线详情的模板实例复制入口。（目前已经有将模板实例复制为普通流水线的功能了，保留了该功能）
克隆出来的模板实例的参数是和老版的模板编辑页面保持一致，区分了流水线变量和模板常量。PAC新版设计会区分入参、常量和其他变量三种。

**Comment by EchoQT** [comment]
ok

**Comment by vhwweng** [comment]
前端迭代时间：3.5d
