### ISSUE TITLE
feat:【蓝盾】【无需评审会】流水线列表需要增加“模版实例”的标识

### ISSUE THREAD

**Issue by carrywang05** [TencentBlueKing/bk-ci#9596]
**背景**
在流水线列表中，一类是普通流水线，一类是模板实例。模板实例是无法直接编辑编排的，操作菜单也会有所区别。因此需要进行标识。

**期望**
- 在流水线列表的列表模式，对每个模板实例（也就是约束模式）增加标识；
- 在流水线列表的卡片模式，对每个模板实例（也就是约束模式）增加标识。
<img width="1087" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/46527215/b2fa7d37-9cd6-4d99-abe2-b1fd446f6b5d">

**Comment by vhwweng** [comment]
前端迭代时间：0.5d
