### ISSUE TITLE
优化GoAgent对于后台资源占用

### ISSUE THREAD

**Issue by tangruotian** [TencentBlueKing/bk-ci#9597]
优化 goagent 现有逻辑可能导致的后台资源浪费，具体如下
1 、整合升级心跳等到同一接口
2 、每秒会有心跳，升级，任务三个向后台的请求 -- [改造为以 websocket 长链接为主短链接为辅的方式](https://github.com/TencentBlueKing/bk-ci/issues/8777)

**Comment by irwinsun** [comment]
如果一台构建机器因为基础环境异常：
 - 目录迁移导致.agent.properties里的JDK路径不对、
 - worker丢失无法恢复、
 - 磁盘空间不足
 - 目录权限不正确权限不足
等包括并不局限于上述情况 ，通过升级也无法自愈恢复的，无法正常工作，平台应该:
 - [ ] 将异常信息上报给后台，并让其进程退出下线。
 - [ ] 异常信息在构建机详情页面：后台将异常信息通过 thirdPartyAgentDetail接口返回，前端修改放在 状态一行
<img width="725" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/16686129/5b8e7d2a-cfe5-4595-9fb1-fddb2fefc87f">
