### ISSUE TITLE
feat：流水线构建详情页支持一键展开/收起 job

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#9775]
1、支持一键展开/收起 job
<img width="400" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/eb31d4c1-d9c5-4336-8712-21287dde551b">
- 默认勾选，展开所有 job
- 去掉勾选后，收起所有Job

2、查看详情页链接，支持指定是否展开

**Comment by irwinsun** [comment]
这个展开和折叠功能建议也能做成所有 job 都适用，比如那些非 Matrix 的较大的编排其实也是需要，可以针对单个job 进行折叠
