### ISSUE TITLE
feat：第三方构建机支持使用 dcoker 运行构建任务

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#9820]
<img width="400" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/8280d990-aae4-4648-b381-d28d81100996">

- 当使用第三方构建机集群时，支持“启用 Docker 运行构建任务”。默认不启用。
- 启用后，支持选择镜像：
  - 若手动输入，私有镜像需指定凭据
- 启用后，支持设置  Volumes 、 Mounts、Gpus 参数
- 支持设置镜像拉取策略
  - 当镜像是 latest 版本时，默认选中 “每次运行时都拉取”
  - 当镜像不是latest版本时，默认选中 “当本地不存在时才拉取”

**Comment by tangruotian** [comment]
补充，
mounts 是列表
imagePullPolicy 镜像拉取策略 枚举 
"always"  ： 每次都重新拉取。
"if-not-present" 只有当镜像在本地不存在时才会拉取。
// policy 为空，并且容器镜像的标签是 :latest， image-pull-policy 会自动设置为 always
// policy 为空，并且为容器镜像指定了非 :latest 的标签， image-pull-policy 就会自动设置为 if-not-present
