### ISSUE TITLE
容器环境profile与T_DATA_SOURCE初始化不匹配

### ISSUE THREAD

**Issue by fitzcao** [TencentBlueKing/bk-ci#9901]
T_DATA_SOURCE 初始化环境为prod

服务的profile为dev

会导致获取不到数据源。创建项目失败

**Comment by stubenhuang** [comment]
已经修复了 , 相关代码:
https://github.com/TencentBlueKing/bk-ci/pull/9866/files#diff-c183f52a9609c2f969c5b61fb60fd4b468d2f30414e614b3999ed8edce3dcef2
