### ISSUE TITLE
版本体验对下架版本支持删除功能

### ISSUE THREAD

**Issue by zixinzhu723** [TencentBlueKing/bk-ci#992]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
版本体验的体验管理中，对下架的版本支持删除功能。

### 以便于
在蓝盾客户端查看体验版本时，会展示很多下架的包，不美观，希望对这些下架包支持删除

### 期望的验收标准
如果删除下架包，在蓝盾客户端查看体验版本时，只能看到可下载的未下载的包。

**Comment by iccengan** [comment]
@zixinzhu723 下架版本的删除功能，你是希望永久删除吗？还是可回收的？我们可以先讨论下这个需求场景哈。

**Comment by irwinsun** [comment]
此需求已经有“显示已过期体验” 过滤
